<?php defined('BASEPATH') or exit('No direct script access allowed');
class Migration_Version_130 extends App_module_migration {
 public function up(){
  update_option('smart_choice_core_enhancements_version','1.3.0');
  $table=db_prefix().'tickets_predefined_replies';
  if(!$this->db->table_exists($table)) return;
  $rows=[
   ['name'=>'Appointment Confirmation','message'=>'Your appointment has been scheduled. Our team will arrive within the confirmed time window. Please make sure the work area is accessible and let us know about gate codes, pets, or parking restrictions.'],
   ['name'=>'Appointment Reschedule','message'=>'We received your request to reschedule. Please provide two preferred dates and time windows, and our team will confirm the first available option.'],
   ['name'=>'Site Visit Preparation','message'=>'Before the site visit, please gather any surveys, plans, permits, HOA documents, product selections, photographs, or prior inspection reports related to the project.'],
   ['name'=>'Estimate Under Review','message'=>'Your estimate is currently being reviewed for scope, quantities, labor, material pricing, permit requirements, and scheduling. We will send the completed estimate as soon as the review is finished.'],
   ['name'=>'Estimate Revision Requested','message'=>'We received your requested estimate changes. The estimator will revise the affected scope and pricing and send an updated version for your review.'],
   ['name'=>'Proposal Sent','message'=>'Your proposal has been prepared and sent for review. Please review the scope, exclusions, payment schedule, and project notes before accepting.'],
   ['name'=>'Proposal Follow-Up','message'=>'We are following up to confirm that you received the proposal and to answer any questions about the scope, materials, pricing, or schedule.'],
   ['name'=>'Contract Ready for Signature','message'=>'Your contract is ready for review and signature. Please verify the customer information, project address, scope, payment terms, and listed selections before signing.'],
   ['name'=>'Deposit Required','message'=>'A deposit is required before materials can be ordered or the project can be placed on the production schedule. Please use the secure payment link shown on your invoice.'],
   ['name'=>'Payment Received','message'=>'Your payment has been received and applied to your account. Thank you. The remaining balance and next scheduled payment are shown on your invoice.'],
   ['name'=>'Partial Payment Received','message'=>'We received your partial payment. It has been applied to the current invoice, and the remaining amount is still due according to the payment schedule.'],
   ['name'=>'Payment Reminder','message'=>'This is a courteous reminder that a scheduled payment is approaching or due. Please review the invoice and contact us immediately if you have a question about the balance.'],
   ['name'=>'Invoice Overdue','message'=>'Our records show that the invoice remains unpaid after the due date. Please submit payment or contact our office to discuss the account.'],
   ['name'=>'Material Selection Needed','message'=>'We need your final material or color selection before ordering. Delayed selections may affect purchasing, lead times, and the project schedule.'],
   ['name'=>'Material Ordered','message'=>'The approved materials have been ordered. We will update you when the supplier confirms availability and the expected delivery date.'],
   ['name'=>'Material Backorder','message'=>'One or more selected materials are backordered. We are checking alternatives and updated delivery dates and will provide options before making substitutions.'],
   ['name'=>'Permit Application Submitted','message'=>'The permit application has been submitted to the appropriate building department. Approval times are controlled by the jurisdiction and may vary.'],
   ['name'=>'Permit Correction Required','message'=>'The building department requested additional information or corrections. Our team is addressing the request and will resubmit the documents.'],
   ['name'=>'Permit Approved','message'=>'The permit has been approved. We are coordinating the next project step, including material delivery, scheduling, and required inspections.'],
   ['name'=>'HOA Approval Required','message'=>'The project requires HOA or architectural review approval. Please submit the requested documents and written authorization before work begins.'],
   ['name'=>'Engineering Documents Needed','message'=>'Engineering drawings or calculations are required before permitting or construction. We will coordinate measurements and provide the engineer with the project information.'],
   ['name'=>'Engineering Site Visit','message'=>'An engineering site visit is required. Please make all affected areas accessible and provide any existing plans, surveys, or structural information.'],
   ['name'=>'Project Scheduled','message'=>'Your project has been placed on the production schedule. Dates may change because of weather, inspections, material availability, or approved change orders.'],
   ['name'=>'Crew Arrival Notice','message'=>'Our crew is scheduled to arrive during the confirmed time window. Please secure pets, clear personal items, and provide access to the work area.'],
   ['name'=>'Weather Delay','message'=>'Work has been delayed because weather conditions are unsafe or unsuitable for the scheduled activity. We will provide the next available work date.'],
   ['name'=>'Inspection Scheduled','message'=>'The required inspection has been scheduled. The inspector controls the arrival time, so the work area must remain accessible for the full inspection window.'],
   ['name'=>'Inspection Passed','message'=>'The scheduled inspection passed. The project may proceed to the next approved phase.'],
   ['name'=>'Inspection Correction','message'=>'The inspector requested a correction. Our team will complete the required work and schedule a reinspection.'],
   ['name'=>'Change Order Required','message'=>'The requested work is outside the current contract scope or results from concealed conditions. A written change order must be approved before the additional work begins.'],
   ['name'=>'Change Order Approved','message'=>'The change order has been approved and added to the project. Pricing, payment requirements, and scheduling impacts are shown in the approved document.'],
   ['name'=>'Hidden Damage Found','message'=>'After opening the work area, we found concealed damage or an unforeseen condition. We will document the issue and provide the recommended repair and pricing before proceeding.'],
   ['name'=>'Customer Access Needed','message'=>'We need access to the property or a specific room to continue work. Please confirm the access arrangement and any alarm, gate, parking, or lockbox instructions.'],
   ['name'=>'Utility Shutoff Required','message'=>'A temporary electrical, water, gas, HVAC, or other utility interruption is required. We will coordinate the expected time and duration before beginning.'],
   ['name'=>'Work Area Preparation','message'=>'Please remove furniture, decorations, valuables, appliances, and personal items from the work area before the crew arrives.'],
   ['name'=>'Daily Project Update','message'=>'Today the team completed the scheduled work and prepared the area for the next phase. We will continue according to the current project schedule.'],
   ['name'=>'Project Delay Update','message'=>'The project schedule has been affected by an unexpected condition. We are working to reduce the delay and will provide a revised sequence or date when confirmed.'],
   ['name'=>'Subcontractor Scheduled','message'=>'A licensed or qualified subcontractor has been scheduled for the next phase. Their work will be coordinated with the project manager and required inspections.'],
   ['name'=>'Electrical Work Update','message'=>'The electrical work is progressing according to the approved scope. Power interruptions and inspections will be coordinated before they occur.'],
   ['name'=>'Plumbing Work Update','message'=>'The plumbing work is progressing according to the approved scope. Water interruptions, pressure testing, and inspections will be coordinated as required.'],
   ['name'=>'HVAC Work Update','message'=>'The HVAC work is progressing according to the approved scope. Equipment startup, testing, balancing, and inspections will be coordinated as required.'],
   ['name'=>'Roofing Work Update','message'=>'The roofing work is progressing according to the approved scope. Weather conditions and required inspections may affect the daily schedule.'],
   ['name'=>'Drywall Work Update','message'=>'Drywall installation or repair is underway. Multiple visits may be required for hanging, finishing, drying, sanding, texture, and paint preparation.'],
   ['name'=>'Painting Work Update','message'=>'Painting preparation or application is underway. Please avoid touching coated surfaces until the crew confirms that they are dry.'],
   ['name'=>'Flooring Work Update','message'=>'Flooring installation is underway. Please avoid the work area until adhesives, grout, coatings, or setting materials have cured.'],
   ['name'=>'Cabinet Installation Update','message'=>'Cabinet installation is underway. Final adjustments may occur after countertops, appliances, hardware, and related finishes are installed.'],
   ['name'=>'Countertop Template Scheduled','message'=>'The countertop template appointment has been scheduled. Cabinets must be permanently installed and final sink, faucet, and appliance information must be available.'],
   ['name'=>'Countertop Installation Scheduled','message'=>'Countertop installation has been scheduled. Please clear access paths and confirm that plumbing reconnection will be coordinated separately when required.'],
   ['name'=>'Window or Door Measurement','message'=>'A final field measurement is required before ordering windows or doors. Product orders may not be changed after approval without additional cost.'],
   ['name'=>'Concrete Work Scheduled','message'=>'Concrete work has been scheduled. Weather, site access, inspections, and curing requirements may affect the timing.'],
   ['name'=>'Final Walkthrough Scheduled','message'=>'The final walkthrough has been scheduled. We will review the completed scope, note any remaining punch-list items, and discuss closeout documents.'],
   ['name'=>'Punch List Received','message'=>'We received the punch-list items. The project manager will review them, confirm which items are within the contracted scope, and schedule approved corrections.'],
   ['name'=>'Punch List Completed','message'=>'The approved punch-list work has been completed. Please review the corrected items and notify us promptly if anything remains unresolved.'],
   ['name'=>'Project Substantially Complete','message'=>'The contracted work is substantially complete and ready for final review, closeout, and any required final payment.'],
   ['name'=>'Final Payment Due','message'=>'The project has reached the stage requiring final payment. Please review the invoice and submit the remaining balance according to the contract.'],
   ['name'=>'Project Closed','message'=>'The project has been closed in our system. Thank you for choosing Smart Choice Contractors USA.'],
   ['name'=>'Warranty Service Request Received','message'=>'We received your service request and will review the issue against the completed scope, product documentation, and applicable workmanship terms.'],
   ['name'=>'Warranty Inspection Scheduled','message'=>'A warranty or service inspection has been scheduled. Please make the affected area accessible and avoid altering the condition before inspection.'],
   ['name'=>'Not Covered by Original Scope','message'=>'The reported item does not appear to be included in the original contracted scope. We can prepare a separate service estimate after reviewing the condition.'],
   ['name'=>'Photo Request','message'=>'Please send clear photographs and, when useful, a short video showing the affected area from both close and wide angles.'],
   ['name'=>'Document Request','message'=>'Please provide the requested survey, permit, plan, receipt, product information, HOA approval, inspection report, or other supporting document.'],
   ['name'=>'Customer Approval Needed','message'=>'We need your written approval before proceeding with the listed selection, change, repair, purchase, or scheduling decision.'],
   ['name'=>'Unable to Reach Customer','message'=>'We attempted to contact you but were unable to connect. Please reply with the best telephone number and time to reach you.'],
   ['name'=>'Voicemail Follow-Up','message'=>'We left a voicemail regarding your project or service request. Please reply when convenient so we can continue assisting you.'],
   ['name'=>'Ticket Assigned','message'=>'Your request has been assigned to the appropriate team member for review and follow-up.'],
   ['name'=>'Ticket Escalated','message'=>'Your request has been escalated to management or the project manager for additional review.'],
   ['name'=>'Ticket Resolved','message'=>'The reported issue has been addressed based on the information available. Please reply if further assistance is still needed.'],
   ['name'=>'Emergency Service Guidance','message'=>'If there is an immediate danger involving fire, active flooding, gas odor, electrical arcing, structural instability, or personal safety, contact emergency services and the appropriate utility before contacting our office.'],
   ['name'=>'License and Insurance Request','message'=>'We can provide current licensing and insurance information appropriate to the project and jurisdiction upon request.'],
   ['name'=>'Supplier Delivery Notice','message'=>'A supplier delivery is scheduled. Please keep the driveway, access route, and designated staging area clear.'],
   ['name'=>'Delivery Delayed','message'=>'The supplier has delayed delivery. We are confirming the revised date and evaluating whether the schedule can be adjusted.'],
   ['name'=>'Debris Removal Scheduled','message'=>'Construction debris removal has been scheduled. Please keep the dumpster or pickup area accessible.'],
   ['name'=>'Cleaning Scheduled','message'=>'Project cleaning has been scheduled. This service is limited to construction-related debris and dust within the contracted work area.'],
   ['name'=>'Customer-Supplied Material Issue','message'=>'A customer-supplied product is missing, damaged, incompatible, or unavailable. Work may pause until an acceptable replacement is provided.'],
   ['name'=>'Product Substitution Approval','message'=>'The originally selected product is unavailable or unsuitable. Please review and approve the proposed substitution before ordering.'],
   ['name'=>'Scope Clarification','message'=>'The requested clarification has been reviewed. The written contract, approved proposal, drawings, specifications, and change orders control the project scope.'],
   ['name'=>'Schedule Confirmation Needed','message'=>'Please confirm the proposed work date so we can reserve the crew and coordinate materials.'],
   ['name'=>'Cancellation Request Received','message'=>'We received your cancellation request. Management will review the contract status, ordered materials, completed work, and applicable charges before confirming cancellation.'],
   ['name'=>'Refund Review','message'=>'Your refund request is under review. Any approved refund will account for payments, completed work, ordered materials, fees, and contract terms.'],
   ['name'=>'Referral Thank You','message'=>'Thank you for referring a customer to Smart Choice Contractors USA. We appreciate your trust and support.'],
   ['name'=>'Review Request','message'=>'Thank you for choosing Smart Choice Contractors USA. We would appreciate an honest review of your experience after the project is complete.'],
   ['name'=>'Construction Noise Notice','message'=>'Construction may create temporary noise, vibration, dust, and traffic. We will make reasonable efforts to limit disruption during approved working hours.'],
   ['name'=>'Neighbor Access Coordination','message'=>'The project may require temporary access near an adjoining property or shared area. Written permission must be obtained before access is used.'],
   ['name'=>'Lead-Safe Work Notice','message'=>'The property may require lead-safe work practices based on age, testing, or scope. Required containment and cleaning procedures may affect cost and schedule.'],
   ['name'=>'Mold or Moisture Concern','message'=>'Visible moisture or suspected microbial growth requires evaluation before concealed repairs are completed. Additional testing or remediation may be recommended.'],
   ['name'=>'Asbestos Concern','message'=>'Suspected asbestos-containing material must be evaluated before disturbance. Testing and specialized abatement may be required.'],
   ['name'=>'Final Documents Available','message'=>'Your final invoice, approvals, photographs, inspection records, or closeout documents are available in the customer portal.'],
  ];
  foreach($rows as $row){
   $exists=$this->db->where('name',$row['name'])->count_all_results($table);
   if(!$exists){$this->db->insert($table,$row);}
  }
 }
}
