<?php defined('BASEPATH') or exit('No direct script access allowed'); ?>
<?php init_head(); ?>
<div id="wrapper"><div class="content usi-seo"><div class="row"><div class="col-md-12">
<?php $this->load->view('usi_smartchoice_seo/partials/top'); ?>
<div class="panel_s"><div class="panel-body">
<div class="usi-toolbar"><h4><?php echo _l('usi_smartchoice_seo_pages'); ?></h4><div class="usi-actions">
<?php if (has_permission('usi_smartchoice_seo','','create')) { ?><a href="<?php echo admin_url('usi_smartchoice_seo/page'); ?>" class="btn btn-sm btn-primary"><i class="fa fa-plus"></i> <?php echo _l('usi_smartchoice_seo_new_page'); ?></a><?php } ?>
<a href="<?php echo admin_url('usi_smartchoice_seo/reports'); ?>" class="btn btn-sm btn-default"><i class="fa fa-bar-chart"></i> <?php echo _l('usi_smartchoice_seo_reports'); ?></a>
<a href="<?php echo admin_url('usi_smartchoice_seo/keywords'); ?>" class="btn btn-sm btn-default"><i class="fa fa-search"></i> <?php echo _l('usi_smartchoice_seo_keywords'); ?></a>
<a href="<?php echo admin_url('usi_smartchoice_seo/pages'); ?>" class="btn btn-sm btn-default"><i class="fa fa-refresh"></i> <?php echo _l('usi_smartchoice_seo_reload'); ?></a>
<a href="<?php echo admin_url('usi_smartchoice_seo/export/pages?' . http_build_query($filters ?? [])); ?>" class="btn btn-sm btn-default"><i class="fa fa-download"></i> <?php echo _l('export'); ?></a>
<a href="<?php echo admin_url('usi_smartchoice_seo/sample_header/pages'); ?>" class="btn btn-sm btn-default"><i class="fa fa-table"></i> <?php echo _l('usi_smartchoice_seo_sample_header'); ?></a>
</div></div>
<form method="get" class="usi-filter"><div class="row"><div class="col-md-3"><?php echo render_input('search','usi_smartchoice_seo_filter_header',$filters['search'] ?? ''); ?></div><div class="col-md-2"><?php echo render_input('status','status',$filters['status'] ?? ''); ?></div><div class="col-md-2"><?php echo render_input('city','usi_smartchoice_seo_city',$filters['city'] ?? ''); ?></div><div class="col-md-2"><?php echo render_input('page_type','usi_smartchoice_seo_page_type',$filters['page_type'] ?? ''); ?></div><div class="col-md-3 usi-filter-buttons"><button class="btn btn-sm btn-primary" type="submit"><?php echo _l('filter'); ?></button><a class="btn btn-sm btn-default" href="<?php echo admin_url('usi_smartchoice_seo/pages'); ?>"><?php echo _l('clear'); ?></a></div></div></form>
<?php echo form_open_multipart(admin_url('usi_smartchoice_seo/import/pages'), ['class'=>'usi-import']); ?><input type="file" name="import_file" accept=".csv"> <button class="btn btn-sm btn-default" type="submit"><i class="fa fa-upload"></i> <?php echo _l('import'); ?></button><?php echo form_close(); ?>
<?php echo form_open(admin_url('usi_smartchoice_seo/mass_delete_pages'), ['class'=>'usi-mass-form']); ?>
<div class="table-responsive"><table class="table table-striped table-condensed usi-compact-table"><thead><tr><th class="usi-check"><input type="checkbox" class="usi-check-all"></th><th><?php echo _l('title'); ?></th><th><?php echo _l('usi_smartchoice_seo_slug'); ?></th><th><?php echo _l('usi_smartchoice_seo_keyword'); ?></th><th><?php echo _l('usi_smartchoice_seo_city'); ?></th><th><?php echo _l('status'); ?></th><th><?php echo _l('options'); ?></th></tr></thead><tbody>
<?php foreach ($pages as $row) { ?><tr><td><input type="checkbox" name="ids[]" value="<?php echo (int)$row['id']; ?>"></td><td><?php echo html_escape($row['title']); ?></td><td><?php echo html_escape($row['slug']); ?></td><td><?php echo html_escape($row['primary_keyword']); ?></td><td><?php echo html_escape($row['city']); ?></td><td><span class="label label-default"><?php echo html_escape(ucfirst($row['status'])); ?></span></td><td><a class="btn btn-xs btn-default" href="<?php echo admin_url('usi_smartchoice_seo/view_page/' . (int)$row['id']); ?>"><?php echo _l('view'); ?></a> <a class="btn btn-xs btn-default" href="<?php echo admin_url('usi_smartchoice_seo/page/' . (int)$row['id']); ?>"><?php echo _l('edit'); ?></a> <?php if (has_permission('usi_smartchoice_seo','','delete')) { ?><a class="btn btn-xs btn-danger _delete" href="<?php echo admin_url('usi_smartchoice_seo/delete_page/' . (int)$row['id']); ?>"><?php echo _l('delete'); ?></a><?php } ?></td></tr><?php } ?>
<?php if (empty($pages)) { ?><tr><td colspan="7" class="text-center text-muted"><?php echo _l('no_results_found'); ?></td></tr><?php } ?>
</tbody></table></div><?php if (has_permission('usi_smartchoice_seo','','delete')) { ?><div class="usi-table-footer"><button class="btn btn-sm btn-danger" type="submit"><i class="fa fa-trash"></i> <?php echo _l('usi_smartchoice_seo_mass_delete'); ?></button></div><?php } ?><?php echo form_close(); ?>
</div></div>
</div></div></div></div>
<?php init_tail(); ?></body></html>
