<?php defined('BASEPATH') or exit('No direct script access allowed'); init_head(); ?>
<div id="wrapper"><div class="content"><div class="panel_s"><div class="panel-body">
<h4><i class="fa fa-shopping-cart"></i> Home Depot Pro Lists</h4><?php $this->load->view('estimating_hub_ai/partials/nav',['nav'=>$nav]); ?>
<div class="alert alert-info">Use this section to build Home Depot Pro Desk material lists. Direct private Pro Xtra account automation requires an approved Home Depot integration or partner API. This module safely exports/imports SKU lists and creates printable quote requests.</div>
<div class="scie-card"><h4>Add Home Depot Item</h4><?php echo form_open(admin_url('estimating_hub_ai/home_depot')); ?><?php echo form_hidden($this->security->get_csrf_token_name(), $this->security->get_csrf_hash()); ?><div class="row"><div class="col-md-2"><label>SKU</label><input name="sku" class="form-control input-sm"></div><div class="col-md-3"><label>Item Name</label><input name="item_name" class="form-control input-sm" required></div><div class="col-md-2"><label>Unit</label><input name="unit" class="form-control input-sm" value="each"></div><div class="col-md-2"><label>Target Price</label><input name="last_price" class="form-control input-sm scie-money" placeholder="99,999.99" maxlength="9"></div><div class="col-md-3"><label>Home Depot Link</label><input name="url" class="form-control input-sm" placeholder="https://www.homedepot.com/"></div></div><br><button class="btn btn-success btn-sm">Add To List</button> <a href="https://www.homedepot.com/" target="_blank" class="btn btn-warning btn-sm">Open Home Depot</a> <a href="<?php echo admin_url('estimating_hub_ai/cost_database'); ?>" class="btn btn-info btn-sm">Allowed Pricing Section</a><?php echo form_close(); ?></div>
<div class="scie-toolbar"><button type="button" class="btn btn-info btn-sm" onclick="$('.scie-advanced-filters').toggle();">Filters</button><a href="<?php echo admin_url('estimating_hub_ai/sample_home_depot'); ?>" class="btn btn-default btn-sm">Sample Header</a><button type="button" class="btn btn-primary btn-sm" onclick="$('#hdImportBox').toggle();">Import</button><a href="<?php echo admin_url('estimating_hub_ai/export_home_depot'); ?>" class="btn btn-default btn-sm">Export</a><a href="<?php echo admin_url('estimating_hub_ai/print_home_depot'); ?>" target="_blank" class="btn btn-default btn-sm">PDF Print</a><a href="<?php echo admin_url('estimating_hub_ai/reload'); ?>" class="btn btn-default btn-sm">Reload</a><button form="hdMassForm" class="btn btn-danger btn-sm" onclick="return confirm('Are you sure you want to delete the selected records?');">Mass Delete</button><input class="form-control input-sm scie-filter" placeholder="Search Home Depot items..."></div>
<div id="hdImportBox" class="scie-import-box" style="display:none"><?php echo form_open_multipart(admin_url('estimating_hub_ai/import_home_depot')); ?><?php echo form_hidden($this->security->get_csrf_token_name(), $this->security->get_csrf_hash()); ?><input type="file" name="import_file" accept=".csv" required> <button class="btn btn-success btn-sm">Accept And Import</button><?php echo form_close(); ?></div>
<div class="scie-advanced-filters" style="display:none"><input class="form-control input-sm scie-filter" placeholder="Filter by SKU, item, unit, price, or source..."></div>
<?php echo form_open(admin_url('estimating_hub_ai/mass_delete_home_depot'), ['id'=>'hdMassForm']); ?><?php echo form_hidden($this->security->get_csrf_token_name(), $this->security->get_csrf_hash()); ?><div class="table-responsive"><table class="table table-striped table-condensed scie-table"><thead><tr><th><input type="checkbox" class="scie-check-all"></th><th>SKU</th><th>Item</th><th>Unit</th><th>Target Price</th><th>Link</th><th>Updated</th></tr></thead><tbody><?php foreach($links as $l): ?><tr class="scie-filter-row"><td><input type="checkbox" name="ids[]" value="<?php echo (int)$l['id']; ?>"></td><td><?php echo html_escape($l['sku']); ?></td><td><?php echo html_escape($l['item_name']); ?></td><td><?php echo html_escape($l['unit']); ?></td><td>$<?php echo number_format((float)$l['last_price'],2,'.',','); ?></td><td><?php if(!empty($l['url'])): ?><a href="<?php echo html_escape($l['url']); ?>" target="_blank">Open</a><?php endif; ?></td><td><?php echo _dt($l['dateupdated']); ?></td></tr><?php endforeach; ?></tbody></table></div><?php echo form_close(); ?>
</div></div></div></div><?php init_tail(); ?>
