<?php defined('BASEPATH') or exit('No direct script access allowed'); init_head(); ?>
<div id="wrapper"><div class="content"><div class="panel_s"><div class="panel-body">
<h4><i class="fa fa-chart-line"></i> Estimating Reports</h4><?php $this->load->view('estimating_hub_ai/partials/nav',['nav'=>$nav]); ?>
<div class="scie-toolbar"><button type="button" class="btn btn-info btn-sm" onclick="$('.scie-advanced-filters').toggle();">Filters</button><a href="<?php echo admin_url('estimating_hub_ai/export_reports'); ?>" class="btn btn-default btn-sm">Export</a><a href="<?php echo admin_url('estimating_hub_ai/reload'); ?>" class="btn btn-default btn-sm">Reload</a><input class="form-control input-sm scie-filter" placeholder="Search reports..."></div>
<div class="row"><div class="col-md-3"><a class="scie-stat" href="<?php echo admin_url('estimating_hub_ai/search?q=estimate'); ?>"><strong><?php echo (int)$stats['estimates']; ?></strong><span>Estimate Drafts</span></a></div><div class="col-md-3"><a class="scie-stat" href="<?php echo admin_url('estimating_hub_ai/cost_database'); ?>"><strong><?php echo (int)$stats['cost_items']; ?></strong><span>Cost Items</span></a></div><div class="col-md-3"><a class="scie-stat" href="<?php echo admin_url('estimating_hub_ai/documents'); ?>"><strong><?php echo (int)$stats['documents']; ?></strong><span>Training Documents</span></a></div><div class="col-md-3"><a class="scie-stat" href="<?php echo admin_url('estimating_hub_ai/home_depot'); ?>"><strong><?php echo (int)$stats['home_depot']; ?></strong><span>Home Depot Items</span></a></div></div>
<div class="scie-advanced-filters" style="display:none"><input class="form-control input-sm scie-filter" placeholder="Filter by source, trade, category, report type..."></div>
<h4>Cost Database Source Report</h4><div class="table-responsive"><table class="table table-striped table-condensed scie-table"><thead><tr><th>Source</th><th>Total Records</th></tr></thead><tbody><?php foreach($sources as $s): ?><tr class="scie-filter-row"><td><?php echo html_escape($s['source'] ?: 'Manual'); ?></td><td><?php echo (int)$s['total']; ?></td></tr><?php endforeach; ?></tbody></table></div>
<h4>Cost Items Report</h4><div class="table-responsive"><table class="table table-striped table-condensed scie-table"><thead><tr><th>Trade</th><th>Category</th><th>Item</th><th>Typical Cost</th><th>Source</th></tr></thead><tbody><?php foreach($items as $i): ?><tr class="scie-filter-row"><td><?php echo html_escape($i['trade']); ?></td><td><?php echo html_escape($i['category']); ?></td><td><?php echo html_escape($i['item_name']); ?></td><td>$<?php echo number_format((float)$i['material_cost_typical'],2,'.',','); ?></td><td><?php echo html_escape($i['source'] ?? 'Manual'); ?></td></tr><?php endforeach; ?></tbody></table></div>
</div></div></div></div><?php init_tail(); ?>
