<?php defined('BASEPATH') or exit('No direct script access allowed'); init_head(); $v=$verification ?? []; ?>
<div id="wrapper"><div class="content usi-seo"><div class="panel_s"><div class="panel-body">
<?php $this->load->view('usi_smartchoice_seo/partials/top'); ?>
<div class="sc-toolbar"><h4><i class="fa fa-check-circle"></i> <?php echo html_escape($title); ?></h4><div class="sc-toolbar-actions"><a class="btn btn-default btn-sm" href="<?php echo admin_url('usi_smartchoice_seo/field_verifications'); ?>"><i class="fa fa-arrow-left"></i> Back</a><a class="btn btn-default btn-sm" href="<?php echo admin_url('usi_smartchoice_seo/field_verification/'.(int)($v['id'] ?? 0)); ?>"><i class="fa fa-pencil"></i> Edit</a><a class="btn btn-success btn-sm" href="<?php echo admin_url('usi_smartchoice_seo/mark_field_verification_ready/'.(int)($v['id'] ?? 0)); ?>"><i class="fa fa-check"></i> Mark Ready</a><?php if(!empty($v['ai_estimate_id'])){ ?><a class="btn btn-info btn-sm" href="<?php echo admin_url('usi_smartchoice_seo/view_ai_estimate/'.(int)$v['ai_estimate_id']); ?>"><i class="fa fa-calculator"></i> Open Estimate</a><?php } ?></div></div>
<?php if(!$v){ ?><div class="alert alert-warning">Field verification record was not found.</div><?php } else { ?>
<table class="table table-bordered usi-detail-table"><tbody>
<tr><th>Title</th><td><?php echo html_escape($v['verification_title']); ?></td></tr><tr><th>Status</th><td><?php echo ucwords(str_replace('_',' ',html_escape($v['field_status']))); ?></td></tr><tr><th>Ready For Estimate</th><td><?php echo ((int)$v['ready_for_estimate']===1?'Yes':'No'); ?></td></tr><tr><th>AI Estimate ID</th><td><?php echo (int)$v['ai_estimate_id']; ?></td></tr><tr><th>Customer ID</th><td><?php echo (int)$v['customer_id']; ?></td></tr><tr><th>Project ID</th><td><?php echo (int)$v['project_id']; ?></td></tr><tr><th>Jobsite Address</th><td><?php echo html_escape($v['jobsite_address']); ?></td></tr><tr><th>Verified By</th><td><?php echo (int)$v['verified_by']; ?></td></tr><tr><th>Verified At</th><td><?php echo html_escape($v['verified_at']); ?></td></tr>
</tbody></table>
<div class="row"><div class="col-md-4"><div class="sc-card"><h4>Measurements</h4><p><?php echo nl2br(html_escape($v['measurement_summary'])); ?></p></div></div><div class="col-md-4"><div class="sc-card"><h4>Checklist</h4><p><?php echo nl2br(html_escape($v['inspection_checklist'])); ?></p></div></div><div class="col-md-4"><div class="sc-card"><h4>Photo Notes</h4><p><?php echo nl2br(html_escape($v['photo_notes'])); ?></p></div></div></div>
<?php } ?>
</div></div></div></div><?php init_tail(); ?>