<?php defined('BASEPATH') or exit('No direct script access allowed'); ?>
<?php init_head(); ?>
<div id="wrapper"><div class="content"><div class="row"><div class="col-md-12"><div class="panel_s"><div class="panel-body">
<div class="sc-sammy-header"><div><h4 class="no-margin"><?php echo html_escape($workflow['workflow_name']); ?></h4><p class="text-muted mtop5"><?php echo html_escape($workflow['description']); ?></p></div><div class="sc-sammy-toolbar"><a href="<?php echo admin_url('usi_smartchoice_seo/workflow_engine'); ?>" class="btn btn-default btn-sm">Workflow Engine</a><a href="<?php echo admin_url('usi_smartchoice_seo/workflow/' . (int)$workflow['id']); ?>" class="btn btn-info btn-sm">Edit</a><a href="<?php echo admin_url('usi_smartchoice_seo/run_workflow/' . (int)$workflow['id']); ?>" class="btn btn-success btn-sm">Run Test</a></div></div>
<hr class="hr-panel-heading" />
<div class="row"><div class="col-md-5"><h5>Add Workflow Step</h5><?php echo form_open(admin_url('usi_smartchoice_seo/save_workflow_step')); ?><input type="hidden" name="workflow_id" value="<?php echo (int)$workflow['id']; ?>"><div class="form-group"><label>Step Order</label><input type="number" name="step_order" class="form-control" value="<?php echo count($steps)+1; ?>"></div><div class="form-group"><label>Step Name</label><input type="text" name="step_name" class="form-control" required></div><div class="row"><div class="col-md-6"><div class="form-group"><label>Step Type</label><select name="step_type" class="form-control"><option value="action">Action</option><option value="condition">Condition</option><option value="delay">Delay</option><option value="approval">Approval</option><option value="log">Log</option></select></div></div><div class="col-md-6"><div class="form-group"><label>Action Type</label><input type="text" name="action_type" class="form-control" value="create_alert"></div></div></div><div class="form-group"><label>Target Area</label><input type="text" name="target_area" class="form-control" value="sammy_ai"></div><div class="form-group"><label>Delay Minutes</label><input type="number" name="delay_minutes" class="form-control" value="0"></div><div class="checkbox checkbox-primary"><input type="checkbox" name="requires_approval" id="requires_approval"><label for="requires_approval">Requires Approval</label></div><div class="form-group"><label>Step Payload</label><textarea name="step_payload" class="form-control" rows="4"></textarea></div><button type="submit" class="btn btn-success btn-sm">Add Step</button><?php echo form_close(); ?></div>
<div class="col-md-7"><h5>Steps</h5><div class="table-responsive"><table class="table table-bordered table-striped sc-compact-table"><thead><tr><th>Order</th><th>Name</th><th>Type</th><th>Action</th><th>Approval</th></tr></thead><tbody><?php if (empty($steps)) { ?><tr><td colspan="5" class="text-center text-muted">No steps found.</td></tr><?php } ?><?php foreach ($steps as $step) { ?><tr><td><?php echo (int)$step['step_order']; ?></td><td><?php echo html_escape($step['step_name']); ?></td><td><?php echo html_escape($step['step_type']); ?></td><td><?php echo html_escape($step['action_type']); ?></td><td><?php echo (int)$step['requires_approval'] === 1 ? 'Yes' : 'No'; ?></td></tr><?php } ?></tbody></table></div><h5>Runs</h5><div class="table-responsive"><table class="table table-bordered table-striped sc-compact-table"><thead><tr><th>ID</th><th>Status</th><th>Started</th><th>Completed</th><th>Result</th></tr></thead><tbody><?php if (empty($runs)) { ?><tr><td colspan="5" class="text-center text-muted">No runs found.</td></tr><?php } ?><?php foreach ($runs as $run) { ?><tr><td><?php echo (int)$run['id']; ?></td><td><?php echo html_escape($run['run_status']); ?></td><td><?php echo html_escape($run['started_at']); ?></td><td><?php echo html_escape($run['completed_at']); ?></td><td><?php echo html_escape($run['result_message']); ?></td></tr><?php } ?></tbody></table></div></div></div>
</div></div></div></div></div></div>
<?php init_tail(); ?></body></html>
