<?php

defined('BASEPATH') or exit('No direct script access allowed');

function scp_slug_193($value) {
    $value = strtolower(trim(preg_replace('/[^A-Za-z0-9]+/', '-', $value), '-'));
    return $value ?: 'product';
}
function scp_get_category_193($CI, $name) {
    $CI->db->where('p_category_name', $name);
    $row = $CI->db->get(db_prefix() . 'product_categories')->row();
    if ($row) { return (int) $row->p_category_id; }
    $CI->db->insert(db_prefix() . 'product_categories', ['p_category_name'=>$name, 'p_category_description'=>$name . ' services']);
    return (int) $CI->db->insert_id();
}
function scp_get_variation_193($CI, $name) {
    $CI->db->where('name', $name);
    $row = $CI->db->get(db_prefix() . 'variations')->row();
    if ($row) { return (int) $row->id; }
    $CI->db->insert(db_prefix() . 'variations', ['name'=>$name, 'description'=>$name]);
    return (int) $CI->db->insert_id();
}
function scp_get_value_193($CI, $variation_id, $value, $order) {
    $CI->db->where('variation_id', $variation_id);
    $CI->db->where('value', $value);
    $row = $CI->db->get(db_prefix() . 'variation_values')->row();
    if ($row) { return (int) $row->id; }
    $CI->db->insert(db_prefix() . 'variation_values', ['variation_id'=>$variation_id, 'value'=>$value, 'value_order'=>$order, 'description'=>$value]);
    return (int) $CI->db->insert_id();
}
function scp_product_193($CI, $category_id, $name, $description, $rate, $groups) {
    $CI->db->where('product_name', $name);
    $existing = $CI->db->get(db_prefix() . 'product_master')->row();
    if ($existing) {
        $product_id = (int) $existing->id;
        $CI->db->where('id', $product_id);
        $CI->db->update(db_prefix() . 'product_master', ['product_category_id'=>$category_id, 'product_description'=>$description, 'rate'=>$rate, 'quantity_number'=>999, 'is_variation'=>1, 'is_digital'=>0, 'slug'=>scp_slug_193($name)]);
    } else {
        $CI->db->insert(db_prefix() . 'product_master', ['product_name'=>$name, 'slug'=>scp_slug_193($name), 'product_description'=>$description, 'product_category_id'=>$category_id, 'rate'=>$rate, 'taxes'=>'', 'quantity_number'=>999, 'product_image'=>'image-not-available.png', 'is_digital'=>0, 'recurring'=>0, 'recurring_type'=>'', 'custom_recurring'=>0, 'cycles'=>0, 'is_variation'=>1]);
        $product_id = (int) $CI->db->insert_id();
    }
    $CI->db->where('product_id', $product_id);
    $CI->db->delete(db_prefix() . 'product_variations');
    $offset = 0;
    foreach ($groups as $groupName => $values) {
        $variation_id = scp_get_variation_193($CI, $groupName);
        $order = 1;
        foreach ($values as $value) {
            $value_id = scp_get_value_193($CI, $variation_id, $value, $order);
            $rate_adjusted = $rate + ($offset * 25) + (($order - 1) * 35);
            $CI->db->insert(db_prefix() . 'product_variations', ['product_id'=>$product_id, 'variation_id'=>$variation_id, 'variation_value_id'=>$value_id, 'rate'=>$rate_adjusted, 'quantity_number'=>999]);
            $order++;
        }
        $offset++;
    }
}

if (!function_exists('products_smartchoice_catalog_seed_193')) {
    function products_smartchoice_catalog_seed_193()
    {
        $CI = &get_instance();
        $CI->db->query('SET foreign_key_checks = 0');

        if (!$CI->db->field_exists('slug', db_prefix() . 'product_master')) {
            $CI->db->query('ALTER TABLE `' . db_prefix() . 'product_master` ADD `slug` VARCHAR(220) NULL DEFAULT NULL AFTER `product_name`');
        }

        $catId = scp_get_category_193($CI, 'Flooring');
        scp_product_193($CI, $catId, 'Luxury Vinyl Plank Installation', 'Homeowner service package for luxury vinyl plank installation with clear options, starting price, and Smart Choice Contractors USA workflow.', 250, ['Removal'=>['Existing Floor Removal','No Removal'],'Furniture Moving'=>['Furniture Move Included','No'],'Stairs'=>['Yes','No'],'Baseboard Option'=>['Quarter Round','New Baseboards','No'],'Moisture Barrier'=>['Yes','No'],'Pattern'=>['Straight Lay','Diagonal Pattern','Herringbone']]);
        scp_product_193($CI, $catId, 'Laminate Flooring Installation', 'Homeowner service package for laminate flooring installation with clear options, starting price, and Smart Choice Contractors USA workflow.', 300, ['Removal'=>['Existing Floor Removal','No Removal'],'Furniture Moving'=>['Furniture Move Included','No'],'Stairs'=>['Yes','No'],'Baseboard Option'=>['Quarter Round','New Baseboards','No'],'Moisture Barrier'=>['Yes','No'],'Pattern'=>['Straight Lay','Diagonal Pattern','Herringbone']]);
        scp_product_193($CI, $catId, 'Tile Flooring Installation', 'Homeowner service package for tile flooring installation with clear options, starting price, and Smart Choice Contractors USA workflow.', 350, ['Removal'=>['Existing Floor Removal','No Removal'],'Furniture Moving'=>['Furniture Move Included','No'],'Stairs'=>['Yes','No'],'Baseboard Option'=>['Quarter Round','New Baseboards','No'],'Moisture Barrier'=>['Yes','No'],'Pattern'=>['Straight Lay','Diagonal Pattern','Herringbone']]);
        scp_product_193($CI, $catId, 'Engineered Hardwood Installation', 'Homeowner service package for engineered hardwood installation with clear options, starting price, and Smart Choice Contractors USA workflow.', 400, ['Removal'=>['Existing Floor Removal','No Removal'],'Furniture Moving'=>['Furniture Move Included','No'],'Stairs'=>['Yes','No'],'Baseboard Option'=>['Quarter Round','New Baseboards','No'],'Moisture Barrier'=>['Yes','No'],'Pattern'=>['Straight Lay','Diagonal Pattern','Herringbone']]);
        scp_product_193($CI, $catId, 'Floor Removal', 'Homeowner service package for floor removal with clear options, starting price, and Smart Choice Contractors USA workflow.', 450, ['Removal'=>['Existing Floor Removal','No Removal'],'Furniture Moving'=>['Furniture Move Included','No'],'Stairs'=>['Yes','No'],'Baseboard Option'=>['Quarter Round','New Baseboards','No'],'Moisture Barrier'=>['Yes','No'],'Pattern'=>['Straight Lay','Diagonal Pattern','Herringbone']]);
        scp_product_193($CI, $catId, 'Floor Leveling', 'Homeowner service package for floor leveling with clear options, starting price, and Smart Choice Contractors USA workflow.', 500, ['Removal'=>['Existing Floor Removal','No Removal'],'Furniture Moving'=>['Furniture Move Included','No'],'Stairs'=>['Yes','No'],'Baseboard Option'=>['Quarter Round','New Baseboards','No'],'Moisture Barrier'=>['Yes','No'],'Pattern'=>['Straight Lay','Diagonal Pattern','Herringbone']]);
        scp_product_193($CI, $catId, 'Baseboard Installation', 'Homeowner service package for baseboard installation with clear options, starting price, and Smart Choice Contractors USA workflow.', 550, ['Removal'=>['Existing Floor Removal','No Removal'],'Furniture Moving'=>['Furniture Move Included','No'],'Stairs'=>['Yes','No'],'Baseboard Option'=>['Quarter Round','New Baseboards','No'],'Moisture Barrier'=>['Yes','No'],'Pattern'=>['Straight Lay','Diagonal Pattern','Herringbone']]);
        scp_product_193($CI, $catId, 'Stair Tread Installation', 'Homeowner service package for stair tread installation with clear options, starting price, and Smart Choice Contractors USA workflow.', 600, ['Removal'=>['Existing Floor Removal','No Removal'],'Furniture Moving'=>['Furniture Move Included','No'],'Stairs'=>['Yes','No'],'Baseboard Option'=>['Quarter Round','New Baseboards','No'],'Moisture Barrier'=>['Yes','No'],'Pattern'=>['Straight Lay','Diagonal Pattern','Herringbone']]);
        scp_product_193($CI, $catId, 'Moisture Barrier Installation', 'Homeowner service package for moisture barrier installation with clear options, starting price, and Smart Choice Contractors USA workflow.', 650, ['Removal'=>['Existing Floor Removal','No Removal'],'Furniture Moving'=>['Furniture Move Included','No'],'Stairs'=>['Yes','No'],'Baseboard Option'=>['Quarter Round','New Baseboards','No'],'Moisture Barrier'=>['Yes','No'],'Pattern'=>['Straight Lay','Diagonal Pattern','Herringbone']]);
        scp_product_193($CI, $catId, 'Glue Down Vinyl Installation', 'Homeowner service package for glue down vinyl installation with clear options, starting price, and Smart Choice Contractors USA workflow.', 700, ['Removal'=>['Existing Floor Removal','No Removal'],'Furniture Moving'=>['Furniture Move Included','No'],'Stairs'=>['Yes','No'],'Baseboard Option'=>['Quarter Round','New Baseboards','No'],'Moisture Barrier'=>['Yes','No'],'Pattern'=>['Straight Lay','Diagonal Pattern','Herringbone']]);
        $catId = scp_get_category_193($CI, 'Doors');
        scp_product_193($CI, $catId, 'Interior Door Installation', 'Homeowner service package for interior door installation with clear options, starting price, and Smart Choice Contractors USA workflow.', 175, ['Door Width'=>['24 in','28 in','30 in','32 in','36 in'],'Door Height'=>['80 in','84 in','96 in'],'Door Type'=>['Hollow Core','Solid Core','Fire Rated'],'Floor Level'=>['First Floor','Second Floor','Third Floor'],'Old Door Removal'=>['Yes','No'],'Trim Option'=>['Existing Trim','New Trim'],'Paint Option'=>['Paint Door','Unpainted']]);
        scp_product_193($CI, $catId, 'Exterior Door Installation', 'Homeowner service package for exterior door installation with clear options, starting price, and Smart Choice Contractors USA workflow.', 225, ['Door Width'=>['24 in','28 in','30 in','32 in','36 in'],'Door Height'=>['80 in','84 in','96 in'],'Door Type'=>['Hollow Core','Solid Core','Fire Rated'],'Floor Level'=>['First Floor','Second Floor','Third Floor'],'Old Door Removal'=>['Yes','No'],'Trim Option'=>['Existing Trim','New Trim'],'Paint Option'=>['Paint Door','Unpainted']]);
        scp_product_193($CI, $catId, 'French Door Installation', 'Homeowner service package for french door installation with clear options, starting price, and Smart Choice Contractors USA workflow.', 275, ['Door Width'=>['24 in','28 in','30 in','32 in','36 in'],'Door Height'=>['80 in','84 in','96 in'],'Door Type'=>['Hollow Core','Solid Core','Fire Rated'],'Floor Level'=>['First Floor','Second Floor','Third Floor'],'Old Door Removal'=>['Yes','No'],'Trim Option'=>['Existing Trim','New Trim'],'Paint Option'=>['Paint Door','Unpainted']]);
        scp_product_193($CI, $catId, 'Sliding Door Installation', 'Homeowner service package for sliding door installation with clear options, starting price, and Smart Choice Contractors USA workflow.', 325, ['Door Width'=>['24 in','28 in','30 in','32 in','36 in'],'Door Height'=>['80 in','84 in','96 in'],'Door Type'=>['Hollow Core','Solid Core','Fire Rated'],'Floor Level'=>['First Floor','Second Floor','Third Floor'],'Old Door Removal'=>['Yes','No'],'Trim Option'=>['Existing Trim','New Trim'],'Paint Option'=>['Paint Door','Unpainted']]);
        scp_product_193($CI, $catId, 'Storm Door Installation', 'Homeowner service package for storm door installation with clear options, starting price, and Smart Choice Contractors USA workflow.', 375, ['Door Width'=>['24 in','28 in','30 in','32 in','36 in'],'Door Height'=>['80 in','84 in','96 in'],'Door Type'=>['Hollow Core','Solid Core','Fire Rated'],'Floor Level'=>['First Floor','Second Floor','Third Floor'],'Old Door Removal'=>['Yes','No'],'Trim Option'=>['Existing Trim','New Trim'],'Paint Option'=>['Paint Door','Unpainted']]);
        scp_product_193($CI, $catId, 'Door Trim Installation', 'Homeowner service package for door trim installation with clear options, starting price, and Smart Choice Contractors USA workflow.', 425, ['Door Width'=>['24 in','28 in','30 in','32 in','36 in'],'Door Height'=>['80 in','84 in','96 in'],'Door Type'=>['Hollow Core','Solid Core','Fire Rated'],'Floor Level'=>['First Floor','Second Floor','Third Floor'],'Old Door Removal'=>['Yes','No'],'Trim Option'=>['Existing Trim','New Trim'],'Paint Option'=>['Paint Door','Unpainted']]);
        scp_product_193($CI, $catId, 'Door Painting', 'Homeowner service package for door painting with clear options, starting price, and Smart Choice Contractors USA workflow.', 475, ['Door Width'=>['24 in','28 in','30 in','32 in','36 in'],'Door Height'=>['80 in','84 in','96 in'],'Door Type'=>['Hollow Core','Solid Core','Fire Rated'],'Floor Level'=>['First Floor','Second Floor','Third Floor'],'Old Door Removal'=>['Yes','No'],'Trim Option'=>['Existing Trim','New Trim'],'Paint Option'=>['Paint Door','Unpainted']]);
        scp_product_193($CI, $catId, 'Pocket Door Installation', 'Homeowner service package for pocket door installation with clear options, starting price, and Smart Choice Contractors USA workflow.', 525, ['Door Width'=>['24 in','28 in','30 in','32 in','36 in'],'Door Height'=>['80 in','84 in','96 in'],'Door Type'=>['Hollow Core','Solid Core','Fire Rated'],'Floor Level'=>['First Floor','Second Floor','Third Floor'],'Old Door Removal'=>['Yes','No'],'Trim Option'=>['Existing Trim','New Trim'],'Paint Option'=>['Paint Door','Unpainted']]);
        scp_product_193($CI, $catId, 'Barn Door Installation', 'Homeowner service package for barn door installation with clear options, starting price, and Smart Choice Contractors USA workflow.', 575, ['Door Width'=>['24 in','28 in','30 in','32 in','36 in'],'Door Height'=>['80 in','84 in','96 in'],'Door Type'=>['Hollow Core','Solid Core','Fire Rated'],'Floor Level'=>['First Floor','Second Floor','Third Floor'],'Old Door Removal'=>['Yes','No'],'Trim Option'=>['Existing Trim','New Trim'],'Paint Option'=>['Paint Door','Unpainted']]);
        scp_product_193($CI, $catId, 'Fire Rated Door Installation', 'Homeowner service package for fire rated door installation with clear options, starting price, and Smart Choice Contractors USA workflow.', 625, ['Door Width'=>['24 in','28 in','30 in','32 in','36 in'],'Door Height'=>['80 in','84 in','96 in'],'Door Type'=>['Hollow Core','Solid Core','Fire Rated'],'Floor Level'=>['First Floor','Second Floor','Third Floor'],'Old Door Removal'=>['Yes','No'],'Trim Option'=>['Existing Trim','New Trim'],'Paint Option'=>['Paint Door','Unpainted']]);
        scp_product_193($CI, $catId, 'Door Hardware Installation', 'Homeowner service package for door hardware installation with clear options, starting price, and Smart Choice Contractors USA workflow.', 675, ['Door Width'=>['24 in','28 in','30 in','32 in','36 in'],'Door Height'=>['80 in','84 in','96 in'],'Door Type'=>['Hollow Core','Solid Core','Fire Rated'],'Floor Level'=>['First Floor','Second Floor','Third Floor'],'Old Door Removal'=>['Yes','No'],'Trim Option'=>['Existing Trim','New Trim'],'Paint Option'=>['Paint Door','Unpainted']]);
        $catId = scp_get_category_193($CI, 'Windows');
        scp_product_193($CI, $catId, 'Window Installation', 'Homeowner service package for window installation with clear options, starting price, and Smart Choice Contractors USA workflow.', 250, ['Window Count'=>['1-10 Windows','11-20 Windows','21-30 Windows','31-40 Windows','40+ Windows'],'Window Type'=>['Single Hung','Double Hung','Slider','Impact'],'Window Size'=>['Small','Medium','Large'],'Old Window Disposal'=>['Haul Away Old Window','Leave On Site'],'Cleaning Scope'=>['Inside Only','Outside Only','Inside and Outside'],'Screen Cleaning'=>['Screens Included','No'],'Track Cleaning'=>['Tracks Included','No'],'Hard Water Removal'=>['Hard Water Treatment','No'],'Floor Level'=>['First Floor','Second Floor','Third Floor']]);
        scp_product_193($CI, $catId, 'Window Replacement', 'Homeowner service package for window replacement with clear options, starting price, and Smart Choice Contractors USA workflow.', 300, ['Window Count'=>['1-10 Windows','11-20 Windows','21-30 Windows','31-40 Windows','40+ Windows'],'Window Type'=>['Single Hung','Double Hung','Slider','Impact'],'Window Size'=>['Small','Medium','Large'],'Old Window Disposal'=>['Haul Away Old Window','Leave On Site'],'Cleaning Scope'=>['Inside Only','Outside Only','Inside and Outside'],'Screen Cleaning'=>['Screens Included','No'],'Track Cleaning'=>['Tracks Included','No'],'Hard Water Removal'=>['Hard Water Treatment','No'],'Floor Level'=>['First Floor','Second Floor','Third Floor']]);
        scp_product_193($CI, $catId, 'Impact Window Upgrade', 'Homeowner service package for impact window upgrade with clear options, starting price, and Smart Choice Contractors USA workflow.', 350, ['Window Count'=>['1-10 Windows','11-20 Windows','21-30 Windows','31-40 Windows','40+ Windows'],'Window Type'=>['Single Hung','Double Hung','Slider','Impact'],'Window Size'=>['Small','Medium','Large'],'Old Window Disposal'=>['Haul Away Old Window','Leave On Site'],'Cleaning Scope'=>['Inside Only','Outside Only','Inside and Outside'],'Screen Cleaning'=>['Screens Included','No'],'Track Cleaning'=>['Tracks Included','No'],'Hard Water Removal'=>['Hard Water Treatment','No'],'Floor Level'=>['First Floor','Second Floor','Third Floor']]);
        scp_product_193($CI, $catId, 'Window Cleaning', 'Homeowner service package for window cleaning with clear options, starting price, and Smart Choice Contractors USA workflow.', 400, ['Window Count'=>['1-10 Windows','11-20 Windows','21-30 Windows','31-40 Windows','40+ Windows'],'Window Type'=>['Single Hung','Double Hung','Slider','Impact'],'Window Size'=>['Small','Medium','Large'],'Old Window Disposal'=>['Haul Away Old Window','Leave On Site'],'Cleaning Scope'=>['Inside Only','Outside Only','Inside and Outside'],'Screen Cleaning'=>['Screens Included','No'],'Track Cleaning'=>['Tracks Included','No'],'Hard Water Removal'=>['Hard Water Treatment','No'],'Floor Level'=>['First Floor','Second Floor','Third Floor']]);
        scp_product_193($CI, $catId, 'Window Trim Repair', 'Homeowner service package for window trim repair with clear options, starting price, and Smart Choice Contractors USA workflow.', 450, ['Window Count'=>['1-10 Windows','11-20 Windows','21-30 Windows','31-40 Windows','40+ Windows'],'Window Type'=>['Single Hung','Double Hung','Slider','Impact'],'Window Size'=>['Small','Medium','Large'],'Old Window Disposal'=>['Haul Away Old Window','Leave On Site'],'Cleaning Scope'=>['Inside Only','Outside Only','Inside and Outside'],'Screen Cleaning'=>['Screens Included','No'],'Track Cleaning'=>['Tracks Included','No'],'Hard Water Removal'=>['Hard Water Treatment','No'],'Floor Level'=>['First Floor','Second Floor','Third Floor']]);
        scp_product_193($CI, $catId, 'Window Screen Replacement', 'Homeowner service package for window screen replacement with clear options, starting price, and Smart Choice Contractors USA workflow.', 500, ['Window Count'=>['1-10 Windows','11-20 Windows','21-30 Windows','31-40 Windows','40+ Windows'],'Window Type'=>['Single Hung','Double Hung','Slider','Impact'],'Window Size'=>['Small','Medium','Large'],'Old Window Disposal'=>['Haul Away Old Window','Leave On Site'],'Cleaning Scope'=>['Inside Only','Outside Only','Inside and Outside'],'Screen Cleaning'=>['Screens Included','No'],'Track Cleaning'=>['Tracks Included','No'],'Hard Water Removal'=>['Hard Water Treatment','No'],'Floor Level'=>['First Floor','Second Floor','Third Floor']]);
        scp_product_193($CI, $catId, 'Window Caulking', 'Homeowner service package for window caulking with clear options, starting price, and Smart Choice Contractors USA workflow.', 550, ['Window Count'=>['1-10 Windows','11-20 Windows','21-30 Windows','31-40 Windows','40+ Windows'],'Window Type'=>['Single Hung','Double Hung','Slider','Impact'],'Window Size'=>['Small','Medium','Large'],'Old Window Disposal'=>['Haul Away Old Window','Leave On Site'],'Cleaning Scope'=>['Inside Only','Outside Only','Inside and Outside'],'Screen Cleaning'=>['Screens Included','No'],'Track Cleaning'=>['Tracks Included','No'],'Hard Water Removal'=>['Hard Water Treatment','No'],'Floor Level'=>['First Floor','Second Floor','Third Floor']]);
        scp_product_193($CI, $catId, 'Window Disposal Service', 'Homeowner service package for window disposal service with clear options, starting price, and Smart Choice Contractors USA workflow.', 600, ['Window Count'=>['1-10 Windows','11-20 Windows','21-30 Windows','31-40 Windows','40+ Windows'],'Window Type'=>['Single Hung','Double Hung','Slider','Impact'],'Window Size'=>['Small','Medium','Large'],'Old Window Disposal'=>['Haul Away Old Window','Leave On Site'],'Cleaning Scope'=>['Inside Only','Outside Only','Inside and Outside'],'Screen Cleaning'=>['Screens Included','No'],'Track Cleaning'=>['Tracks Included','No'],'Hard Water Removal'=>['Hard Water Treatment','No'],'Floor Level'=>['First Floor','Second Floor','Third Floor']]);
        scp_product_193($CI, $catId, 'Second Floor Window Installation', 'Homeowner service package for second floor window installation with clear options, starting price, and Smart Choice Contractors USA workflow.', 650, ['Window Count'=>['1-10 Windows','11-20 Windows','21-30 Windows','31-40 Windows','40+ Windows'],'Window Type'=>['Single Hung','Double Hung','Slider','Impact'],'Window Size'=>['Small','Medium','Large'],'Old Window Disposal'=>['Haul Away Old Window','Leave On Site'],'Cleaning Scope'=>['Inside Only','Outside Only','Inside and Outside'],'Screen Cleaning'=>['Screens Included','No'],'Track Cleaning'=>['Tracks Included','No'],'Hard Water Removal'=>['Hard Water Treatment','No'],'Floor Level'=>['First Floor','Second Floor','Third Floor']]);
        scp_product_193($CI, $catId, 'Window Permit Assistance', 'Homeowner service package for window permit assistance with clear options, starting price, and Smart Choice Contractors USA workflow.', 700, ['Window Count'=>['1-10 Windows','11-20 Windows','21-30 Windows','31-40 Windows','40+ Windows'],'Window Type'=>['Single Hung','Double Hung','Slider','Impact'],'Window Size'=>['Small','Medium','Large'],'Old Window Disposal'=>['Haul Away Old Window','Leave On Site'],'Cleaning Scope'=>['Inside Only','Outside Only','Inside and Outside'],'Screen Cleaning'=>['Screens Included','No'],'Track Cleaning'=>['Tracks Included','No'],'Hard Water Removal'=>['Hard Water Treatment','No'],'Floor Level'=>['First Floor','Second Floor','Third Floor']]);
        $catId = scp_get_category_193($CI, 'Bathrooms');
        scp_product_193($CI, $catId, 'Bathroom Remodel Starter', 'Homeowner service package for bathroom remodel starter with clear options, starting price, and Smart Choice Contractors USA workflow.', 450, ['Project Type'=>['Residential','Commercial'],'Removal'=>['Existing Floor Removal','No Removal'],'Permit Required'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Shower Tile Installation', 'Homeowner service package for shower tile installation with clear options, starting price, and Smart Choice Contractors USA workflow.', 500, ['Project Type'=>['Residential','Commercial'],'Removal'=>['Existing Floor Removal','No Removal'],'Permit Required'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Vanity Installation', 'Homeowner service package for vanity installation with clear options, starting price, and Smart Choice Contractors USA workflow.', 550, ['Project Type'=>['Residential','Commercial'],'Removal'=>['Existing Floor Removal','No Removal'],'Permit Required'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Toilet Installation', 'Homeowner service package for toilet installation with clear options, starting price, and Smart Choice Contractors USA workflow.', 600, ['Project Type'=>['Residential','Commercial'],'Removal'=>['Existing Floor Removal','No Removal'],'Permit Required'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Shower Glass Installation', 'Homeowner service package for shower glass installation with clear options, starting price, and Smart Choice Contractors USA workflow.', 650, ['Project Type'=>['Residential','Commercial'],'Removal'=>['Existing Floor Removal','No Removal'],'Permit Required'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Bathroom Floor Tile', 'Homeowner service package for bathroom floor tile with clear options, starting price, and Smart Choice Contractors USA workflow.', 700, ['Project Type'=>['Residential','Commercial'],'Removal'=>['Existing Floor Removal','No Removal'],'Permit Required'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Bathroom Exhaust Fan', 'Homeowner service package for bathroom exhaust fan with clear options, starting price, and Smart Choice Contractors USA workflow.', 750, ['Project Type'=>['Residential','Commercial'],'Removal'=>['Existing Floor Removal','No Removal'],'Permit Required'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Tub to Shower Conversion', 'Homeowner service package for tub to shower conversion with clear options, starting price, and Smart Choice Contractors USA workflow.', 800, ['Project Type'=>['Residential','Commercial'],'Removal'=>['Existing Floor Removal','No Removal'],'Permit Required'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Bathroom Demolition', 'Homeowner service package for bathroom demolition with clear options, starting price, and Smart Choice Contractors USA workflow.', 850, ['Project Type'=>['Residential','Commercial'],'Removal'=>['Existing Floor Removal','No Removal'],'Permit Required'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Waterproofing System', 'Homeowner service package for waterproofing system with clear options, starting price, and Smart Choice Contractors USA workflow.', 900, ['Project Type'=>['Residential','Commercial'],'Removal'=>['Existing Floor Removal','No Removal'],'Permit Required'=>['Yes','No']]);
        $catId = scp_get_category_193($CI, 'Kitchen');
        scp_product_193($CI, $catId, 'Kitchen Cabinet Installation', 'Homeowner service package for kitchen cabinet installation with clear options, starting price, and Smart Choice Contractors USA workflow.', 350, ['Project Type'=>['Residential','Commercial'],'Removal'=>['Yes','No'],'Permit Required'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Countertop Installation', 'Homeowner service package for countertop installation with clear options, starting price, and Smart Choice Contractors USA workflow.', 400, ['Project Type'=>['Residential','Commercial'],'Removal'=>['Yes','No'],'Permit Required'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Backsplash Installation', 'Homeowner service package for backsplash installation with clear options, starting price, and Smart Choice Contractors USA workflow.', 450, ['Project Type'=>['Residential','Commercial'],'Removal'=>['Yes','No'],'Permit Required'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Kitchen Sink Installation', 'Homeowner service package for kitchen sink installation with clear options, starting price, and Smart Choice Contractors USA workflow.', 500, ['Project Type'=>['Residential','Commercial'],'Removal'=>['Yes','No'],'Permit Required'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Garbage Disposal Installation', 'Homeowner service package for garbage disposal installation with clear options, starting price, and Smart Choice Contractors USA workflow.', 550, ['Project Type'=>['Residential','Commercial'],'Removal'=>['Yes','No'],'Permit Required'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Kitchen Faucet Installation', 'Homeowner service package for kitchen faucet installation with clear options, starting price, and Smart Choice Contractors USA workflow.', 600, ['Project Type'=>['Residential','Commercial'],'Removal'=>['Yes','No'],'Permit Required'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Cabinet Hardware Installation', 'Homeowner service package for cabinet hardware installation with clear options, starting price, and Smart Choice Contractors USA workflow.', 650, ['Project Type'=>['Residential','Commercial'],'Removal'=>['Yes','No'],'Permit Required'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Pantry Shelving', 'Homeowner service package for pantry shelving with clear options, starting price, and Smart Choice Contractors USA workflow.', 700, ['Project Type'=>['Residential','Commercial'],'Removal'=>['Yes','No'],'Permit Required'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Kitchen Lighting', 'Homeowner service package for kitchen lighting with clear options, starting price, and Smart Choice Contractors USA workflow.', 750, ['Project Type'=>['Residential','Commercial'],'Removal'=>['Yes','No'],'Permit Required'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Cabinet Removal', 'Homeowner service package for cabinet removal with clear options, starting price, and Smart Choice Contractors USA workflow.', 800, ['Project Type'=>['Residential','Commercial'],'Removal'=>['Yes','No'],'Permit Required'=>['Yes','No']]);
        $catId = scp_get_category_193($CI, 'Painting');
        scp_product_193($CI, $catId, 'Interior Painting', 'Homeowner service package for interior painting with clear options, starting price, and Smart Choice Contractors USA workflow.', 275, ['Painting Scope'=>['Interior','Exterior'],'Area'=>['Walls','Ceilings','Trim and Doors'],'Texture Repair'=>['Minor Texture Repair','No'],'Primer'=>['Yes','No'],'Paint Grade'=>['Standard','Premium Paint']]);
        scp_product_193($CI, $catId, 'Exterior Painting', 'Homeowner service package for exterior painting with clear options, starting price, and Smart Choice Contractors USA workflow.', 325, ['Painting Scope'=>['Interior','Exterior'],'Area'=>['Walls','Ceilings','Trim and Doors'],'Texture Repair'=>['Minor Texture Repair','No'],'Primer'=>['Yes','No'],'Paint Grade'=>['Standard','Premium Paint']]);
        scp_product_193($CI, $catId, 'Trim Painting', 'Homeowner service package for trim painting with clear options, starting price, and Smart Choice Contractors USA workflow.', 375, ['Painting Scope'=>['Interior','Exterior'],'Area'=>['Walls','Ceilings','Trim and Doors'],'Texture Repair'=>['Minor Texture Repair','No'],'Primer'=>['Yes','No'],'Paint Grade'=>['Standard','Premium Paint']]);
        scp_product_193($CI, $catId, 'Ceiling Painting', 'Homeowner service package for ceiling painting with clear options, starting price, and Smart Choice Contractors USA workflow.', 425, ['Painting Scope'=>['Interior','Exterior'],'Area'=>['Walls','Ceilings','Trim and Doors'],'Texture Repair'=>['Minor Texture Repair','No'],'Primer'=>['Yes','No'],'Paint Grade'=>['Standard','Premium Paint']]);
        scp_product_193($CI, $catId, 'Door Painting Package', 'Homeowner service package for door painting package with clear options, starting price, and Smart Choice Contractors USA workflow.', 475, ['Painting Scope'=>['Interior','Exterior'],'Area'=>['Walls','Ceilings','Trim and Doors'],'Texture Repair'=>['Minor Texture Repair','No'],'Primer'=>['Yes','No'],'Paint Grade'=>['Standard','Premium Paint']]);
        scp_product_193($CI, $catId, 'Drywall Texture Repair', 'Homeowner service package for drywall texture repair with clear options, starting price, and Smart Choice Contractors USA workflow.', 525, ['Painting Scope'=>['Interior','Exterior'],'Area'=>['Walls','Ceilings','Trim and Doors'],'Texture Repair'=>['Minor Texture Repair','No'],'Primer'=>['Yes','No'],'Paint Grade'=>['Standard','Premium Paint']]);
        scp_product_193($CI, $catId, 'Primer Application', 'Homeowner service package for primer application with clear options, starting price, and Smart Choice Contractors USA workflow.', 575, ['Painting Scope'=>['Interior','Exterior'],'Area'=>['Walls','Ceilings','Trim and Doors'],'Texture Repair'=>['Minor Texture Repair','No'],'Primer'=>['Yes','No'],'Paint Grade'=>['Standard','Premium Paint']]);
        scp_product_193($CI, $catId, 'Accent Wall Painting', 'Homeowner service package for accent wall painting with clear options, starting price, and Smart Choice Contractors USA workflow.', 625, ['Painting Scope'=>['Interior','Exterior'],'Area'=>['Walls','Ceilings','Trim and Doors'],'Texture Repair'=>['Minor Texture Repair','No'],'Primer'=>['Yes','No'],'Paint Grade'=>['Standard','Premium Paint']]);
        scp_product_193($CI, $catId, 'Cabinet Painting', 'Homeowner service package for cabinet painting with clear options, starting price, and Smart Choice Contractors USA workflow.', 675, ['Painting Scope'=>['Interior','Exterior'],'Area'=>['Walls','Ceilings','Trim and Doors'],'Texture Repair'=>['Minor Texture Repair','No'],'Primer'=>['Yes','No'],'Paint Grade'=>['Standard','Premium Paint']]);
        scp_product_193($CI, $catId, 'Pressure Washing Before Paint', 'Homeowner service package for pressure washing before paint with clear options, starting price, and Smart Choice Contractors USA workflow.', 725, ['Painting Scope'=>['Interior','Exterior'],'Area'=>['Walls','Ceilings','Trim and Doors'],'Texture Repair'=>['Minor Texture Repair','No'],'Primer'=>['Yes','No'],'Paint Grade'=>['Standard','Premium Paint']]);
        $catId = scp_get_category_193($CI, 'Drywall');
        scp_product_193($CI, $catId, 'Drywall Patch Repair', 'Homeowner service package for drywall patch repair with clear options, starting price, and Smart Choice Contractors USA workflow.', 225, ['Area'=>['Walls','Ceilings'],'Texture Repair'=>['Minor Texture Repair','No'],'Primer'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Drywall Hanging', 'Homeowner service package for drywall hanging with clear options, starting price, and Smart Choice Contractors USA workflow.', 275, ['Area'=>['Walls','Ceilings'],'Texture Repair'=>['Minor Texture Repair','No'],'Primer'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Drywall Finishing', 'Homeowner service package for drywall finishing with clear options, starting price, and Smart Choice Contractors USA workflow.', 325, ['Area'=>['Walls','Ceilings'],'Texture Repair'=>['Minor Texture Repair','No'],'Primer'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Texture Matching', 'Homeowner service package for texture matching with clear options, starting price, and Smart Choice Contractors USA workflow.', 375, ['Area'=>['Walls','Ceilings'],'Texture Repair'=>['Minor Texture Repair','No'],'Primer'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Ceiling Drywall Repair', 'Homeowner service package for ceiling drywall repair with clear options, starting price, and Smart Choice Contractors USA workflow.', 425, ['Area'=>['Walls','Ceilings'],'Texture Repair'=>['Minor Texture Repair','No'],'Primer'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Garage Drywall', 'Homeowner service package for garage drywall with clear options, starting price, and Smart Choice Contractors USA workflow.', 475, ['Area'=>['Walls','Ceilings'],'Texture Repair'=>['Minor Texture Repair','No'],'Primer'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Water Damage Drywall Repair', 'Homeowner service package for water damage drywall repair with clear options, starting price, and Smart Choice Contractors USA workflow.', 525, ['Area'=>['Walls','Ceilings'],'Texture Repair'=>['Minor Texture Repair','No'],'Primer'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Corner Bead Repair', 'Homeowner service package for corner bead repair with clear options, starting price, and Smart Choice Contractors USA workflow.', 575, ['Area'=>['Walls','Ceilings'],'Texture Repair'=>['Minor Texture Repair','No'],'Primer'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Drywall Sanding', 'Homeowner service package for drywall sanding with clear options, starting price, and Smart Choice Contractors USA workflow.', 625, ['Area'=>['Walls','Ceilings'],'Texture Repair'=>['Minor Texture Repair','No'],'Primer'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Drywall Prime Ready Finish', 'Homeowner service package for drywall prime ready finish with clear options, starting price, and Smart Choice Contractors USA workflow.', 675, ['Area'=>['Walls','Ceilings'],'Texture Repair'=>['Minor Texture Repair','No'],'Primer'=>['Yes','No']]);
        $catId = scp_get_category_193($CI, 'Electrical');
        scp_product_193($CI, $catId, 'Panel Upgrade', 'Homeowner service package for panel upgrade with clear options, starting price, and Smart Choice Contractors USA workflow.', 175, ['Electrical Service'=>['Panel Upgrade','New Circuit','EV Charger','Ceiling Fan','Outlet or Switch'],'Permit Required'=>['Yes','No'],'Story Level'=>['One Story','Two Story']]);
        scp_product_193($CI, $catId, 'EV Charger Installation', 'Homeowner service package for ev charger installation with clear options, starting price, and Smart Choice Contractors USA workflow.', 225, ['Electrical Service'=>['Panel Upgrade','New Circuit','EV Charger','Ceiling Fan','Outlet or Switch'],'Permit Required'=>['Yes','No'],'Story Level'=>['One Story','Two Story']]);
        scp_product_193($CI, $catId, 'Ceiling Fan Installation', 'Homeowner service package for ceiling fan installation with clear options, starting price, and Smart Choice Contractors USA workflow.', 275, ['Electrical Service'=>['Panel Upgrade','New Circuit','EV Charger','Ceiling Fan','Outlet or Switch'],'Permit Required'=>['Yes','No'],'Story Level'=>['One Story','Two Story']]);
        scp_product_193($CI, $catId, 'Light Fixture Installation', 'Homeowner service package for light fixture installation with clear options, starting price, and Smart Choice Contractors USA workflow.', 325, ['Electrical Service'=>['Panel Upgrade','New Circuit','EV Charger','Ceiling Fan','Outlet or Switch'],'Permit Required'=>['Yes','No'],'Story Level'=>['One Story','Two Story']]);
        scp_product_193($CI, $catId, 'Outlet Installation', 'Homeowner service package for outlet installation with clear options, starting price, and Smart Choice Contractors USA workflow.', 375, ['Electrical Service'=>['Panel Upgrade','New Circuit','EV Charger','Ceiling Fan','Outlet or Switch'],'Permit Required'=>['Yes','No'],'Story Level'=>['One Story','Two Story']]);
        scp_product_193($CI, $catId, 'Switch Replacement', 'Homeowner service package for switch replacement with clear options, starting price, and Smart Choice Contractors USA workflow.', 425, ['Electrical Service'=>['Panel Upgrade','New Circuit','EV Charger','Ceiling Fan','Outlet or Switch'],'Permit Required'=>['Yes','No'],'Story Level'=>['One Story','Two Story']]);
        scp_product_193($CI, $catId, 'Dedicated Circuit', 'Homeowner service package for dedicated circuit with clear options, starting price, and Smart Choice Contractors USA workflow.', 475, ['Electrical Service'=>['Panel Upgrade','New Circuit','EV Charger','Ceiling Fan','Outlet or Switch'],'Permit Required'=>['Yes','No'],'Story Level'=>['One Story','Two Story']]);
        scp_product_193($CI, $catId, 'Generator Inlet', 'Homeowner service package for generator inlet with clear options, starting price, and Smart Choice Contractors USA workflow.', 525, ['Electrical Service'=>['Panel Upgrade','New Circuit','EV Charger','Ceiling Fan','Outlet or Switch'],'Permit Required'=>['Yes','No'],'Story Level'=>['One Story','Two Story']]);
        scp_product_193($CI, $catId, 'Smoke Detector Installation', 'Homeowner service package for smoke detector installation with clear options, starting price, and Smart Choice Contractors USA workflow.', 575, ['Electrical Service'=>['Panel Upgrade','New Circuit','EV Charger','Ceiling Fan','Outlet or Switch'],'Permit Required'=>['Yes','No'],'Story Level'=>['One Story','Two Story']]);
        scp_product_193($CI, $catId, 'Electrical Troubleshooting', 'Homeowner service package for electrical troubleshooting with clear options, starting price, and Smart Choice Contractors USA workflow.', 625, ['Electrical Service'=>['Panel Upgrade','New Circuit','EV Charger','Ceiling Fan','Outlet or Switch'],'Permit Required'=>['Yes','No'],'Story Level'=>['One Story','Two Story']]);
        $catId = scp_get_category_193($CI, 'Plumbing');
        scp_product_193($CI, $catId, 'Water Heater Installation', 'Homeowner service package for water heater installation with clear options, starting price, and Smart Choice Contractors USA workflow.', 150, ['Plumbing Service'=>['Toilet','Sink','Garbage Disposal','Leak Repair'],'Water Heater Type'=>['Tank Water Heater','Tankless Water Heater'],'Inspection Option'=>['Camera Inspection','No'],'Story Level'=>['One Story','Two Story']]);
        scp_product_193($CI, $catId, 'Tankless Water Heater', 'Homeowner service package for tankless water heater with clear options, starting price, and Smart Choice Contractors USA workflow.', 200, ['Plumbing Service'=>['Toilet','Sink','Garbage Disposal','Leak Repair'],'Water Heater Type'=>['Tank Water Heater','Tankless Water Heater'],'Inspection Option'=>['Camera Inspection','No'],'Story Level'=>['One Story','Two Story']]);
        scp_product_193($CI, $catId, 'Toilet Replacement', 'Homeowner service package for toilet replacement with clear options, starting price, and Smart Choice Contractors USA workflow.', 250, ['Plumbing Service'=>['Toilet','Sink','Garbage Disposal','Leak Repair'],'Water Heater Type'=>['Tank Water Heater','Tankless Water Heater'],'Inspection Option'=>['Camera Inspection','No'],'Story Level'=>['One Story','Two Story']]);
        scp_product_193($CI, $catId, 'Sink Installation', 'Homeowner service package for sink installation with clear options, starting price, and Smart Choice Contractors USA workflow.', 300, ['Plumbing Service'=>['Toilet','Sink','Garbage Disposal','Leak Repair'],'Water Heater Type'=>['Tank Water Heater','Tankless Water Heater'],'Inspection Option'=>['Camera Inspection','No'],'Story Level'=>['One Story','Two Story']]);
        scp_product_193($CI, $catId, 'Leak Repair', 'Homeowner service package for leak repair with clear options, starting price, and Smart Choice Contractors USA workflow.', 350, ['Plumbing Service'=>['Toilet','Sink','Garbage Disposal','Leak Repair'],'Water Heater Type'=>['Tank Water Heater','Tankless Water Heater'],'Inspection Option'=>['Camera Inspection','No'],'Story Level'=>['One Story','Two Story']]);
        scp_product_193($CI, $catId, 'Garbage Disposal Replacement', 'Homeowner service package for garbage disposal replacement with clear options, starting price, and Smart Choice Contractors USA workflow.', 400, ['Plumbing Service'=>['Toilet','Sink','Garbage Disposal','Leak Repair'],'Water Heater Type'=>['Tank Water Heater','Tankless Water Heater'],'Inspection Option'=>['Camera Inspection','No'],'Story Level'=>['One Story','Two Story']]);
        scp_product_193($CI, $catId, 'Shower Valve Replacement', 'Homeowner service package for shower valve replacement with clear options, starting price, and Smart Choice Contractors USA workflow.', 450, ['Plumbing Service'=>['Toilet','Sink','Garbage Disposal','Leak Repair'],'Water Heater Type'=>['Tank Water Heater','Tankless Water Heater'],'Inspection Option'=>['Camera Inspection','No'],'Story Level'=>['One Story','Two Story']]);
        scp_product_193($CI, $catId, 'Faucet Installation', 'Homeowner service package for faucet installation with clear options, starting price, and Smart Choice Contractors USA workflow.', 500, ['Plumbing Service'=>['Toilet','Sink','Garbage Disposal','Leak Repair'],'Water Heater Type'=>['Tank Water Heater','Tankless Water Heater'],'Inspection Option'=>['Camera Inspection','No'],'Story Level'=>['One Story','Two Story']]);
        scp_product_193($CI, $catId, 'Drain Cleaning', 'Homeowner service package for drain cleaning with clear options, starting price, and Smart Choice Contractors USA workflow.', 550, ['Plumbing Service'=>['Toilet','Sink','Garbage Disposal','Leak Repair'],'Water Heater Type'=>['Tank Water Heater','Tankless Water Heater'],'Inspection Option'=>['Camera Inspection','No'],'Story Level'=>['One Story','Two Story']]);
        scp_product_193($CI, $catId, 'Plumbing Camera Inspection', 'Homeowner service package for plumbing camera inspection with clear options, starting price, and Smart Choice Contractors USA workflow.', 600, ['Plumbing Service'=>['Toilet','Sink','Garbage Disposal','Leak Repair'],'Water Heater Type'=>['Tank Water Heater','Tankless Water Heater'],'Inspection Option'=>['Camera Inspection','No'],'Story Level'=>['One Story','Two Story']]);
        $catId = scp_get_category_193($CI, 'HVAC');
        scp_product_193($CI, $catId, 'Mini Split Installation', 'Homeowner service package for mini split installation with clear options, starting price, and Smart Choice Contractors USA workflow.', 275, ['Project Type'=>['Residential','Commercial'],'Story Level'=>['One Story','Two Story'],'Permit Required'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Thermostat Installation', 'Homeowner service package for thermostat installation with clear options, starting price, and Smart Choice Contractors USA workflow.', 325, ['Project Type'=>['Residential','Commercial'],'Story Level'=>['One Story','Two Story'],'Permit Required'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Duct Repair', 'Homeowner service package for duct repair with clear options, starting price, and Smart Choice Contractors USA workflow.', 375, ['Project Type'=>['Residential','Commercial'],'Story Level'=>['One Story','Two Story'],'Permit Required'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Air Handler Platform', 'Homeowner service package for air handler platform with clear options, starting price, and Smart Choice Contractors USA workflow.', 425, ['Project Type'=>['Residential','Commercial'],'Story Level'=>['One Story','Two Story'],'Permit Required'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Return Air Upgrade', 'Homeowner service package for return air upgrade with clear options, starting price, and Smart Choice Contractors USA workflow.', 475, ['Project Type'=>['Residential','Commercial'],'Story Level'=>['One Story','Two Story'],'Permit Required'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Supply Vent Installation', 'Homeowner service package for supply vent installation with clear options, starting price, and Smart Choice Contractors USA workflow.', 525, ['Project Type'=>['Residential','Commercial'],'Story Level'=>['One Story','Two Story'],'Permit Required'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Dryer Vent Cleaning', 'Homeowner service package for dryer vent cleaning with clear options, starting price, and Smart Choice Contractors USA workflow.', 575, ['Project Type'=>['Residential','Commercial'],'Story Level'=>['One Story','Two Story'],'Permit Required'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'HVAC Maintenance Visit', 'Homeowner service package for hvac maintenance visit with clear options, starting price, and Smart Choice Contractors USA workflow.', 625, ['Project Type'=>['Residential','Commercial'],'Story Level'=>['One Story','Two Story'],'Permit Required'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Condensate Line Flush', 'Homeowner service package for condensate line flush with clear options, starting price, and Smart Choice Contractors USA workflow.', 675, ['Project Type'=>['Residential','Commercial'],'Story Level'=>['One Story','Two Story'],'Permit Required'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Attic Duct Insulation', 'Homeowner service package for attic duct insulation with clear options, starting price, and Smart Choice Contractors USA workflow.', 725, ['Project Type'=>['Residential','Commercial'],'Story Level'=>['One Story','Two Story'],'Permit Required'=>['Yes','No']]);
        $catId = scp_get_category_193($CI, 'Roofing');
        scp_product_193($CI, $catId, 'Shingle Roof Repair', 'Homeowner service package for shingle roof repair with clear options, starting price, and Smart Choice Contractors USA workflow.', 350, ['Roof Type'=>['Shingle','Metal','Flat Roof'],'Tear Off'=>['Yes','No'],'Dumpster'=>['Yes','No'],'Story Level'=>['One Story','Two Story'],'Permit Required'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Flat Roof Repair', 'Homeowner service package for flat roof repair with clear options, starting price, and Smart Choice Contractors USA workflow.', 400, ['Roof Type'=>['Shingle','Metal','Flat Roof'],'Tear Off'=>['Yes','No'],'Dumpster'=>['Yes','No'],'Story Level'=>['One Story','Two Story'],'Permit Required'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Roof Inspection', 'Homeowner service package for roof inspection with clear options, starting price, and Smart Choice Contractors USA workflow.', 450, ['Roof Type'=>['Shingle','Metal','Flat Roof'],'Tear Off'=>['Yes','No'],'Dumpster'=>['Yes','No'],'Story Level'=>['One Story','Two Story'],'Permit Required'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Roof Tear Off', 'Homeowner service package for roof tear off with clear options, starting price, and Smart Choice Contractors USA workflow.', 500, ['Roof Type'=>['Shingle','Metal','Flat Roof'],'Tear Off'=>['Yes','No'],'Dumpster'=>['Yes','No'],'Story Level'=>['One Story','Two Story'],'Permit Required'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Fascia Repair', 'Homeowner service package for fascia repair with clear options, starting price, and Smart Choice Contractors USA workflow.', 550, ['Roof Type'=>['Shingle','Metal','Flat Roof'],'Tear Off'=>['Yes','No'],'Dumpster'=>['Yes','No'],'Story Level'=>['One Story','Two Story'],'Permit Required'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Soffit Installation', 'Homeowner service package for soffit installation with clear options, starting price, and Smart Choice Contractors USA workflow.', 600, ['Roof Type'=>['Shingle','Metal','Flat Roof'],'Tear Off'=>['Yes','No'],'Dumpster'=>['Yes','No'],'Story Level'=>['One Story','Two Story'],'Permit Required'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Roof Vent Installation', 'Homeowner service package for roof vent installation with clear options, starting price, and Smart Choice Contractors USA workflow.', 650, ['Roof Type'=>['Shingle','Metal','Flat Roof'],'Tear Off'=>['Yes','No'],'Dumpster'=>['Yes','No'],'Story Level'=>['One Story','Two Story'],'Permit Required'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Metal Roof Repair', 'Homeowner service package for metal roof repair with clear options, starting price, and Smart Choice Contractors USA workflow.', 700, ['Roof Type'=>['Shingle','Metal','Flat Roof'],'Tear Off'=>['Yes','No'],'Dumpster'=>['Yes','No'],'Story Level'=>['One Story','Two Story'],'Permit Required'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Roof Permit Assistance', 'Homeowner service package for roof permit assistance with clear options, starting price, and Smart Choice Contractors USA workflow.', 750, ['Roof Type'=>['Shingle','Metal','Flat Roof'],'Tear Off'=>['Yes','No'],'Dumpster'=>['Yes','No'],'Story Level'=>['One Story','Two Story'],'Permit Required'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Gutter Installation', 'Homeowner service package for gutter installation with clear options, starting price, and Smart Choice Contractors USA workflow.', 800, ['Roof Type'=>['Shingle','Metal','Flat Roof'],'Tear Off'=>['Yes','No'],'Dumpster'=>['Yes','No'],'Story Level'=>['One Story','Two Story'],'Permit Required'=>['Yes','No']]);
        $catId = scp_get_category_193($CI, 'Concrete');
        scp_product_193($CI, $catId, 'Concrete Slab', 'Homeowner service package for concrete slab with clear options, starting price, and Smart Choice Contractors USA workflow.', 400, ['Project Type'=>['Residential','Commercial'],'Permit Required'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Driveway Concrete', 'Homeowner service package for driveway concrete with clear options, starting price, and Smart Choice Contractors USA workflow.', 450, ['Project Type'=>['Residential','Commercial'],'Permit Required'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Sidewalk Concrete', 'Homeowner service package for sidewalk concrete with clear options, starting price, and Smart Choice Contractors USA workflow.', 500, ['Project Type'=>['Residential','Commercial'],'Permit Required'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Concrete Demo', 'Homeowner service package for concrete demo with clear options, starting price, and Smart Choice Contractors USA workflow.', 550, ['Project Type'=>['Residential','Commercial'],'Permit Required'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Concrete Patch', 'Homeowner service package for concrete patch with clear options, starting price, and Smart Choice Contractors USA workflow.', 600, ['Project Type'=>['Residential','Commercial'],'Permit Required'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Footer Pour', 'Homeowner service package for footer pour with clear options, starting price, and Smart Choice Contractors USA workflow.', 650, ['Project Type'=>['Residential','Commercial'],'Permit Required'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Concrete Steps', 'Homeowner service package for concrete steps with clear options, starting price, and Smart Choice Contractors USA workflow.', 700, ['Project Type'=>['Residential','Commercial'],'Permit Required'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Paver Removal', 'Homeowner service package for paver removal with clear options, starting price, and Smart Choice Contractors USA workflow.', 750, ['Project Type'=>['Residential','Commercial'],'Permit Required'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Concrete Sealing', 'Homeowner service package for concrete sealing with clear options, starting price, and Smart Choice Contractors USA workflow.', 800, ['Project Type'=>['Residential','Commercial'],'Permit Required'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Curb Repair', 'Homeowner service package for curb repair with clear options, starting price, and Smart Choice Contractors USA workflow.', 850, ['Project Type'=>['Residential','Commercial'],'Permit Required'=>['Yes','No']]);
        $catId = scp_get_category_193($CI, 'Fencing');
        scp_product_193($CI, $catId, 'Fence Installation', 'Homeowner service package for fence installation with clear options, starting price, and Smart Choice Contractors USA workflow.', 300, ['Fence Height'=>['4 ft','6 ft','8 ft'],'Fence Material'=>['Wood','Vinyl','Aluminum','Chain Link'],'Gate Option'=>['No Gate','48 in Gate','60 in Gate','72 in Gate'],'Double Gate Option'=>['None','8 ft Double Gate','10 ft Double Gate','12 ft Double Gate'],'Remove Existing Fence'=>['Yes','No'],'Permit Help'=>['Yes','No'],'HOA Help'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Wood Fence Installation', 'Homeowner service package for wood fence installation with clear options, starting price, and Smart Choice Contractors USA workflow.', 350, ['Fence Height'=>['4 ft','6 ft','8 ft'],'Fence Material'=>['Wood','Vinyl','Aluminum','Chain Link'],'Gate Option'=>['No Gate','48 in Gate','60 in Gate','72 in Gate'],'Double Gate Option'=>['None','8 ft Double Gate','10 ft Double Gate','12 ft Double Gate'],'Remove Existing Fence'=>['Yes','No'],'Permit Help'=>['Yes','No'],'HOA Help'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Vinyl Fence Installation', 'Homeowner service package for vinyl fence installation with clear options, starting price, and Smart Choice Contractors USA workflow.', 400, ['Fence Height'=>['4 ft','6 ft','8 ft'],'Fence Material'=>['Wood','Vinyl','Aluminum','Chain Link'],'Gate Option'=>['No Gate','48 in Gate','60 in Gate','72 in Gate'],'Double Gate Option'=>['None','8 ft Double Gate','10 ft Double Gate','12 ft Double Gate'],'Remove Existing Fence'=>['Yes','No'],'Permit Help'=>['Yes','No'],'HOA Help'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Chain Link Fence Installation', 'Homeowner service package for chain link fence installation with clear options, starting price, and Smart Choice Contractors USA workflow.', 450, ['Fence Height'=>['4 ft','6 ft','8 ft'],'Fence Material'=>['Wood','Vinyl','Aluminum','Chain Link'],'Gate Option'=>['No Gate','48 in Gate','60 in Gate','72 in Gate'],'Double Gate Option'=>['None','8 ft Double Gate','10 ft Double Gate','12 ft Double Gate'],'Remove Existing Fence'=>['Yes','No'],'Permit Help'=>['Yes','No'],'HOA Help'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Fence Repair', 'Homeowner service package for fence repair with clear options, starting price, and Smart Choice Contractors USA workflow.', 500, ['Fence Height'=>['4 ft','6 ft','8 ft'],'Fence Material'=>['Wood','Vinyl','Aluminum','Chain Link'],'Gate Option'=>['No Gate','48 in Gate','60 in Gate','72 in Gate'],'Double Gate Option'=>['None','8 ft Double Gate','10 ft Double Gate','12 ft Double Gate'],'Remove Existing Fence'=>['Yes','No'],'Permit Help'=>['Yes','No'],'HOA Help'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Gate Installation', 'Homeowner service package for gate installation with clear options, starting price, and Smart Choice Contractors USA workflow.', 550, ['Fence Height'=>['4 ft','6 ft','8 ft'],'Fence Material'=>['Wood','Vinyl','Aluminum','Chain Link'],'Gate Option'=>['No Gate','48 in Gate','60 in Gate','72 in Gate'],'Double Gate Option'=>['None','8 ft Double Gate','10 ft Double Gate','12 ft Double Gate'],'Remove Existing Fence'=>['Yes','No'],'Permit Help'=>['Yes','No'],'HOA Help'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Double Gate Installation', 'Homeowner service package for double gate installation with clear options, starting price, and Smart Choice Contractors USA workflow.', 600, ['Fence Height'=>['4 ft','6 ft','8 ft'],'Fence Material'=>['Wood','Vinyl','Aluminum','Chain Link'],'Gate Option'=>['No Gate','48 in Gate','60 in Gate','72 in Gate'],'Double Gate Option'=>['None','8 ft Double Gate','10 ft Double Gate','12 ft Double Gate'],'Remove Existing Fence'=>['Yes','No'],'Permit Help'=>['Yes','No'],'HOA Help'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Fence Removal', 'Homeowner service package for fence removal with clear options, starting price, and Smart Choice Contractors USA workflow.', 650, ['Fence Height'=>['4 ft','6 ft','8 ft'],'Fence Material'=>['Wood','Vinyl','Aluminum','Chain Link'],'Gate Option'=>['No Gate','48 in Gate','60 in Gate','72 in Gate'],'Double Gate Option'=>['None','8 ft Double Gate','10 ft Double Gate','12 ft Double Gate'],'Remove Existing Fence'=>['Yes','No'],'Permit Help'=>['Yes','No'],'HOA Help'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Fence Permit Help', 'Homeowner service package for fence permit help with clear options, starting price, and Smart Choice Contractors USA workflow.', 700, ['Fence Height'=>['4 ft','6 ft','8 ft'],'Fence Material'=>['Wood','Vinyl','Aluminum','Chain Link'],'Gate Option'=>['No Gate','48 in Gate','60 in Gate','72 in Gate'],'Double Gate Option'=>['None','8 ft Double Gate','10 ft Double Gate','12 ft Double Gate'],'Remove Existing Fence'=>['Yes','No'],'Permit Help'=>['Yes','No'],'HOA Help'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'HOA Fence Package', 'Homeowner service package for hoa fence package with clear options, starting price, and Smart Choice Contractors USA workflow.', 750, ['Fence Height'=>['4 ft','6 ft','8 ft'],'Fence Material'=>['Wood','Vinyl','Aluminum','Chain Link'],'Gate Option'=>['No Gate','48 in Gate','60 in Gate','72 in Gate'],'Double Gate Option'=>['None','8 ft Double Gate','10 ft Double Gate','12 ft Double Gate'],'Remove Existing Fence'=>['Yes','No'],'Permit Help'=>['Yes','No'],'HOA Help'=>['Yes','No']]);
        scp_product_193($CI, $catId, 'Post Replacement', 'Homeowner service package for post replacement with clear options, starting price, and Smart Choice Contractors USA workflow.', 800, ['Fence Height'=>['4 ft','6 ft','8 ft'],'Fence Material'=>['Wood','Vinyl','Aluminum','Chain Link'],'Gate Option'=>['No Gate','48 in Gate','60 in Gate','72 in Gate'],'Double Gate Option'=>['None','8 ft Double Gate','10 ft Double Gate','12 ft Double Gate'],'Remove Existing Fence'=>['Yes','No'],'Permit Help'=>['Yes','No'],'HOA Help'=>['Yes','No']]);
        $catId = scp_get_category_193($CI, 'Engineering & Permits');
        scp_product_193($CI, $catId, 'Engineering Digital Signature', 'Homeowner service package for engineering digital signature with clear options, starting price, and Smart Choice Contractors USA workflow.', 450, ['Engineering Tier'=>['Up to $2,500','$2,500-$5,000','$5,000-$10,000','$10,000+'],'Project Type'=>['Residential','Commercial'],'Plan Type'=>['Structural','MEP','Energy Calculation','Wind Load'],'Delivery'=>['Digital Signature','Permit Package']]);
        scp_product_193($CI, $catId, 'Structural Engineering Letter', 'Homeowner service package for structural engineering letter with clear options, starting price, and Smart Choice Contractors USA workflow.', 500, ['Engineering Tier'=>['Up to $2,500','$2,500-$5,000','$5,000-$10,000','$10,000+'],'Project Type'=>['Residential','Commercial'],'Plan Type'=>['Structural','MEP','Energy Calculation','Wind Load'],'Delivery'=>['Digital Signature','Permit Package']]);
        scp_product_193($CI, $catId, 'MEP Engineering Package', 'Homeowner service package for mep engineering package with clear options, starting price, and Smart Choice Contractors USA workflow.', 550, ['Engineering Tier'=>['Up to $2,500','$2,500-$5,000','$5,000-$10,000','$10,000+'],'Project Type'=>['Residential','Commercial'],'Plan Type'=>['Structural','MEP','Energy Calculation','Wind Load'],'Delivery'=>['Digital Signature','Permit Package']]);
        scp_product_193($CI, $catId, 'Energy Calculations', 'Homeowner service package for energy calculations with clear options, starting price, and Smart Choice Contractors USA workflow.', 600, ['Engineering Tier'=>['Up to $2,500','$2,500-$5,000','$5,000-$10,000','$10,000+'],'Project Type'=>['Residential','Commercial'],'Plan Type'=>['Structural','MEP','Energy Calculation','Wind Load'],'Delivery'=>['Digital Signature','Permit Package']]);
        scp_product_193($CI, $catId, 'Wind Load Report', 'Homeowner service package for wind load report with clear options, starting price, and Smart Choice Contractors USA workflow.', 650, ['Engineering Tier'=>['Up to $2,500','$2,500-$5,000','$5,000-$10,000','$10,000+'],'Project Type'=>['Residential','Commercial'],'Plan Type'=>['Structural','MEP','Energy Calculation','Wind Load'],'Delivery'=>['Digital Signature','Permit Package']]);
        scp_product_193($CI, $catId, 'Permit Drawing Package', 'Homeowner service package for permit drawing package with clear options, starting price, and Smart Choice Contractors USA workflow.', 700, ['Engineering Tier'=>['Up to $2,500','$2,500-$5,000','$5,000-$10,000','$10,000+'],'Project Type'=>['Residential','Commercial'],'Plan Type'=>['Structural','MEP','Energy Calculation','Wind Load'],'Delivery'=>['Digital Signature','Permit Package']]);
        scp_product_193($CI, $catId, 'As Built Drawing', 'Homeowner service package for as built drawing with clear options, starting price, and Smart Choice Contractors USA workflow.', 750, ['Engineering Tier'=>['Up to $2,500','$2,500-$5,000','$5,000-$10,000','$10,000+'],'Project Type'=>['Residential','Commercial'],'Plan Type'=>['Structural','MEP','Energy Calculation','Wind Load'],'Delivery'=>['Digital Signature','Permit Package']]);
        scp_product_193($CI, $catId, 'Site Plan Drafting', 'Homeowner service package for site plan drafting with clear options, starting price, and Smart Choice Contractors USA workflow.', 800, ['Engineering Tier'=>['Up to $2,500','$2,500-$5,000','$5,000-$10,000','$10,000+'],'Project Type'=>['Residential','Commercial'],'Plan Type'=>['Structural','MEP','Energy Calculation','Wind Load'],'Delivery'=>['Digital Signature','Permit Package']]);
        scp_product_193($CI, $catId, 'Revision Response', 'Homeowner service package for revision response with clear options, starting price, and Smart Choice Contractors USA workflow.', 850, ['Engineering Tier'=>['Up to $2,500','$2,500-$5,000','$5,000-$10,000','$10,000+'],'Project Type'=>['Residential','Commercial'],'Plan Type'=>['Structural','MEP','Energy Calculation','Wind Load'],'Delivery'=>['Digital Signature','Permit Package']]);
        scp_product_193($CI, $catId, 'Digital Engineer Seal', 'Homeowner service package for digital engineer seal with clear options, starting price, and Smart Choice Contractors USA workflow.', 900, ['Engineering Tier'=>['Up to $2,500','$2,500-$5,000','$5,000-$10,000','$10,000+'],'Project Type'=>['Residential','Commercial'],'Plan Type'=>['Structural','MEP','Energy Calculation','Wind Load'],'Delivery'=>['Digital Signature','Permit Package']]);
        scp_product_193($CI, $catId, 'Commercial Permit Package', 'Homeowner service package for commercial permit package with clear options, starting price, and Smart Choice Contractors USA workflow.', 950, ['Engineering Tier'=>['Up to $2,500','$2,500-$5,000','$5,000-$10,000','$10,000+'],'Project Type'=>['Residential','Commercial'],'Plan Type'=>['Structural','MEP','Energy Calculation','Wind Load'],'Delivery'=>['Digital Signature','Permit Package']]);
        $catId = scp_get_category_193($CI, 'Design Services');
        scp_product_193($CI, $catId, 'Interior Design Consultation', 'Homeowner service package for interior design consultation with clear options, starting price, and Smart Choice Contractors USA workflow.', 250, ['Design Package'=>['Basic','Standard Plus','Premium'],'Room Count'=>['1 Room','2 Rooms','3 Rooms','Whole Home']]);
        scp_product_193($CI, $catId, '3D Rendering', 'Homeowner service package for 3d rendering with clear options, starting price, and Smart Choice Contractors USA workflow.', 300, ['Design Package'=>['Basic','Standard Plus','Premium'],'Room Count'=>['1 Room','2 Rooms','3 Rooms','Whole Home']]);
        scp_product_193($CI, $catId, 'Material Selection Board', 'Homeowner service package for material selection board with clear options, starting price, and Smart Choice Contractors USA workflow.', 350, ['Design Package'=>['Basic','Standard Plus','Premium'],'Room Count'=>['1 Room','2 Rooms','3 Rooms','Whole Home']]);
        scp_product_193($CI, $catId, 'Kitchen Layout Design', 'Homeowner service package for kitchen layout design with clear options, starting price, and Smart Choice Contractors USA workflow.', 400, ['Design Package'=>['Basic','Standard Plus','Premium'],'Room Count'=>['1 Room','2 Rooms','3 Rooms','Whole Home']]);
        scp_product_193($CI, $catId, 'Bathroom Layout Design', 'Homeowner service package for bathroom layout design with clear options, starting price, and Smart Choice Contractors USA workflow.', 450, ['Design Package'=>['Basic','Standard Plus','Premium'],'Room Count'=>['1 Room','2 Rooms','3 Rooms','Whole Home']]);
        scp_product_193($CI, $catId, 'Color Consultation', 'Homeowner service package for color consultation with clear options, starting price, and Smart Choice Contractors USA workflow.', 500, ['Design Package'=>['Basic','Standard Plus','Premium'],'Room Count'=>['1 Room','2 Rooms','3 Rooms','Whole Home']]);
        scp_product_193($CI, $catId, 'Flooring Design Plan', 'Homeowner service package for flooring design plan with clear options, starting price, and Smart Choice Contractors USA workflow.', 550, ['Design Package'=>['Basic','Standard Plus','Premium'],'Room Count'=>['1 Room','2 Rooms','3 Rooms','Whole Home']]);
        scp_product_193($CI, $catId, 'Lighting Design Plan', 'Homeowner service package for lighting design plan with clear options, starting price, and Smart Choice Contractors USA workflow.', 600, ['Design Package'=>['Basic','Standard Plus','Premium'],'Room Count'=>['1 Room','2 Rooms','3 Rooms','Whole Home']]);
        scp_product_193($CI, $catId, 'Cabinet Design Plan', 'Homeowner service package for cabinet design plan with clear options, starting price, and Smart Choice Contractors USA workflow.', 650, ['Design Package'=>['Basic','Standard Plus','Premium'],'Room Count'=>['1 Room','2 Rooms','3 Rooms','Whole Home']]);
        scp_product_193($CI, $catId, 'Project Scope Package', 'Homeowner service package for project scope package with clear options, starting price, and Smart Choice Contractors USA workflow.', 700, ['Design Package'=>['Basic','Standard Plus','Premium'],'Room Count'=>['1 Room','2 Rooms','3 Rooms','Whole Home']]);
        $catId = scp_get_category_193($CI, 'Cleaning');
        scp_product_193($CI, $catId, 'Post Construction Cleaning', 'Homeowner service package for post construction cleaning with clear options, starting price, and Smart Choice Contractors USA workflow.', 175, ['Cleaning Level'=>['Basic','Standard Plus','Premium'],'Room Count'=>['1 Room','2 Rooms','3 Rooms','Whole Home']]);
        scp_product_193($CI, $catId, 'Move In Cleaning', 'Homeowner service package for move in cleaning with clear options, starting price, and Smart Choice Contractors USA workflow.', 225, ['Cleaning Level'=>['Basic','Standard Plus','Premium'],'Room Count'=>['1 Room','2 Rooms','3 Rooms','Whole Home']]);
        scp_product_193($CI, $catId, 'Window Cleaning Package', 'Homeowner service package for window cleaning package with clear options, starting price, and Smart Choice Contractors USA workflow.', 275, ['Cleaning Level'=>['Basic','Standard Plus','Premium'],'Room Count'=>['1 Room','2 Rooms','3 Rooms','Whole Home']]);
        scp_product_193($CI, $catId, 'Pressure Washing', 'Homeowner service package for pressure washing with clear options, starting price, and Smart Choice Contractors USA workflow.', 325, ['Cleaning Level'=>['Basic','Standard Plus','Premium'],'Room Count'=>['1 Room','2 Rooms','3 Rooms','Whole Home']]);
        scp_product_193($CI, $catId, 'Debris Hauling', 'Homeowner service package for debris hauling with clear options, starting price, and Smart Choice Contractors USA workflow.', 375, ['Cleaning Level'=>['Basic','Standard Plus','Premium'],'Room Count'=>['1 Room','2 Rooms','3 Rooms','Whole Home']]);
        scp_product_193($CI, $catId, 'Garage Cleanout', 'Homeowner service package for garage cleanout with clear options, starting price, and Smart Choice Contractors USA workflow.', 425, ['Cleaning Level'=>['Basic','Standard Plus','Premium'],'Room Count'=>['1 Room','2 Rooms','3 Rooms','Whole Home']]);
        scp_product_193($CI, $catId, 'Appliance Cleaning', 'Homeowner service package for appliance cleaning with clear options, starting price, and Smart Choice Contractors USA workflow.', 475, ['Cleaning Level'=>['Basic','Standard Plus','Premium'],'Room Count'=>['1 Room','2 Rooms','3 Rooms','Whole Home']]);
        scp_product_193($CI, $catId, 'Deep Cleaning', 'Homeowner service package for deep cleaning with clear options, starting price, and Smart Choice Contractors USA workflow.', 525, ['Cleaning Level'=>['Basic','Standard Plus','Premium'],'Room Count'=>['1 Room','2 Rooms','3 Rooms','Whole Home']]);
        scp_product_193($CI, $catId, 'Final Touch Cleaning', 'Homeowner service package for final touch cleaning with clear options, starting price, and Smart Choice Contractors USA workflow.', 575, ['Cleaning Level'=>['Basic','Standard Plus','Premium'],'Room Count'=>['1 Room','2 Rooms','3 Rooms','Whole Home']]);
        scp_product_193($CI, $catId, 'Dust Control Cleaning', 'Homeowner service package for dust control cleaning with clear options, starting price, and Smart Choice Contractors USA workflow.', 625, ['Cleaning Level'=>['Basic','Standard Plus','Premium'],'Room Count'=>['1 Room','2 Rooms','3 Rooms','Whole Home']]);

        $CI->db->query('SET foreign_key_checks = 1');
    }
}

class Migration_Version_193 extends App_module_migration
{
    public function up()
    {
        products_smartchoice_catalog_seed_193();
    }

    public function down()
    {
        // Keep seeded homeowner catalog data in place on rollback.
    }
}
