<?php defined('BASEPATH') or exit('No direct script access allowed'); init_head(); ?>
<style>
.sf-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(290px,1fr));gap:18px}.sf-card{background:#fff;border:1px solid #e7e9ed;border-radius:12px;box-shadow:0 3px 12px rgba(0,0,0,.06);overflow:hidden}.sf-preview{height:235px;padding:14px;background:#f5f6f8;display:flex;align-items:center;justify-content:center}.sf-preview-image{width:100%;height:100%;object-fit:contain;background:#fff;border:1px solid #e4e7eb;box-shadow:0 3px 10px rgba(0,0,0,.08)}.sf-paper{width:100%;height:100%;background:#fff;border:1px solid #e4e7eb;box-shadow:0 3px 10px rgba(0,0,0,.08);padding:13px;position:relative;overflow:hidden}.sf-mini-head{height:38px;margin-bottom:10px}.sf-mini-title{height:9px;width:42%;margin-bottom:5px}.sf-mini-line{height:5px;background:#e8eaed;margin:5px 0;border-radius:2px}.sf-mini-meta{display:flex;gap:5px;margin:10px 0}.sf-mini-meta span{height:30px;flex:1}.sf-mini-table{margin-top:10px;border:1px solid #eceff2}.sf-mini-row{height:14px}.sf-mini-total{width:38%;height:18px;margin:9px 0 0 auto}.sf-variant-blueprint .sf-paper{background-image:linear-gradient(rgba(23,54,93,.05) 1px,transparent 1px),linear-gradient(90deg,rgba(23,54,93,.05) 1px,transparent 1px);background-size:12px 12px}.sf-variant-executive .sf-mini-head{border-top:7px solid #111827;border-bottom:1px solid #b8bec6;background:transparent!important}.sf-variant-modern-edge .sf-paper{border-left:8px solid var(--sf-primary)}.sf-variant-citrus .sf-mini-head{border-radius:18px 0 18px 0}.sf-variant-coastal .sf-mini-meta span{border-radius:12px}.sf-variant-emerald .sf-mini-table{border-radius:8px;overflow:hidden}.sf-variant-contrast .sf-mini-head{height:48px}.sf-variant-signature .sf-paper:after{content:"";position:absolute;right:16px;bottom:16px;width:34px;height:34px;border-radius:50%;background:var(--sf-accent);box-shadow:0 0 0 4px #fff}.sf-variant-split .sf-mini-head{width:48%;margin-left:52%}.sf-variant-boxed .sf-mini-meta span{border:1px solid #cfd5dc;background:#fff!important}.sf-body{padding:15px}.sf-title{font-size:16px;font-weight:600;margin-bottom:6px}.sf-design{font-size:12px;color:#7b8491;margin-bottom:10px;text-transform:capitalize}.sf-actions{display:flex;gap:6px;flex-wrap:wrap}.sf-actions .btn{padding:5px 8px}.sf-active{box-shadow:0 0 0 2px #169179 inset}
</style>
<div id="wrapper"><div class="content">
<div class="row"><div class="col-md-12"><div class="panel_s"><div class="panel-body">
<div class="tw-flex tw-justify-between tw-items-center tw-mb-4"><div><h4 class="tw-m-0"><?php echo _l('styleflow_document_templates'); ?></h4><p class="text-muted tw-mt-1"><?php echo _l('styleflow_manage_help'); ?></p></div><?php if (staff_can('view','settings')): ?><a href="<?php echo admin_url('styleflow/settings'); ?>" class="btn btn-default"><i class="fa fa-cog"></i> <?php echo _l('styleflow_crm_settings'); ?></a><?php endif; ?></div>
<div class="sf-grid">
<?php foreach ($templates as $tpl):
$inv=styleflow_active_template('invoice')===$tpl['slug']; $est=styleflow_active_template('estimate')===$tpl['slug']; $pro=styleflow_active_template('proposal')===$tpl['slug'];
$variant=styleflow_design_variant($tpl); $example=styleflow_template_preview_image_url($tpl); ?>
<div class="sf-card <?php echo ($inv||$est||$pro)?'sf-active':''; ?>">
<div class="sf-preview sf-variant-<?php echo html_escape($variant); ?>" style="--sf-primary:<?php echo html_escape($tpl['primary_color']); ?>;--sf-secondary:<?php echo html_escape($tpl['secondary_color']); ?>;--sf-accent:<?php echo html_escape($tpl['accent_color']); ?>;">
<?php if ($example): ?>
<img class="sf-preview-image" loading="lazy" src="<?php echo html_escape($example); ?>" alt="<?php echo html_escape(styleflow_template_display_name($tpl)); ?>">
<?php else: ?>
<div class="sf-paper"><div class="sf-mini-head" style="background:<?php echo html_escape($tpl['primary_color']); ?>"></div><div class="sf-mini-title" style="background:<?php echo html_escape($tpl['primary_color']); ?>"></div><div class="sf-mini-line" style="width:58%"></div><div class="sf-mini-line" style="width:35%"></div><div class="sf-mini-meta"><span style="background:<?php echo html_escape($tpl['secondary_color']); ?>"></span><span style="background:<?php echo html_escape($tpl['secondary_color']); ?>"></span><span style="background:<?php echo html_escape($tpl['secondary_color']); ?>"></span></div><div class="sf-mini-table"><div class="sf-mini-row" style="background:<?php echo html_escape($tpl['primary_color']); ?>"></div><div class="sf-mini-row" style="background:<?php echo html_escape($tpl['secondary_color']); ?>"></div><div class="sf-mini-row" style="background:#fff"></div><div class="sf-mini-row" style="background:<?php echo html_escape($tpl['secondary_color']); ?>"></div></div><div class="sf-mini-total" style="background:<?php echo html_escape($tpl['accent_color']); ?>"></div></div>
<?php endif; ?>
</div>
<div class="sf-body"><div class="sf-title"><?php echo html_escape(styleflow_template_display_name($tpl)); ?></div><div class="sf-design"><?php echo html_escape(_l('styleflow_design_style')); ?>: <?php echo html_escape(str_replace('-', ' ', $variant)); ?></div><div class="sf-actions">
<?php if (!empty($tpl['available_proposal'])): ?><a class="btn btn-xs <?php echo $pro?'btn-success':'btn-primary'; ?>" href="<?php echo admin_url('styleflow/activate/proposal/'.$tpl['slug']); ?>"><?php echo $pro?_l('styleflow_active_proposal'):_l('styleflow_activate_proposal'); ?></a><?php endif; ?>
<?php if (!empty($tpl['available_invoice'])): ?><a class="btn btn-xs <?php echo $inv?'btn-success':'btn-primary'; ?>" href="<?php echo admin_url('styleflow/activate/invoice/'.$tpl['slug']); ?>"><?php echo $inv?_l('styleflow_active_invoice'):_l('styleflow_activate_invoice'); ?></a><?php endif; ?>
<?php if (!empty($tpl['available_estimate'])): ?><a class="btn btn-xs <?php echo $est?'btn-success':'btn-primary'; ?>" href="<?php echo admin_url('styleflow/activate/estimate/'.$tpl['slug']); ?>"><?php echo $est?_l('styleflow_active_estimate'):_l('styleflow_activate_estimate'); ?></a><?php endif; ?>
<a class="btn btn-xs btn-info" target="_blank" href="<?php echo admin_url('styleflow/preview/'.$tpl['slug']); ?>"><i class="fa fa-eye"></i> <?php echo _l('styleflow_full_preview'); ?></a>
</div></div></div>
<?php endforeach; ?>
</div></div></div></div></div>
</div></div>
<?php init_tail(); ?>
