<?php defined('BASEPATH') or exit('No direct script access allowed'); init_head();
$t=$template;
$variant=styleflow_design_variant($t);
$staffId=((string)($t['staff_photo_mode'] ?? 'none')==='selected') ? (int)($t['selected_staff_id'] ?? 0) : 0;
$staffPhoto=$staffId ? styleflow_staff_photo_source($staffId, false) : null;
$staffName=$staffId ? styleflow_staff_display_name($staffId) : _l('styleflow_preview_employee');
?>
<style>
.sf-full-preview{max-width:900px;margin:0 auto;background:#fff;border:1px solid #dfe3e8;box-shadow:0 8px 30px rgba(0,0,0,.10);padding:42px;font-family:Arial,sans-serif;position:relative;overflow:hidden}.sf-hdr{display:flex;justify-content:space-between;align-items:flex-start;padding-bottom:18px;margin-bottom:24px}.sf-logo{font-size:26px;font-weight:800;letter-spacing:.5px}.sf-doc-title{font-size:31px;font-weight:800;text-align:right}.sf-meta{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:20px 0}.sf-meta>div{padding:14px}.sf-addresses{display:grid;grid-template-columns:1fr 1fr;gap:22px;margin:24px 0}.sf-items{width:100%;border-collapse:collapse}.sf-items th,.sf-items td{padding:11px}.sf-total{margin-left:auto;margin-top:18px;width:42%;padding:14px;font-size:17px;font-weight:700}.sf-note{margin-top:28px;padding-top:12px}.sf-employee{display:flex;align-items:center;gap:10px;margin-top:24px}.sf-employee img,.sf-avatar{width:58px;height:58px;border-radius:50%;object-fit:cover}.sf-avatar{display:flex;align-items:center;justify-content:center;color:#fff;font-weight:700;font-size:11px}.sf-v-blueprint{background-image:linear-gradient(rgba(23,54,93,.04) 1px,transparent 1px),linear-gradient(90deg,rgba(23,54,93,.04) 1px,transparent 1px);background-size:18px 18px}.sf-v-blueprint .sf-hdr{border:2px solid var(--p);padding:18px}.sf-v-executive{border-top:12px solid #111827}.sf-v-executive .sf-hdr{border-bottom:1px solid #9ca3af}.sf-v-executive .sf-meta>div{border:1px solid #d1d5db;background:#fff!important}.sf-v-modern-edge{border-left:14px solid var(--p)}.sf-v-modern-edge .sf-doc-title{background:var(--p);color:#fff;padding:10px 16px;border-radius:16px 0 16px 0}.sf-v-citrus .sf-hdr{background:var(--p);color:#fff;margin:-42px -42px 25px;padding:28px 42px}.sf-v-coastal .sf-meta>div{border-radius:16px}.sf-v-emerald .sf-items{border-radius:10px;overflow:hidden;box-shadow:0 0 0 1px #dfe7e4}.sf-v-contrast .sf-hdr{background:#111827;color:#fff;margin:-42px -42px 25px;padding:28px 42px;border-bottom:8px solid var(--a)}.sf-v-signature .sf-note{font-family:Georgia,serif;font-style:italic;border-top:1px solid var(--a)}.sf-v-split .sf-hdr .sf-logo{width:45%}.sf-v-split .sf-doc-title{width:45%;border-left:5px solid var(--p);padding-left:18px}.sf-v-boxed .sf-addresses>div,.sf-v-boxed .sf-meta>div{border:1px solid #d6dbe1}.sf-v-band .sf-hdr{background:var(--p);color:#fff;margin:-42px -42px 25px;padding:28px 42px}
</style>
<div id="wrapper"><div class="content"><div class="panel_s"><div class="panel-body">
<div class="tw-flex tw-justify-between tw-items-center"><div><h4><?php echo html_escape(styleflow_template_display_name($t)); ?></h4><p class="text-muted"><?php echo _l('styleflow_preview_structure_help'); ?></p></div><a href="<?php echo admin_url('styleflow/manage_templates'); ?>" class="btn btn-default"><?php echo _l('go_back'); ?></a></div><hr>
<div class="sf-full-preview sf-v-<?php echo html_escape($variant); ?>" style="--p:<?php echo html_escape($t['primary_color']); ?>;--s:<?php echo html_escape($t['secondary_color']); ?>;--a:<?php echo html_escape($t['accent_color']); ?>;color:<?php echo html_escape($t['text_color']); ?>;font-family:<?php echo html_escape($t['font_family']); ?>;">
<div class="sf-hdr" style="border-color:<?php echo html_escape($t['primary_color']); ?>"><div class="sf-logo" style="color:<?php echo in_array($variant,['band','citrus','contrast'],true)?'#fff':html_escape($t['primary_color']); ?>">SMART CHOICE<br><small style="font-size:11px;font-weight:400">CONTRACTORS USA</small></div><div class="sf-doc-title" style="color:<?php echo in_array($variant,['band','citrus','contrast'],true)?'#fff':html_escape($t['primary_color']); ?>"><?php echo html_escape(_l('styleflow_preview_invoice')); ?><br><small style="font-size:13px"># INV-000123</small></div></div>
<div class="sf-meta"><div style="background:<?php echo html_escape($t['secondary_color']); ?>"><b><?php echo _l('styleflow_preview_date'); ?></b><br>08/17/2026</div><div style="background:<?php echo html_escape($t['secondary_color']); ?>"><b><?php echo _l('styleflow_preview_due'); ?></b><br>08/27/2026</div><div style="background:<?php echo html_escape($t['secondary_color']); ?>"><b><?php echo _l('status'); ?></b><br>Sent</div></div>
<div class="sf-addresses"><div><b style="color:<?php echo html_escape($t['primary_color']); ?>">SMART CHOICE CONTRACTORS USA</b><br>Professional Construction Services<br>Tampa Bay, Florida</div><div><b style="color:<?php echo html_escape($t['primary_color']); ?>"><?php echo _l('styleflow_preview_bill_to'); ?></b><br><?php echo _l('styleflow_preview_customer_name'); ?><br><?php echo _l('styleflow_preview_project_address'); ?></div></div>
<table class="sf-items"><thead><tr style="background:<?php echo html_escape($t['primary_color']); ?>;color:#fff"><th><?php echo _l('styleflow_preview_description'); ?></th><th><?php echo _l('styleflow_preview_qty'); ?></th><th><?php echo _l('styleflow_preview_rate'); ?></th><th><?php echo _l('styleflow_preview_amount'); ?></th></tr></thead><tbody><tr style="background:<?php echo html_escape($t['secondary_color']); ?>"><td><?php echo _l('styleflow_preview_service_item'); ?></td><td>1</td><td>$2,500.00</td><td>$2,500.00</td></tr><tr><td>Project coordination and installation</td><td>1</td><td>$450.00</td><td>$450.00</td></tr></tbody></table>
<div class="sf-total" style="background:<?php echo html_escape($t['primary_color']); ?>;color:#fff"><?php echo _l('styleflow_total'); ?>: $2,950.00</div>
<div class="sf-note" style="border-color:<?php echo html_escape($t['accent_color']); ?>"><?php echo _l('styleflow_preview_thank_you'); ?></div>
<?php if (($t['staff_photo_mode'] ?? 'none') !== 'none'): ?><div class="sf-employee"><?php if($staffPhoto): ?><img src="<?php echo html_escape($staffPhoto); ?>" alt=""><?php else: ?><div class="sf-avatar" style="background:<?php echo html_escape($t['accent_color']); ?>">STAFF</div><?php endif; ?><div><b><?php echo html_escape($staffName); ?></b><br><small><?php echo _l('styleflow_employee_representative'); ?></small></div></div><?php endif; ?>
</div>
</div></div></div></div>
<?php init_tail(); ?>
