// Exercise the shipped PHP partial using dummy input values, never submit a login.
const assert = require('node:assert/strict');
const path = require('node:path');
const {execFileSync} = require('node:child_process');
const {JSDOM} = require('jsdom');
const partial = path.resolve(__dirname, '../application/views/authentication/includes/password_visibility.php');
const script = execFileSync('php', ['-r', 'define("BASEPATH", true); include $argv[1];', partial], {encoding:'utf8'});
const dom = new JSDOM('<form><label for="password">Password</label><input id="password" name="password" type="password"><input id="passwordr" name="passwordr" type="password"><input name="remember" type="checkbox" value="1"></form>'+script, {runScripts:'dangerously'});
const doc = dom.window.document;
const inputs = [...doc.querySelectorAll('input[type="password"]')];
const buttons = [...doc.querySelectorAll('.sc-auth-password button')];
const form = doc.querySelector('form');
let submits=0;
form.addEventListener('submit', e=>{ e.preventDefault(); submits++; });
inputs.forEach((input,i)=>input.value='dummy-'+i);
const payload=[...new dom.window.FormData(form)];
buttons.forEach((button,i)=>{
    assert.equal(button.type,'button');
    assert.equal(button.getAttribute('aria-controls'),inputs[i].id);
    assert.equal(button.getAttribute('aria-label'),'Show password');
    button.click();
    assert.equal(inputs[i].type,'text');
    assert.equal(button.getAttribute('aria-pressed'),'true');
    assert.equal(button.getAttribute('aria-label'),'Hide password');
    assert.equal(inputs[1-i].type,'password');
    assert.deepEqual([...new dom.window.FormData(form)],payload);
    button.click();
    assert.equal(inputs[i].type,'password');
});
assert.equal(submits,0);
buttons.forEach(button=>button.click());
form.dispatchEvent(new dom.window.Event('submit',{cancelable:true}));
assert.ok(inputs.every(input=>input.type==='password'));
buttons.forEach(button=>button.click());
form.reset();
assert.ok(inputs.every(input=>input.type==='password'));
doc.querySelector('[name="remember"]').checked=true;
assert.equal(new dom.window.FormData(form).get('remember'),'1');
dom.window.close();
console.log('PASS password eyes: independent controls, accessible labels, unchanged values, remasking and Remember me payload');
