'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const {JSDOM} = require('jsdom');
const view = fs.readFileSync(path.join(__dirname, '../modules/google_meet/views/dashboard.php'), 'utf8');
const script = view.match(/<script>([\s\S]*?)<\/script>/)[1].replace(/<\?php echo admin_url\('([^']*)'\); \?>/g, (_, uri) => '/admin/' + uri);
const modal = view.match(/<div class="modal fade" id="gm-meeting-view-modal"[\s\S]*?(?=<script>)/)[0];
const dom = new JSDOM('<button class="gm-view-popup" data-id="43">View</button>' + modal, {url: 'https://crm.example/admin/google_meet', runScripts: 'outside-only'});
const w = dom.window, d = w.document;
const state = {requests: [], opened: 0, alerts: []};
let payload = {success: true, title: '<img src=x onerror=alert(1)>', description: '<script>alert(1)</script>', start_time: '10/08/2026 7:16 AM', status: 'Scheduled', meet_link: 'https://meet.jit.si/SC-shared-room', room_url: '/admin/google_meet/room/43'};
w.fetch = async url => {state.requests.push(url); return {json: async () => payload};};
w.jQuery = () => ({modal: action => {if (action === 'show') state.opened++;}});
w.alert = text => state.alerts.push(text);
w.eval(script);
const tick = () => new Promise(resolve => setTimeout(resolve, 10));
let checks = 0;
function check(value, label) {assert.ok(value, label);checks++;}
(async () => {
    await tick();
    d.querySelector('.gm-view-popup').click(); await tick();
    check(state.requests[0] === '/admin/google_meet/meeting_modal/43' && state.opened === 1, 'View keeps the existing permission-checked quick preview request');
    check(w.location.pathname === '/admin/google_meet', 'Preview does not directly navigate away from the dashboard');
    check(d.getElementById('gm-modal-details').getAttribute('href') === '/admin/google_meet/view/43', 'Full details are discoverable from the preview');
    check(d.getElementById('gm-modal-join').getAttribute('href') === payload.room_url, 'Join uses the authorized CRM room URL');
    check(d.getElementById('gm-modal-link').getAttribute('href') === payload.meet_link, 'Saved invitation room unchanged');
    check(d.getElementById('gm-modal-title').textContent === payload.title && !d.querySelector('#gm-modal-title img') && !d.querySelector('#gm-modal-description script'), 'Preview values are text rather than executable HTML');
    payload = {...payload, room_url: '', meet_link: ''};
    d.querySelector('.gm-view-popup').click(); await tick();
    check(!d.getElementById('gm-modal-join').hasAttribute('href') && d.getElementById('gm-modal-join').getAttribute('aria-disabled') === 'true', 'Pending rooms cannot navigate to an invalid join link');
    check(d.getElementById('gm-modal-link').textContent === 'Meeting link pending' && !d.getElementById('gm-modal-link').hasAttribute('href'), 'Pending room has useful feedback');
    payload = {...payload, room_url: '/admin/google_meet/room/43', meet_link: 'https://meet.jit.si/SC-shared-room'};
    d.querySelector('.gm-view-popup').click(); await tick();
    check(d.getElementById('gm-modal-join').getAttribute('aria-disabled') === 'false' && !d.getElementById('gm-modal-join').hasAttribute('tabindex'), 'Saved rooms become keyboard-accessible after a pending preview');
    payload = {success: false, message: 'Meeting not found.'};
    const opened = state.opened; d.querySelector('.gm-view-popup').click(); await tick();
    check(state.opened === opened && state.alerts.includes('Meeting not found.'), 'Denied or missing records do not open a stale preview');
    d.querySelector('.gm-view-popup').setAttribute('data-id', '../settings');
    const requests = state.requests.length; d.querySelector('.gm-view-popup').click(); await tick();
    check(state.requests.length === requests, 'Only numeric meeting identifiers are requested');
    w.close(); console.log(`PASS: ${checks} quick-preview, safe room, detail navigation and escaping checks`);
})().catch(error => {w.close();console.error(error);process.exitCode = 1;});
