'use strict';
const assert = require('node:assert/strict');
const { execFileSync } = require('node:child_process');
const path = require('node:path');
const { JSDOM } = require('jsdom');
const html = execFileSync('php', [path.join(__dirname, 'proposal_content_preview.php'), '--fixture'], { encoding: 'utf8' });
const dom = new JSDOM(html, { runScripts: 'outside-only' });
const w = dom.window;
const disclosure = w.document.getElementById('sc-proposal-content-editor');
const preview = w.document.getElementById('sc-proposal-content-preview');
const raw = w.document.getElementById('proposal_content_area');
let initializations = 0;
let template = raw.innerHTML;
w.init_proposal_editor = () => { initializations++; };
w.tinymce = { get: id => {
    assert.equal(id, 'proposal_content_area');
    return { getContent: () => template };
} };
w.eval(w.document.querySelector('script').textContent);
assert.equal(disclosure.open, false);
assert.equal(initializations, 0, 'closed template does not initialize or autosave');
assert.doesNotMatch(preview.innerHTML, /proposal_items/);
assert.match(raw.innerHTML, /\{\{ proposal_items \}\}/);
disclosure.open = true;
disclosure.dispatchEvent(new w.Event('toggle'));
assert.equal(initializations, 1);
assert.equal(preview.hidden, true);
assert.equal(raw.innerHTML, template, 'opening editor preserves template');
// Closing shows the latest editor content, without leaking tokens or modifying that content.
template = '<p>Updated scope</p><p>{PROPOSAL_ITEMS}</p><p>{{ proposal_items }}</p>';
disclosure.open = false;
disclosure.dispatchEvent(new w.Event('toggle'));
assert.equal(preview.hidden, false);
assert.match(preview.innerHTML, /Updated scope/);
assert.doesNotMatch(preview.innerHTML, /proposal_items/i);
assert.match(template, /PROPOSAL_ITEMS/, 'preview refresh does not rewrite save payload');
disclosure.open = true;
disclosure.dispatchEvent(new w.Event('toggle'));
assert.equal(initializations, 1, 'reopening keeps the same editor');
w.close();
console.log('PASS proposal preview disclosure, lazy editor initialization, reopen and content refresh; no external writes');
