const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const {JSDOM} = require('jsdom');
const dom = new JSDOM('<aside id="menu"><div class="sidebar-user-profile open"><ul class="dropdown-menu"><li class="header-edit-profile"><a href="/admin/staff/edit_profile">Edit profile</a></li><li class="header-languages"><button type="button" class="sc-staff-language-toggle" aria-expanded="false" aria-controls="languages">Language</button><ul id="languages" class="dropdown-menu"><li><a href="/admin/staff/change_language/english">English</a></li></ul></li></ul></div></aside>',{runScripts:'outside-only'});
const doc=dom.window.document;
let parentClicks=0;
doc.querySelector('.sidebar-user-profile').addEventListener('click',()=>parentClicks++);
dom.window.eval(fs.readFileSync(path.join(__dirname,'../assets/js/staff-profile-menu.js'),'utf8'));
const button=doc.querySelector('button');
const item=button.parentElement;
assert.equal(button.type,'button');
button.click();
assert.equal(parentClicks,0,'Language toggle must not close the parent dropdown');
assert.equal(button.getAttribute('aria-expanded'),'true');
assert.ok(item.classList.contains('sc-language-open'));
button.click();
assert.equal(button.getAttribute('aria-expanded'),'false');
button.click();
button.dispatchEvent(new dom.window.KeyboardEvent('keydown',{key:'Escape',bubbles:true,cancelable:true}));
assert.equal(button.getAttribute('aria-expanded'),'false');
assert.equal(doc.activeElement,button);
assert.equal(doc.querySelector('.header-edit-profile a').getAttribute('href'),'/admin/staff/edit_profile');
assert.equal(doc.querySelector('#languages a').getAttribute('href'),'/admin/staff/change_language/english');
dom.window.close();
console.log('PASS staff profile: language click/keyboard state, parent stays open and native routes preserved');
