<?php defined('BASEPATH') or exit('No direct script access allowed'); ?>
<?php init_head(); ?>
<div id="wrapper"><div class="content"><div class="row"><div class="col-md-12">
<div class="smart-productivity-header"><div><h4><?php echo smart_daily_productivity_label('smart_daily_productivity_dashboard'); ?></h4><p><?php echo smart_daily_productivity_label('smart_daily_productivity_dashboard_help'); ?></p></div><div><a href="<?php echo admin_url('smart_daily_productivity/my_day'); ?>" class="btn btn-success btn-sm"><?php echo smart_daily_productivity_label('smart_daily_productivity_add_daily_entry'); ?></a> <a href="<?php echo admin_url('smart_daily_productivity/health'); ?>" class="btn btn-info btn-sm"><?php echo smart_daily_productivity_label('smart_daily_productivity_health_checker'); ?></a></div></div>
<div class="panel_s"><div class="panel-body">
<?php echo form_open(admin_url('smart_daily_productivity'), ['method'=>'get']); ?><div class="row">
<div class="col-md-3"><?php echo render_date_input('date_from', smart_daily_productivity_label('smart_daily_productivity_date_from'), $date_from); ?></div>
<div class="col-md-3"><?php echo render_date_input('date_to', smart_daily_productivity_label('smart_daily_productivity_date_to'), $date_to); ?></div>
<?php if (has_permission('smart_daily_productivity','','view')) { ?><div class="col-md-3"><label><?php echo _l('staff_member'); ?></label><select name="staff_id" class="selectpicker" data-width="100%"><option value="0"><?php echo smart_daily_productivity_label('smart_daily_productivity_all_staff'); ?></option><?php foreach($staff as $member){ ?><option value="<?php echo (int)$member['staffid']; ?>" <?php echo (int)$staff_id===(int)$member['staffid']?'selected':''; ?>><?php echo html_escape($member['firstname'].' '.$member['lastname']); ?></option><?php } ?></select></div><?php } ?>
<div class="col-md-3"><label>&nbsp;</label><button class="btn btn-primary btn-block" type="submit"><?php echo smart_daily_productivity_label('smart_daily_productivity_refresh'); ?></button></div>
</div><?php echo form_close(); ?>
</div></div>
<div class="row smart-score-cards">
<div class="col-md-2"><div class="smart-card"><span><?php echo smart_daily_productivity_label('smart_daily_productivity_entries'); ?></span><strong><?php echo (int)$summary['entries_total']; ?></strong></div></div>
<div class="col-md-2"><div class="smart-card"><span><?php echo smart_daily_productivity_label('smart_daily_productivity_total_hours'); ?></span><strong><?php echo round(((int)$summary['minutes_total'])/60,2); ?></strong></div></div>
<div class="col-md-2"><div class="smart-card"><span><?php echo smart_daily_productivity_label('smart_daily_productivity_tasks'); ?></span><strong><?php echo (int)$summary['tasks_total']; ?></strong></div></div>
<div class="col-md-2"><div class="smart-card"><span><?php echo smart_daily_productivity_label('smart_daily_productivity_tickets'); ?></span><strong><?php echo (int)$summary['tickets_total']; ?></strong></div></div>
<div class="col-md-2"><div class="smart-card"><span><?php echo smart_daily_productivity_label('smart_daily_productivity_manual'); ?></span><strong><?php echo (int)$summary['manual_total']; ?></strong></div></div>
<div class="col-md-2"><div class="smart-card"><span><?php echo smart_daily_productivity_label('smart_daily_productivity_average_score'); ?></span><strong><?php echo html_escape((string)$summary['average_score']); ?>%</strong></div></div>
</div>
<div class="panel_s"><div class="panel-body"><h4><?php echo smart_daily_productivity_label('smart_daily_productivity_employee_scoreboard'); ?></h4><div class="table-responsive"><table class="table table-striped"><thead><tr><th><?php echo _l('staff_member'); ?></th><th><?php echo _l('date'); ?></th><th><?php echo smart_daily_productivity_label('smart_daily_productivity_score'); ?></th><th><?php echo smart_daily_productivity_label('smart_daily_productivity_rating'); ?></th><th><?php echo smart_daily_productivity_label('smart_daily_productivity_total_minutes'); ?></th><th><?php echo smart_daily_productivity_label('smart_daily_productivity_completed_tasks'); ?></th><th><?php echo smart_daily_productivity_label('smart_daily_productivity_ticket_closed'); ?></th></tr></thead><tbody><?php foreach($scores as $row){ ?><tr><td><?php echo html_escape($row['firstname'].' '.$row['lastname']); ?></td><td><?php echo _d($row['score_date']); ?></td><td><div class="progress"><div class="progress-bar" role="progressbar" style="width:<?php echo min(100,(float)$row['score_percent']); ?>%"><?php echo html_escape($row['score_percent']); ?>%</div></div></td><td><?php echo html_escape($row['rating_label']); ?></td><td><?php echo (int)$row['minutes_total']; ?></td><td><?php echo (int)$row['completed_tasks']; ?></td><td><?php echo (int)$row['ticket_closed']; ?></td></tr><?php } ?></tbody></table></div></div></div>
</div></div></div></div>
<?php init_tail(); ?>
