<?php
defined('BASEPATH') or exit('No direct script access allowed');
function sccc_install(){
 $CI=&get_instance(); $CI->load->dbforge(); $p=db_prefix();
 $queries=[];
 $queries[]="CREATE TABLE IF NOT EXISTS `{$p}sccc_calls` (`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,`twilio_sid` VARCHAR(64) NULL,`staff_id` INT UNSIGNED NULL,`lead_id` INT UNSIGNED NULL,`client_id` INT UNSIGNED NULL,`contact_id` INT UNSIGNED NULL,`campaign_id` INT UNSIGNED NULL,`list_contact_id` INT UNSIGNED NULL,`direction` VARCHAR(20) NOT NULL DEFAULT 'outbound',`from_number` VARCHAR(50) NULL,`to_number` VARCHAR(50) NULL,`subject` VARCHAR(191) NULL,`status` VARCHAR(40) NOT NULL DEFAULT 'queued',`disposition` VARCHAR(80) NULL,`duration` INT UNSIGNED NOT NULL DEFAULT 0,`answered_at` DATETIME NULL,`ended_at` DATETIME NULL,`notes` TEXT NULL,`ai_summary` LONGTEXT NULL,`created_at` DATETIME NOT NULL,`updated_at` DATETIME NULL,PRIMARY KEY (`id`),KEY `twilio_sid` (`twilio_sid`),KEY `staff_id` (`staff_id`),KEY `campaign_id` (`campaign_id`),KEY `status` (`status`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;";
 $queries[]="CREATE TABLE IF NOT EXISTS `{$p}sccc_campaigns` (`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,`name` VARCHAR(191) NOT NULL,`list_id` INT UNSIGNED NOT NULL,`staff_id` INT UNSIGNED NULL,`caller_id` VARCHAR(50) NULL,`status` VARCHAR(30) NOT NULL DEFAULT 'draft',`mode` VARCHAR(20) NOT NULL DEFAULT 'power',`voicemail_greeting_id` INT UNSIGNED NULL,`ai_agent_id` INT UNSIGNED NULL,`max_attempts` INT NOT NULL DEFAULT 2,`retry_minutes` INT NOT NULL DEFAULT 60,`daily_limit` INT NOT NULL DEFAULT 500,`business_start` TIME NULL,`business_end` TIME NULL,`timezone` VARCHAR(80) NULL,`created_by` INT UNSIGNED NOT NULL,`created_at` DATETIME NOT NULL,`updated_at` DATETIME NULL,PRIMARY KEY (`id`),KEY `status` (`status`),KEY `list_id` (`list_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;";
 $queries[]="CREATE TABLE IF NOT EXISTS `{$p}sccc_lists` (`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,`name` VARCHAR(191) NOT NULL,`description` TEXT NULL,`created_by` INT UNSIGNED NOT NULL,`created_at` DATETIME NOT NULL,`updated_at` DATETIME NULL,PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;";
 $queries[]="CREATE TABLE IF NOT EXISTS `{$p}sccc_list_contacts` (`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,`list_id` INT UNSIGNED NOT NULL,`first_name` VARCHAR(100) NULL,`last_name` VARCHAR(100) NULL,`company` VARCHAR(191) NULL,`phone` VARCHAR(50) NOT NULL,`email` VARCHAR(191) NULL,`lead_source` VARCHAR(191) NULL,`assigned_staff` INT UNSIGNED NULL,`notes` TEXT NULL,`attempts` INT NOT NULL DEFAULT 0,`last_call_at` DATETIME NULL,`next_attempt_at` DATETIME NULL,`status` VARCHAR(40) NOT NULL DEFAULT 'ready',`disposition` VARCHAR(80) NULL,`do_not_call` TINYINT(1) NOT NULL DEFAULT 0,`created_at` DATETIME NOT NULL,PRIMARY KEY (`id`),KEY `list_id` (`list_id`),KEY `phone` (`phone`),KEY `status` (`status`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;";
 $queries[]="CREATE TABLE IF NOT EXISTS `{$p}sccc_extensions` (`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,`staff_id` INT UNSIGNED NULL,`extension` VARCHAR(12) NOT NULL,`display_name` VARCHAR(191) NOT NULL,`destination_type` VARCHAR(20) NOT NULL DEFAULT 'browser',`destination` VARCHAR(191) NULL,`fallback_number` VARCHAR(50) NULL,`ring_seconds` INT NOT NULL DEFAULT 25,`active` TINYINT(1) NOT NULL DEFAULT 1,`created_at` DATETIME NOT NULL,`updated_at` DATETIME NULL,PRIMARY KEY (`id`),UNIQUE KEY `extension` (`extension`),KEY `staff_id` (`staff_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;";
 $queries[]="CREATE TABLE IF NOT EXISTS `{$p}sccc_greetings` (`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,`name` VARCHAR(191) NOT NULL,`type` VARCHAR(40) NOT NULL DEFAULT 'general',`file_name` VARCHAR(255) NULL,`file_path` VARCHAR(500) NULL,`text_to_speech` TEXT NULL,`voice` VARCHAR(50) NULL,`language` VARCHAR(20) NULL,`active` TINYINT(1) NOT NULL DEFAULT 1,`created_by` INT UNSIGNED NOT NULL,`created_at` DATETIME NOT NULL,PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;";
 $queries[]="CREATE TABLE IF NOT EXISTS `{$p}sccc_callbacks` (`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,`call_id` INT UNSIGNED NULL,`name` VARCHAR(191) NULL,`phone` VARCHAR(50) NOT NULL,`staff_id` INT UNSIGNED NULL,`department_id` INT UNSIGNED NULL,`due_at` DATETIME NULL,`status` VARCHAR(30) NOT NULL DEFAULT 'pending',`notes` TEXT NULL,`created_at` DATETIME NOT NULL,`completed_at` DATETIME NULL,PRIMARY KEY (`id`),KEY `status` (`status`),KEY `due_at` (`due_at`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;";
 $queries[]="CREATE TABLE IF NOT EXISTS `{$p}sccc_recordings` (`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,`call_id` INT UNSIGNED NULL,`twilio_recording_sid` VARCHAR(64) NULL,`recording_url` VARCHAR(500) NOT NULL,`duration` INT UNSIGNED NOT NULL DEFAULT 0,`channels` INT NOT NULL DEFAULT 1,`created_at` DATETIME NOT NULL,PRIMARY KEY (`id`),KEY `call_id` (`call_id`),KEY `twilio_recording_sid` (`twilio_recording_sid`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;";
 $queries[]="CREATE TABLE IF NOT EXISTS `{$p}sccc_dispositions` (`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,`name` VARCHAR(100) NOT NULL,`slug` VARCHAR(100) NOT NULL,`is_success` TINYINT(1) NOT NULL DEFAULT 0,`creates_lead` TINYINT(1) NOT NULL DEFAULT 0,`do_not_call` TINYINT(1) NOT NULL DEFAULT 0,`active` TINYINT(1) NOT NULL DEFAULT 1,`sort_order` INT NOT NULL DEFAULT 0,PRIMARY KEY (`id`),UNIQUE KEY `slug` (`slug`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;";
 $queries[]="CREATE TABLE IF NOT EXISTS `{$p}sccc_ai_agents` (`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,`name` VARCHAR(191) NOT NULL,`provider` VARCHAR(80) NOT NULL DEFAULT 'generic_stream',`websocket_url` VARCHAR(500) NULL,`webhook_url` VARCHAR(500) NULL,`system_prompt` LONGTEXT NULL,`voice_name` VARCHAR(100) NULL,`active` TINYINT(1) NOT NULL DEFAULT 1,`created_by` INT UNSIGNED NOT NULL,`created_at` DATETIME NOT NULL,`updated_at` DATETIME NULL,PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;";
 foreach($queries as $q){ $CI->db->query($q); }
 $defaults=['interested'=>['Interested',1,1,0],'new_lead'=>['New Lead',1,1,0],'appointment'=>['Appointment Scheduled',1,0,0],'estimate'=>['Estimate Requested',1,0,0],'callback'=>['Callback Requested',0,0,0],'no_answer'=>['No Answer',0,0,0],'busy'=>['Busy',0,0,0],'voicemail'=>['Voicemail',0,0,0],'wrong_number'=>['Wrong Number',0,0,1],'not_interested'=>['Not Interested',0,0,0],'do_not_call'=>['Do Not Call',0,0,1],'converted'=>['Sale / Converted',1,0,0],'follow_up'=>['Follow-Up Needed',0,0,0],'failed'=>['Failed',0,0,0]];
 $n=0; foreach($defaults as $slug=>$d){ if(!$CI->db->where('slug',$slug)->get($p.'sccc_dispositions')->row()){ $CI->db->insert($p.'sccc_dispositions',['name'=>$d[0],'slug'=>$slug,'is_success'=>$d[1],'creates_lead'=>$d[2],'do_not_call'=>$d[3],'sort_order'=>++$n]); } }
 $opts=['sccc_twilio_account_sid'=>'','sccc_twilio_auth_token'=>'','sccc_twiml_app_sid'=>'','sccc_api_key_sid'=>'','sccc_api_key_secret'=>'','sccc_main_number'=>'','sccc_outbound_caller_id'=>'','sccc_default_country'=>'US','sccc_default_timezone'=>'America/New_York','sccc_record_calls'=>'1','sccc_recording_announcement'=>'0','sccc_main_greeting_id'=>'0','sccc_after_hours_greeting_id'=>'0','sccc_business_start'=>'08:00','sccc_business_end'=>'18:00','sccc_dialpad_color'=>'#16a34a','sccc_dialpad_key_color'=>'#f8fafc','sccc_dialpad_text_color'=>'#0f172a','sccc_enable_callbacks'=>'1','sccc_callback_key'=>'2','sccc_directory_key'=>'9','sccc_operator_key'=>'0','sccc_operator_extension'=>'','sccc_ai_enabled'=>'0','sccc_ai_provider'=>'generic_stream','sccc_ai_api_key'=>'','sccc_ai_websocket_url'=>'','sccc_max_campaign_cps'=>'1','sccc_call_retention_days'=>'365','sccc_allow_download_recordings'=>'1'];
 foreach($opts as $k=>$v){ add_option($k,$v); }
 $dir=FCPATH.'uploads/smart_choice_call_center/greetings/'; if(!is_dir($dir)) @mkdir($dir,0755,true);
}
