<?php
defined('BASEPATH') or exit('No direct script access allowed');
class Migration_Version_132 extends App_module_migration
{
    public function up()
    {
        $CI=&get_instance(); $books=db_prefix().'wiki_books'; $articles=db_prefix().'wiki_articles';
        if($CI->db->table_exists($books)){
            if(!$CI->db->field_exists('cover_image',$books)) $CI->db->query("ALTER TABLE `{$books}` ADD `cover_image` VARCHAR(500) NULL DEFAULT NULL AFTER `short_description`");
            if(!$CI->db->field_exists('area_type',$books)) $CI->db->query("ALTER TABLE `{$books}` ADD `area_type` VARCHAR(30) NOT NULL DEFAULT 'crm' AFTER `customer_visible`");
            if(!$CI->db->field_exists('area_label',$books)) $CI->db->query("ALTER TABLE `{$books}` ADD `area_label` VARCHAR(100) NULL DEFAULT NULL AFTER `area_type`");
            $CI->db->query("UPDATE `{$books}` SET area_type=IF(customer_visible=1,'customer','crm'), area_label=IF(customer_visible=1,'Customer Area','CRM Center') WHERE area_label IS NULL OR area_label=''");
        }
        add_option('training_manual_internal_area_label','CRM Center');
        $seed=[
          ['Warranty','Understand labor and material warranty coverage, exclusions, and claim steps.','Warranty Coverage',"<div class='sc-cover'><span class='sc-kicker'>Customer Guide</span><h2>Warranty Coverage</h2><p>Smart Choice Contractors USA normally provides a one-year workmanship warranty unless the written contract states otherwise. Material warranties are provided by the manufacturer and vary by product.</p></div><h2>What Is Covered</h2><ul><li>Defects caused by covered workmanship during the stated labor-warranty period.</li><li>Eligible material defects according to the manufacturer warranty.</li></ul><h2>What Is Not Covered</h2><p>Warranty coverage does not include normal wear, misuse, lack of maintenance, unauthorized alterations, or acts of God, including hurricanes, tropical storms, high winds, flooding, lightning, fire, or other events outside the contractor's control.</p><h2>Requesting Service</h2><p>Contact Smart Choice promptly, provide photos and project information, and allow reasonable access for inspection.</p>"],
          ['Our Project Process','Follow the project from the first call through planning, permits, material delivery, construction, and completion.','How Our Project Process Works',"<div class='sc-cover'><span class='sc-kicker'>Project Roadmap</span><h2>From First Call to Completion</h2></div><div class='sc-step'><span class='sc-step-number'>1</span><div><strong>Call and appointment:</strong> We discuss the project and schedule a site visit.</div></div><div class='sc-step'><span class='sc-step-number'>2</span><div><strong>Site visit:</strong> We inspect, measure, clarify goals, and identify conditions.</div></div><div class='sc-step'><span class='sc-step-number'>3</span><div><strong>Estimate and drawings:</strong> We schedule delivery of the estimate and prepare drawings when required.</div></div><div class='sc-step'><span class='sc-step-number'>4</span><div><strong>Permitting:</strong> Required applications, plans, reviews, and approvals are completed.</div></div><div class='sc-step'><span class='sc-step-number'>5</span><div><strong>Scheduling:</strong> The approved project is placed on the production schedule.</div></div><div class='sc-step'><span class='sc-step-number'>6</span><div><strong>Materials and construction:</strong> Materials are ordered or delivered and work begins.</div></div>"],
          ['Smart Material Shopping','Learn how managed retail and distributor accounts help us search for suitable materials and competitive pricing.','How We Shop for Project Materials',"<div class='sc-cover'><span class='sc-kicker'>Material Purchasing</span><h2>Buying Smart Without Sacrificing Quality</h2></div><p>We compare availability, specifications, lead times, warranties, delivery costs, and pricing before purchasing. Depending on the project, we may use managed accounts or supplier relationships with Home Depot, Lowe's, ABC Supply, Beacon Building Products, Town & Country Industries, Suncoast Building Sales, Gulfeagle Supply, Builders FirstSource, Ferguson, Floor & Decor, local lumberyards, specialty distributors, and manufacturer-authorized suppliers.</p><div class='sc-note'>The selected source depends on project requirements, approved materials, availability, location, and delivery schedule. The lowest price is not automatically the best value when quality or compatibility would be reduced.</div>"],
          ['Five-Year Project Records','Learn what project documents we normally retain and how to request copies.','Your Project Records',"<div class='sc-cover'><span class='sc-kicker'>Record Retention</span><h2>Project Information Kept for Five Years</h2></div><p>Smart Choice Contractors USA normally retains project records for approximately five years, subject to applicable law, system availability, and the written agreement.</p><h2>Records May Include</h2><ul><li>Estimates, proposals, contracts, invoices, and payment records.</li><li>Project photographs and uploaded documents.</li><li>Financing-related records maintained in the project file.</li><li>Change orders, communications, selections, and completion documents.</li></ul><p>Customers may request available copies through the client portal or by contacting the office. Some third-party records may remain subject to the provider's own retention rules.</p>"],
          ['Reviews and Future Savings','Understand why honest reviews matter and how they may help with future-project promotions.','Why Your Review Matters',"<div class='sc-cover'><span class='sc-kicker'>Customer Feedback</span><h2>Help Other Customers Make a Smart Choice</h2></div><p>An honest review tells future customers what went well, what could improve, and what they can expect when selecting a contractor. Reviews help local homeowners compare companies and make informed decisions.</p><h2>Why Reviews Are Important</h2><ul><li>They recognize employees and trade partners who delivered good service.</li><li>They help us improve our process and customer communication.</li><li>They give other homeowners real project experience to consider.</li><li>They strengthen our ability to serve the local market.</li></ul><p>Customers who leave an honest review may become eligible for future-project promotions or discounts when offered. A positive review is never required, and any promotion is subject to its written terms.</p>"],
        ];
        foreach($seed as $row){
            $existing=$CI->db->where('name',$row[0])->get($books)->row();
            if(!$existing){$CI->db->insert($books,['name'=>$row[0],'short_description'=>$row[1],'customer_visible'=>1,'area_type'=>'customer','area_label'=>'Customer Area','assign_type'=>'specific_staff','assign_ids'=>'','author_id'=>0]);$bid=$CI->db->insert_id();}else{$bid=$existing->id;}
            if(!$CI->db->where('book_id',$bid)->where('title',$row[2])->get($articles)->row()){
                $data=['title'=>$row[2],'description'=>$row[1],'content'=>$row[3],'is_publish'=>1,'author_id'=>0,'book_id'=>$bid,'slug'=>url_title($row[2],'-',true),'type'=>'document'];
                foreach(['visibility'=>'public','audience'=>'customer_portal','content_kind'=>'article','language_code'=>'en','style_preset'=>'smart_choice'] as $k=>$v){if($CI->db->field_exists($k,$articles))$data[$k]=$v;}
                $CI->db->insert($articles,$data);
            }
        }
    }
    public function down() { }
}
