<?php defined('BASEPATH') or exit('No direct script access allowed'); init_head(); ?>
<div id="wrapper"><div class="content"><div class="panel_s"><div class="panel-body">
<?php $this->load->view('usi_smartchoice_seo/partials/top'); ?>
<div class="sc-toolbar"><h4><i class="fa fa-database"></i> <?php echo html_escape($title); ?></h4><div class="sc-toolbar-actions"><a class="btn btn-success btn-sm" href="<?php echo admin_url('usi_smartchoice_seo/rebuild_price_index'); ?>"><i class="fa fa-refresh"></i> Learn From CRM Estimates</a><a class="btn btn-default btn-sm" href="<?php echo admin_url('usi_smartchoice_seo/export/price_index'); ?>"><i class="fa fa-download"></i> Export</a><a class="btn btn-default btn-sm" href="<?php echo admin_url('usi_smartchoice_seo/pricing_engine'); ?>"><i class="fa fa-repeat"></i> Reload</a></div></div>
<div class="row">
  <div class="col-md-4"><div class="sc-card"><div class="sc-card-count"><?php echo (int)$counts['rows']; ?></div><div class="sc-card-label">Indexed Line Items</div></div></div>
  <div class="col-md-4"><div class="sc-card"><div class="sc-card-count"><?php echo (int)$counts['crm_estimates']; ?></div><div class="sc-card-label">CRM Estimate Sources</div></div></div>
  <div class="col-md-4"><div class="sc-card"><div class="sc-card-count"><?php echo (int)$counts['services']; ?></div><div class="sc-card-label">Service Groups</div></div></div>
</div>
<form method="get" class="sc-filter"><div class="row"><div class="col-md-4"><input type="text" name="search" class="form-control" placeholder="Search service, description, unit, or city" value="<?php echo html_escape($filters['search'] ?? ''); ?>"></div><div class="col-md-3"><input type="number" name="source_id" class="form-control" placeholder="CRM Estimate ID" value="<?php echo html_escape($filters['source_id'] ?? ''); ?>"></div><div class="col-md-3"><button class="btn btn-primary btn-sm" type="submit">Filter</button> <a class="btn btn-default btn-sm" href="<?php echo admin_url('usi_smartchoice_seo/pricing_engine'); ?>">Clear</a></div></div></form>
<div class="table-responsive"><table class="table table-striped table-condensed sc-table sc-pricing-table"><thead><tr><th class="sc-col-id">ID</th><th class="sc-left">Service</th><th class="sc-left sc-col-description">Description</th><th class="sc-col-qty">Qty</th><th class="sc-col-unit">Unit</th><th class="sc-col-money">Rate</th><th class="sc-col-money">Total</th><th class="sc-col-source">Source Estimate</th><th class="sc-col-confidence">Confidence</th></tr></thead><tbody>
<?php foreach ($price_rows as $row) { ?><tr><td><?php echo (int)$row['id']; ?></td><td class="sc-left"><?php echo html_escape($row['service_keyword']); ?></td><td class="sc-left"><?php echo html_escape($row['description']); ?></td><td><?php echo html_escape($row['quantity']); ?></td><td><?php echo html_escape($row['unit']); ?></td><td><?php echo app_format_money((float)$row['unit_rate'], get_base_currency()); ?></td><td><?php echo app_format_money((float)$row['line_total'], get_base_currency()); ?></td><td>#<?php echo (int)$row['source_id']; ?></td><td><?php echo html_escape($row['confidence']); ?>%</td></tr><?php } ?>
<?php if (empty($price_rows)) { ?><tr><td colspan="9" class="text-center text-muted">No pricing rows found. Click Learn From CRM Estimates first.</td></tr><?php } ?>
</tbody></table></div>
<div class="alert alert-info mtop15"><strong>How this works:</strong> Sammy AI reads historical Perfex estimate line items, groups them by construction service, then uses the closest matching rows when you click Calculate Numbers on an AI Estimate.</div>
</div></div></div></div><?php init_tail(); ?>
