<?php defined('BASEPATH') or exit('No direct script access allowed'); init_head(); ?>
<div id="wrapper"><div class="content usi-seo"><div class="panel_s"><div class="panel-body">
<?php $this->load->view('usi_smartchoice_seo/partials/top'); ?>
<div class="sc-toolbar"><h4><i class="fa fa-calculator"></i> <?php echo html_escape($title); ?></h4><div class="sc-toolbar-actions"><a class="btn btn-primary btn-sm" href="<?php echo admin_url('usi_smartchoice_seo/ai_estimate'); ?>">New Estimate</a><a class="btn btn-info btn-sm" href="<?php echo admin_url('usi_smartchoice_seo/estimate_review_queue'); ?>">Estimate Review</a><a class="btn btn-success btn-sm" href="<?php echo admin_url('usi_smartchoice_seo/rebuild_price_index'); ?>">Learn From CRM Estimates</a><a class="btn btn-default btn-sm" href="<?php echo admin_url('usi_smartchoice_seo/pricing_engine'); ?>">Pricing Engine</a><a class="btn btn-default btn-sm" href="<?php echo admin_url('usi_smartchoice_seo/sample_header/ai_estimates'); ?>">Sample Header</a><a class="btn btn-default btn-sm" href="<?php echo admin_url('usi_smartchoice_seo/export/ai_estimates'); ?>">Export</a><a class="btn btn-default btn-sm" href="<?php echo admin_url('usi_smartchoice_seo/ai_estimates'); ?>">Reload</a></div></div>
<form method="get" class="sc-filter"><input type="text" name="search" class="form-control" placeholder="Filter title, location, scope, or status" value="<?php echo html_escape($filters['search'] ?? ''); ?>"></form>
<?php echo form_open(admin_url('usi_smartchoice_seo/mass_delete_ai_estimates')); ?><div class="table-responsive"><table class="table table-striped table-condensed sc-table sc-estimates-table"><thead><tr><th class="sc-col-check"><input type="checkbox" class="sc-check-all"></th><th class="sc-left">Title</th><th class="sc-left">Location</th><th class="sc-left">Status</th><th class="sc-left sc-col-total">Total</th><th class="sc-left">CRM Links</th><th class="sc-left sc-col-date">Created</th><th class="sc-actions-col">Actions</th></tr></thead><tbody>
<?php foreach ($estimates as $row) { ?><tr><td><input type="checkbox" name="ids[]" value="<?php echo (int)$row['id']; ?>"></td><td class="sc-left"><strong><?php echo html_escape($row['title']); ?></strong></td><td class="sc-left"><?php echo html_escape($row['location']); ?></td><td class="sc-left"><?php echo html_escape(ucwords(str_replace('_',' ', $row['status']))); ?></td><td class="sc-left"><?php echo app_format_money((float)$row['total'], get_base_currency()); ?></td><td class="sc-left">Customer <?php echo (int)$row['customer_id']; ?> / Lead <?php echo (int)$row['lead_id']; ?> / Project <?php echo (int)$row['project_id']; ?></td><td class="sc-left"><?php echo html_escape($row['created_at']); ?></td><td class="sc-actions-col"><a class="btn btn-info btn-xs" href="<?php echo admin_url('usi_smartchoice_seo/estimate_review/' . (int)$row['id']); ?>">Review</a> <a class="btn btn-default btn-xs" href="<?php echo admin_url('usi_smartchoice_seo/view_ai_estimate/' . (int)$row['id']); ?>">View</a> <a class="btn btn-default btn-xs" href="<?php echo admin_url('usi_smartchoice_seo/ai_estimate/' . (int)$row['id']); ?>">Edit</a> <a class="btn btn-danger btn-xs _delete" href="<?php echo admin_url('usi_smartchoice_seo/delete_ai_estimate/' . (int)$row['id']); ?>">Delete</a></td></tr><?php } ?>
<?php if (empty($estimates)) { ?><tr><td colspan="8" class="text-center text-muted">No AI estimates found.</td></tr><?php } ?>
</tbody></table></div><button type="submit" class="btn btn-danger btn-sm">Mass Delete</button><?php echo form_close(); ?>
</div></div></div></div><?php init_tail(); ?>
