<?php defined('BASEPATH') or exit('No direct script access allowed'); init_head(); ?>
<div id="wrapper"><div class="content"><div class="panel_s"><div class="panel-body">
<?php $this->load->view('usi_smartchoice_seo/partials/top'); ?>
<div class="sc-toolbar"><h4><i class="fa fa-check-square-o"></i> <?php echo html_escape($title); ?></h4><div class="sc-toolbar-actions"><a class="btn btn-primary btn-sm" href="<?php echo admin_url('usi_smartchoice_seo/ai_estimate'); ?>">New AI Estimate</a><a class="btn btn-success btn-sm" href="<?php echo admin_url('usi_smartchoice_seo/rebuild_price_index'); ?>">Learn From CRM Estimates</a><a class="btn btn-default btn-sm" href="<?php echo admin_url('usi_smartchoice_seo/estimate_review_queue'); ?>">Reload</a></div></div>
<form method="get" class="sc-filter row"><div class="col-md-8"><input type="text" name="search" class="form-control" placeholder="Filter title, location, scope, or status" value="<?php echo html_escape($filters['search'] ?? ''); ?>"></div><div class="col-md-3"><select name="review_status" class="form-control"><option value="">All Review Statuses</option><?php foreach (['draft','in_review','needs_revision','approved'] as $status) { ?><option value="<?php echo html_escape($status); ?>" <?php echo (($filters['review_status'] ?? '') === $status) ? 'selected' : ''; ?>><?php echo ucwords(str_replace('_',' ',$status)); ?></option><?php } ?></select></div><div class="col-md-1"><button class="btn btn-default btn-block" type="submit">Filter</button></div></form>
<div class="table-responsive"><table class="table table-striped table-condensed sc-table"><thead><tr><th>ID</th><th>Title</th><th>Location</th><th>Status</th><th>Review</th><th>Total</th><th>Confidence</th><th>Field Verified</th><th>Updated</th><th class="text-center">Actions</th></tr></thead><tbody>
<?php foreach ($estimates as $row) { ?><tr><td><?php echo (int)$row['id']; ?></td><td><?php echo html_escape($row['title']); ?></td><td><?php echo html_escape($row['location']); ?></td><td><?php echo html_escape($row['status']); ?></td><td><?php echo html_escape($row['review_status'] ?? 'draft'); ?></td><td><?php echo app_format_money((float)$row['total'], get_base_currency()); ?></td><td><?php echo html_escape((string)($row['pricing_confidence'] ?? '0')); ?>%</td><td><?php echo !empty($row['field_verified']) ? 'Yes' : 'No'; ?></td><td><?php echo html_escape($row['updated_at']); ?></td><td class="text-center"><a class="btn btn-info btn-xs" href="<?php echo admin_url('usi_smartchoice_seo/estimate_review/' . (int)$row['id']); ?>">Review</a> <a class="btn btn-default btn-xs" href="<?php echo admin_url('usi_smartchoice_seo/view_ai_estimate/' . (int)$row['id']); ?>">View</a></td></tr><?php } ?>
<?php if (empty($estimates)) { ?><tr><td colspan="10" class="text-center text-muted">No AI estimates found for review.</td></tr><?php } ?>
</tbody></table></div>
</div></div></div></div><?php init_tail(); ?>
