<?php defined('BASEPATH') or exit('No direct script access allowed'); ?>
<?php init_head(); ?>
<div id="wrapper"><div class="content solar-pro-shell"><?php $this->load->view('admin/_module_nav'); ?><div class="solar-hero compact"><div><h1><?php echo _l('solar_pro_analyses'); ?></h1><p><?php echo _l('solar_pro_analyses_subtitle'); ?></p></div><a class="btn solar-btn-primary" href="<?php echo admin_url('solar_pro/analysis'); ?>"><i class="fa fa-plus"></i> <?php echo _l('solar_pro_new_analysis'); ?></a></div>
<div class="panel_s solar-card"><div class="panel-body"><div class="solar-toolbar"><input class="form-control" id="solar-table-search" placeholder="<?php echo html_escape(_l('solar_pro_search')); ?>"><button type="button" class="btn btn-default" data-solar-export="#solar-analyses-table"><i class="fa fa-download"></i> <?php echo _l('solar_pro_export'); ?></button><a class="btn btn-default" href="<?php echo admin_url('solar_pro/analyses'); ?>"><i class="fa fa-refresh"></i> <?php echo _l('solar_pro_reload'); ?></a></div>
<?php echo form_open(admin_url('solar_pro/mass_delete'),['id'=>'solar-mass-delete-form']); ?>
<div class="table-responsive"><table class="table table-hover solar-filter-table" id="solar-analyses-table"><thead><tr><th><input type="checkbox" data-solar-check-all></th><th>ID</th><th><?php echo _l('solar_pro_customer'); ?></th><th><?php echo _l('solar_pro_address'); ?></th><th><?php echo _l('solar_pro_system_size'); ?></th><th><?php echo _l('solar_pro_panels'); ?></th><th><?php echo _l('solar_pro_production'); ?></th><th><?php echo _l('solar_pro_savings'); ?></th><th><?php echo _l('solar_pro_status'); ?></th><th><?php echo _l('solar_pro_actions'); ?></th></tr></thead><tbody>
<?php foreach($analyses as $a): ?><tr><td><input type="checkbox" name="ids[]" value="<?php echo $a['id']; ?>" class="solar-row-check"></td><td><?php echo $a['id']; ?></td><td><?php echo html_escape(trim($a['first_name'].' '.$a['last_name'])); ?></td><td><?php echo html_escape($a['address']); ?></td><td><?php echo number_format($a['system_kw'],3); ?> kW</td><td><?php echo (int)$a['panel_count']; ?></td><td><?php echo number_format($a['annual_production_kwh']); ?> kWh</td><td><?php echo app_format_money($a['year1_savings'],get_base_currency()); ?></td><td><span class="label label-info"><?php echo html_escape($a['status']); ?></span></td><td><a class="btn btn-xs btn-default" href="<?php echo admin_url('solar_pro/analysis/'.$a['id']); ?>"><i class="fa fa-eye"></i></a> <?php if(is_admin()||staff_can('delete','solar_pro')): ?><a class="btn btn-xs btn-danger _delete" href="<?php echo admin_url('solar_pro/delete_analysis/'.$a['id']); ?>"><i class="fa fa-trash"></i></a><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div>
<?php if(is_admin()||staff_can('delete','solar_pro')): ?><button type="submit" class="btn btn-danger btn-sm"><i class="fa fa-trash"></i> <?php echo _l('solar_pro_mass_delete'); ?></button><?php endif; ?>
<?php echo form_close(); ?></div></div></div></div>
<?php init_tail(); ?>
