<?php defined('BASEPATH') or exit('No direct script access allowed'); ?>
<?php init_head(); ?>
<div id="wrapper"><div class="content solar-pro-shell"><?php $this->load->view('admin/_module_nav'); ?>
<div class="solar-hero compact"><div><span class="solar-kicker"><?php echo _l('solar_pro_design_engine'); ?></span><h1><?php echo _l('solar_pro_new_analysis'); ?></h1><p><?php echo _l('solar_pro_calculator_subtitle'); ?></p></div></div>
<?php echo form_open(admin_url('solar_pro/calculate'), ['id'=>'solar-pro-analysis-form']); ?>
<div class="row">
<div class="col-md-8"><div class="panel_s solar-card"><div class="panel-body">
<h4 class="solar-section-title"><i class="fa fa-home"></i> <?php echo _l('solar_pro_property_customer'); ?></h4>
<div class="row"><div class="col-md-6"><?php echo render_input('first_name','solar_pro_first_name'); ?></div><div class="col-md-6"><?php echo render_input('last_name','solar_pro_last_name'); ?></div></div>
<div class="row"><div class="col-md-6"><?php echo render_input('email','solar_pro_email','', 'email'); ?></div><div class="col-md-6"><?php echo render_input('phone','solar_pro_phone'); ?></div></div>
<?php echo render_input('address','solar_pro_address','','text',['required'=>true]); ?>
<div class="row"><div class="col-md-5"><?php echo render_input('city','solar_pro_city'); ?></div><div class="col-md-3"><?php echo render_input('state','solar_pro_state',solar_pro_setting('solar_pro_default_state','FL')); ?></div><div class="col-md-4"><?php echo render_input('zip','solar_pro_zip'); ?></div></div>
<input type="hidden" name="latitude" id="latitude"><input type="hidden" name="longitude" id="longitude">
<hr><h4 class="solar-section-title"><i class="fa fa-bolt"></i> <?php echo _l('solar_pro_energy_profile'); ?></h4>
<div class="row"><div class="col-md-6"><?php echo render_input('annual_consumption_kwh','solar_pro_annual_consumption_kwh','','number',['required'=>true,'min'=>'1','step'=>'0.01']); ?></div><div class="col-md-6"><?php echo render_input('average_monthly_bill','solar_pro_average_monthly_bill','','number',['min'=>'0','step'=>'0.01']); ?></div></div>
<div class="row"><div class="col-md-6"><div class="form-group"><label><?php echo _l('solar_pro_utility'); ?></label><select name="utility_id" class="form-control selectpicker" data-live-search="true"><option value=""><?php echo _l('solar_pro_select_utility'); ?></option><?php foreach($utilities as $u): ?><option value="<?php echo $u['id']; ?>"><?php echo html_escape($u['name']); ?></option><?php endforeach; ?></select></div></div>
<div class="col-md-6"><div class="form-group"><label><?php echo _l('solar_pro_rate_plan'); ?></label><select name="utility_rate_id" class="form-control selectpicker" data-live-search="true"><option value=""><?php echo _l('solar_pro_use_default_rate'); ?></option><?php foreach($rates as $r): ?><option value="<?php echo $r['id']; ?>"><?php echo html_escape($r['rate_name']); ?></option><?php endforeach; ?></select></div></div></div>
<hr><h4 class="solar-section-title"><i class="fa fa-cogs"></i> <?php echo _l('solar_pro_system_equipment'); ?></h4>
<div class="row"><div class="col-md-4"><div class="form-group"><label><?php echo _l('solar_pro_panel'); ?></label><select name="panel_equipment_id" id="panel_equipment_id" class="form-control selectpicker"><?php foreach($panels as $p): ?><option value="<?php echo $p['id']; ?>" data-watts="<?php echo (float)$p['watts']; ?>" <?php echo (int)$p['watts']==(int)solar_pro_setting('solar_pro_default_panel_watts',440)?'selected':''; ?>><?php echo html_escape($p['manufacturer'].' '.$p['model']); ?></option><?php endforeach; ?></select><input type="hidden" name="panel_watts" id="panel_watts" value="<?php echo html_escape(solar_pro_setting('solar_pro_default_panel_watts','440')); ?>"></div></div>
<div class="col-md-4"><div class="form-group"><label><?php echo _l('solar_pro_microinverter'); ?></label><select name="inverter_equipment_id" class="form-control selectpicker"><option value=""><?php echo _l('solar_pro_select'); ?></option><?php foreach($inverters as $i): ?><option value="<?php echo $i['id']; ?>"><?php echo html_escape($i['manufacturer'].' '.$i['model']); ?></option><?php endforeach; ?></select></div></div>
<div class="col-md-4"><div class="solar-assumption-box"><span><?php echo _l('solar_pro_installed_price_per_panel'); ?></span><strong><?php echo app_format_money((float)solar_pro_setting('solar_pro_price_per_panel',1800),get_base_currency()); ?></strong></div></div></div>
</div></div></div>
<div class="col-md-4"><div class="panel_s solar-card sticky"><div class="panel-body"><h4><?php echo _l('solar_pro_analysis_methods'); ?></h4>
<label class="solar-method solar-method-choice"><input type="radio" name="analysis_method" value="google_solar" checked><i class="fa fa-google"></i><div><strong><?php echo _l('solar_pro_google_solar'); ?></strong><p><?php echo _l('solar_pro_google_method_desc'); ?></p></div></label>
<label class="solar-method solar-method-choice"><input type="radio" name="analysis_method" value="quick_estimate"><i class="fa fa-calculator"></i><div><strong><?php echo _l('solar_pro_quick_estimate'); ?></strong><p><?php echo _l('solar_pro_fallback_method_desc'); ?></p></div></label>
<div class="panel_s solar-card"><div class="panel-body"><h4><?php echo _l('solar_pro_contract_optional'); ?></h4><div class="checkbox checkbox-primary"><input type="checkbox" name="create_contract" value="1" id="create_contract"><label for="create_contract"><?php echo _l('solar_pro_create_contract_after_analysis'); ?></label></div><div class="form-group"><label><?php echo _l('solar_pro_template'); ?></label><select name="contract_template_id" class="selectpicker" data-width="100%"><option value=""></option><?php foreach(($contract_templates??[]) as $t): ?><option value="<?php echo $t['id']; ?>"><?php echo html_escape($t['name']); ?></option><?php endforeach; ?></select></div></div></div><button type="submit" class="btn solar-btn-primary btn-block"><i class="fa fa-sun-o"></i> <?php echo _l('solar_pro_analyze_property'); ?></button>
<p class="solar-disclaimer"><?php echo _l('solar_pro_estimate_disclaimer'); ?></p>
</div></div></div>
</div><?php echo form_close(); ?></div></div>
<?php init_tail(); ?>
