<?php defined('BASEPATH') or exit('No direct script access allowed'); ?>
<?php init_head(); ?>
<div id="wrapper"><div class="content solar-pro-shell"><?php $this->load->view('admin/_module_nav'); ?>
<div class="solar-hero"><div><span class="solar-kicker"><?php echo strtoupper(html_escape($analysis['analysis_source'])); ?></span><h1><?php echo _l('solar_pro_analysis_report'); ?> #<?php echo $analysis['id']; ?></h1><p><?php echo html_escape($analysis['address'].', '.$analysis['city'].', '.$analysis['state'].' '.$analysis['zip']); ?></p></div><div class="solar-actions"><a class="btn btn-default" href="<?php echo admin_url('solar_pro/analysis_pdf/'.$analysis['id']); ?>"><i class="fa fa-file-pdf-o"></i> <?php echo _l('solar_pro_download_pdf'); ?></a><a target="_blank" class="btn btn-default" href="<?php echo site_url('solar_pro/portal/'.$analysis['public_token']); ?>"><i class="fa fa-external-link"></i> <?php echo _l('solar_pro_customer_view'); ?></a><?php if(empty($analysis['lead_id']) && (is_admin()||staff_can('edit','solar_pro'))): ?><a class="btn btn-default" href="<?php echo admin_url('solar_pro/create_lead/'.$analysis['id']); ?>"><i class="fa fa-user-plus"></i> <?php echo _l('solar_pro_create_lead'); ?></a><?php endif; ?><?php if(!$analysis['proposal'] && (is_admin()||staff_can('create','solar_pro'))): ?><a class="btn btn-default" href="<?php echo admin_url('solar_pro/create_proposal/'.$analysis['id']); ?>"><i class="fa fa-file-invoice-dollar"></i> <?php echo _l('solar_pro_create_proposal'); ?></a><?php elseif($analysis['proposal']): ?><a class="btn btn-default" href="<?php echo admin_url('solar_pro/proposal/'.$analysis['proposal']['id']); ?>"><i class="fa fa-file-invoice-dollar"></i> <?php echo _l('solar_pro_view_proposal'); ?></a><?php endif; ?><?php if(!$analysis['contract'] && (is_admin()||staff_can('manage_contracts','solar_pro'))): ?><a class="btn solar-btn-primary" href="<?php echo admin_url('solar_pro/create_contract/'.$analysis['id']); ?>"><i class="fa fa-pencil-square-o"></i> <?php echo _l('solar_pro_create_contract'); ?></a><?php endif; ?></div></div>
<div class="row solar-stat-grid">
<div class="col-md solar-stat-card"><span><?php echo _l('solar_pro_system_size'); ?></span><strong><?php echo number_format($analysis['system_kw'],3); ?> kW</strong></div>
<div class="col-md solar-stat-card"><span><?php echo _l('solar_pro_panels'); ?></span><strong><?php echo (int)$analysis['panel_count']; ?> × <?php echo number_format($analysis['panel_watts']); ?> W</strong></div>
<div class="col-md solar-stat-card"><span><?php echo _l('solar_pro_annual_generation'); ?></span><strong><?php echo number_format($analysis['annual_production_kwh']); ?> kWh</strong></div>
<div class="col-md solar-stat-card"><span><?php echo _l('solar_pro_solar_offset'); ?></span><strong><?php echo number_format($analysis['solar_offset_pct'],1); ?>%</strong></div>
<div class="col-md solar-stat-card"><span><?php echo _l('solar_pro_system_price'); ?></span><strong><?php echo app_format_money($analysis['system_price'],get_base_currency()); ?></strong></div>
</div>
<div class="row"><div class="col-md-8"><div class="panel_s solar-card"><div class="panel-body"><h4><?php echo _l('solar_pro_monthly_energy'); ?></h4><canvas id="solar-production-chart" height="125" data-months='<?php echo html_escape(json_encode(array_values($months))); ?>' data-production='<?php echo html_escape(json_encode(array_map('floatval',array_column($analysis['monthly'],'production_kwh')))); ?>' data-consumption='<?php echo html_escape(json_encode(array_map('floatval',array_column($analysis['monthly'],'consumption_kwh')))); ?>'></canvas><div class="solar-chart-legend"><span class="production"><?php echo _l('solar_pro_production'); ?></span><span class="consumption"><?php echo _l('solar_pro_consumption'); ?></span></div></div></div></div>
<div class="col-md-4"><div class="panel_s solar-card"><div class="panel-body"><h4><?php echo _l('solar_pro_financial_snapshot'); ?></h4><div class="solar-metric"><span><?php echo _l('solar_pro_year1_savings'); ?></span><strong><?php echo app_format_money($analysis['year1_savings'],get_base_currency()); ?></strong></div><div class="solar-metric"><span><?php echo _l('solar_pro_payback'); ?></span><strong><?php echo $analysis['payback_years']!==null?number_format($analysis['payback_years'],1).' '._l('solar_pro_years'):_l('solar_pro_not_reached'); ?></strong></div><div class="solar-metric"><span><?php echo _l('solar_pro_lifetime_net_savings'); ?></span><strong><?php echo app_format_money($analysis['lifetime_savings'],get_base_currency()); ?></strong></div><div class="solar-metric"><span><?php echo _l('solar_pro_data_source'); ?></span><strong><?php echo $analysis['analysis_source']==='google_solar'?_l('solar_pro_google_solar'):_l('solar_pro_fallback_estimate'); ?></strong></div><?php if($analysis['imagery_quality']): ?><div class="solar-metric"><span><?php echo _l('solar_pro_imagery_quality'); ?></span><strong><?php echo html_escape($analysis['imagery_quality']); ?></strong></div><?php endif; ?></div></div></div></div>
<div class="panel_s solar-card"><div class="panel-body"><h4><?php echo _l('solar_pro_monthly_breakdown'); ?></h4><div class="table-responsive"><table class="table table-hover"><thead><tr><th><?php echo _l('solar_pro_month'); ?></th><th><?php echo _l('solar_pro_production'); ?></th><th><?php echo _l('solar_pro_consumption'); ?></th><th><?php echo _l('solar_pro_before_solar'); ?></th><th><?php echo _l('solar_pro_after_solar'); ?></th><th><?php echo _l('solar_pro_savings'); ?></th></tr></thead><tbody><?php foreach($analysis['monthly'] as $m): ?><tr><td><?php echo $months[(int)$m['month_number']]; ?></td><td><?php echo number_format($m['production_kwh']); ?> kWh</td><td><?php echo number_format($m['consumption_kwh']); ?> kWh</td><td><?php echo app_format_money($m['utility_cost_without_solar'],get_base_currency()); ?></td><td><?php echo app_format_money($m['utility_cost_with_solar'],get_base_currency()); ?></td><td><?php echo app_format_money($m['savings'],get_base_currency()); ?></td></tr><?php endforeach; ?></tbody></table></div></div></div>
<div class="panel_s solar-card"><div class="panel-body"><h4><?php echo _l('solar_pro_payment_savings'); ?></h4><div class="row"><div class="col-md-3"><div class="solar-metric"><span><?php echo _l('solar_pro_est_monthly_payment'); ?></span><strong><?php echo app_format_money($finance['monthly_payment'],get_base_currency()); ?></strong></div></div><div class="col-md-3"><div class="solar-metric"><span><?php echo _l('solar_pro_monthly_savings'); ?></span><strong><?php echo app_format_money($finance['monthly_savings'],get_base_currency()); ?></strong></div></div><div class="col-md-3"><div class="solar-metric"><span><?php echo _l('solar_pro_annual_savings'); ?></span><strong><?php echo app_format_money($finance['annual_savings'],get_base_currency()); ?></strong></div></div><div class="col-md-3"><div class="solar-metric"><span>APR / <?php echo _l('solar_pro_term'); ?></span><strong><?php echo number_format($finance['apr_pct'],2); ?>% / <?php echo (int)$finance['term_years']; ?>y</strong></div></div></div><div class="table-responsive"><table class="table table-bordered"><thead><tr><th>5 <?php echo _l('solar_pro_years'); ?></th><th>10 <?php echo _l('solar_pro_years'); ?></th><th>20 <?php echo _l('solar_pro_years'); ?></th><th>25 <?php echo _l('solar_pro_years'); ?></th></tr></thead><tbody><tr><?php foreach([5,10,20,25] as $yr): ?><td><?php echo app_format_money($finance['projections'][$yr],get_base_currency()); ?></td><?php endforeach; ?></tr></tbody></table></div></div></div><?php if(!empty($documents)): ?><div class="panel_s solar-card"><div class="panel-body"><h4><?php echo _l('solar_pro_customer_documents'); ?></h4><?php foreach($documents as $d): ?><a class="btn btn-default btn-sm mright5 mbot5" target="_blank" href="<?php echo site_url('solar_pro/portal/'.$analysis['public_token'].'/document/'.$d['id']); ?>"><i class="fa fa-paperclip"></i> <?php echo html_escape($d['file_name']); ?></a><?php endforeach; ?></div></div><?php endif; ?>
<?php if($analysis['contract']): ?><div class="panel_s solar-card"><div class="panel-body"><h4><?php echo _l('solar_pro_contract'); ?></h4><p><strong><?php echo html_escape($analysis['contract']['title']); ?></strong> <span class="label label-info"><?php echo html_escape($analysis['contract']['status']); ?></span></p><a target="_blank" class="btn solar-btn-primary" href="<?php echo site_url('solar_pro/portal/'.$analysis['contract']['public_token'].'/sign'); ?>"><?php echo _l('solar_pro_open_contract'); ?></a></div></div><?php endif; ?>
</div></div>
<?php init_tail(); ?>
