<?php defined('BASEPATH') or exit('No direct script access allowed'); ?>
<?php init_head(); ?>
<div id="wrapper"><div class="content solar-pro-shell"><?php $this->load->view('admin/_module_nav'); ?><div class="solar-hero compact"><div><h1><?php echo _l('solar_pro_utilities'); ?></h1><p><?php echo _l('solar_pro_utilities_subtitle'); ?></p></div></div>
<div class="row"><div class="col-md-4"><div class="panel_s solar-card"><div class="panel-body"><h4><?php echo _l('solar_pro_add_utility'); ?></h4><?php echo form_open(admin_url('solar_pro/utilities')); ?><?php echo render_input('name','solar_pro_utility_name','','text',['required'=>true]); ?><?php echo render_input('short_name','solar_pro_short_name'); ?><?php echo render_input('service_area','solar_pro_service_area'); ?><?php echo render_input('website','solar_pro_website','','url'); ?><button class="btn solar-btn-primary" type="submit"><?php echo _l('solar_pro_save'); ?></button><?php echo form_close(); ?></div></div></div>
<div class="col-md-8"><div class="panel_s solar-card"><div class="panel-body"><h4><?php echo _l('solar_pro_add_rate_plan'); ?></h4><?php echo form_open(admin_url('solar_pro/save_rate')); ?><div class="row"><div class="col-md-6"><label><?php echo _l('solar_pro_utility'); ?></label><select class="form-control selectpicker" name="utility_id" required><?php foreach($utilities as $u): ?><option value="<?php echo $u['id']; ?>"><?php echo html_escape($u['name']); ?></option><?php endforeach; ?></select></div><div class="col-md-6"><?php echo render_input('rate_name','solar_pro_rate_name','','text',['required'=>true]); ?></div></div>
<div class="row"><div class="col-md-4"><?php echo render_date_input('effective_date','solar_pro_effective_date'); ?></div><div class="col-md-4"><?php echo render_input('customer_charge','solar_pro_customer_charge','0','number',['step'=>'0.0001']); ?></div><div class="col-md-4"><?php echo render_input('minimum_bill','solar_pro_minimum_bill','0','number',['step'=>'0.0001']); ?></div></div>
<div class="row"><div class="col-md-4"><?php echo render_input('energy_rate','solar_pro_energy_rate','0','number',['step'=>'0.000001']); ?></div><div class="col-md-4"><?php echo render_input('fuel_rate','solar_pro_fuel_rate','0','number',['step'=>'0.000001']); ?></div><div class="col-md-4"><?php echo render_input('export_credit_rate','solar_pro_export_credit','0','number',['step'=>'0.000001']); ?></div></div>
<div class="row"><div class="col-md-3"><?php echo render_input('storm_charge','solar_pro_storm_charge','0','number',['step'=>'0.0001']); ?></div><div class="col-md-3"><?php echo render_input('gross_receipts_pct','solar_pro_gross_receipts_pct','0','number',['step'=>'0.0001']); ?></div><div class="col-md-3"><?php echo render_input('utility_tax_pct','solar_pro_utility_tax_pct','0','number',['step'=>'0.0001']); ?></div><div class="col-md-3"><?php echo render_input('sales_tax_pct','solar_pro_sales_tax_pct','0','number',['step'=>'0.0001']); ?></div></div>
<input type="hidden" name="other_monthly_charge" value="0"><div class="checkbox checkbox-primary"><input type="checkbox" name="net_metering" id="net_metering" value="1" checked><label for="net_metering"><?php echo _l('solar_pro_net_metering'); ?></label></div><?php echo render_textarea('notes','solar_pro_notes'); ?><button class="btn solar-btn-primary" type="submit"><?php echo _l('solar_pro_save_rate'); ?></button><?php echo form_close(); ?></div></div></div></div>
<div class="panel_s solar-card"><div class="panel-body"><div class="solar-toolbar"><input class="form-control" id="solar-table-search" placeholder="<?php echo html_escape(_l('solar_pro_search')); ?>"><button type="button" class="btn btn-default" data-solar-export="#solar-utilities-table"><i class="fa fa-download"></i> <?php echo _l('solar_pro_export'); ?></button><a class="btn btn-default" href="<?php echo admin_url('solar_pro/utilities'); ?>"><i class="fa fa-refresh"></i> <?php echo _l('solar_pro_reload'); ?></a></div><div class="table-responsive"><table class="table table-hover solar-filter-table" id="solar-utilities-table"><thead><tr><th><?php echo _l('solar_pro_utility'); ?></th><th><?php echo _l('solar_pro_rate_name'); ?></th><th><?php echo _l('solar_pro_effective_date'); ?></th><th><?php echo _l('solar_pro_customer_charge'); ?></th><th><?php echo _l('solar_pro_energy_rate'); ?></th><th><?php echo _l('solar_pro_minimum_bill'); ?></th></tr></thead><tbody><?php foreach($rates as $r): $u=array_values(array_filter($utilities,function($x)use($r){return $x['id']==$r['utility_id'];})); ?><tr><td><?php echo html_escape($u?$u[0]['name']:''); ?></td><td><?php echo html_escape($r['rate_name']); ?></td><td><?php echo html_escape($r['effective_date']); ?></td><td><?php echo number_format($r['customer_charge'],2); ?></td><td><?php echo number_format($r['energy_rate'],6); ?></td><td><?php echo number_format($r['minimum_bill'],2); ?></td></tr><?php endforeach; ?></tbody></table></div></div></div>
</div></div><?php init_tail(); ?>
