<?php defined('BASEPATH') or exit('No direct script access allowed'); ?>
<?php init_head(); ?>
<div id="wrapper"><div class="content smart-choice-links-page"><div class="row"><div class="col-md-12">
<div class="scl-hero panel_s"><div class="panel-body"><div class="scl-hero-flex"><div><h3><i class="fa fa-book"></i> <?php echo _l('smart_choice_links_how_to_use'); ?></h3><p>This guide explains how to create, organize, display, search, troubleshoot, and safely maintain the two Smart Choice Links menus.</p></div><div class="scl-hero-actions"><a href="<?php echo admin_url('smart_choice_links'); ?>" class="btn btn-default btn-sm"><i class="fa fa-list"></i> <?php echo _l('smart_choice_links_manage'); ?></a><a href="<?php echo admin_url('smart_choice_links/settings'); ?>" class="btn btn-default btn-sm"><i class="fa fa-cog"></i> <?php echo _l('settings'); ?></a></div></div></div></div>
<div class="scl-module-tabs"><a href="<?php echo admin_url('smart_choice_links'); ?>"><i class="fa fa-list"></i> <?php echo _l('smart_choice_links_manage'); ?></a><a href="<?php echo admin_url('smart_choice_links/settings'); ?>"><i class="fa fa-cog"></i> <?php echo _l('smart_choice_links_settings'); ?></a><a href="<?php echo admin_url('smart_choice_links/help'); ?>" class="active"><i class="fa fa-question-circle"></i> <?php echo _l('smart_choice_links_how_to_use'); ?></a><a href="<?php echo admin_url('smart_choice_links/health'); ?>"><i class="fa fa-heartbeat"></i> <?php echo _l('smart_choice_links_health_check'); ?></a></div>

<div class="row">
<div class="col-md-12"><div class="scl-guide-card"><h4><i class="fa fa-info-circle"></i> What the Module Does</h4><p>Smart Choice Links places one star to the left of the CRM search bar and one star to the right. Each star opens a separate list of shortcuts. The left star is normally used for daily operations. The right star is normally used for administration, Setup, reports, training, suppliers, and management tools. The module also adds search fields to large CRM menus so employees can find a menu or module name without scrolling.</p></div></div>

<div class="col-md-6"><div class="scl-guide-card"><h4><i class="fa fa-star"></i> Left Star: Daily Work Links</h4><p>Use the left star for pages employees open repeatedly during daily work, such as Dashboard, Customers, Contacts, Leads, Estimates, Proposals, Invoices, Projects, Tasks, Calendar, Tickets, and Appointments. Keeping operational links on the left makes them faster to reach and keeps administration links separate.</p></div></div>
<div class="col-md-6"><div class="scl-guide-card"><h4><i class="fa fa-star-o"></i> Right Star: Administration Links</h4><p>Use the right star for Setup, Employees, Roles, Modules, Reports, Utilities, Media, Suppliers, Home Depot, training documents, company policies, and other management tools. A link may also be assigned to both stars when it is important to both groups.</p></div></div>

<div class="col-md-12"><div class="scl-guide-card"><h4><i class="fa fa-plus-circle"></i> Add a New Link</h4><p><strong>Step 1:</strong> Open Smart Choice Links from the CRM menu. <strong>Step 2:</strong> Click Add New Link. <strong>Step 3:</strong> enter a short title that employees will recognize. <strong>Step 4:</strong> paste the full internal or external URL. <strong>Step 5:</strong> choose Left, Right, or Both. <strong>Step 6:</strong> select an icon and category. <strong>Step 7:</strong> choose how the link opens. <strong>Step 8:</strong> select staff or role visibility when the link should be restricted. <strong>Step 9:</strong> save and test the link from the appropriate star.</p></div></div>

<div class="col-md-6"><div class="scl-guide-card"><h4><i class="fa fa-link"></i> Internal CRM Links</h4><p>For CRM pages, use the complete CRM address or a supported admin path. Examples include <code>admin/clients</code>, <code>admin/projects</code>, and <code>admin/settings</code>. Internal links should normally open in the same tab so the user remains inside the CRM.</p></div></div>
<div class="col-md-6"><div class="scl-guide-card"><h4><i class="fa fa-external-link"></i> External Links</h4><p>For external websites, enter the full address beginning with <code>https://</code>. Examples include supplier websites, permit portals, cloud documents, training websites, and vendor accounts. External links should normally open in a new tab so the CRM remains open.</p></div></div>

<div class="col-md-6"><div class="scl-guide-card"><h4><i class="fa fa-window-restore"></i> Link Opening Options</h4><p><strong>Same Tab</strong> replaces the current CRM page. <strong>New Tab</strong> opens another browser tab. <strong>Popup</strong> opens a smaller resizable window. Use Same Tab for normal CRM pages, New Tab for external websites, and Popup only for tools that work correctly in a separate window.</p></div></div>
<div class="col-md-6"><div class="scl-guide-card"><h4><i class="fa fa-users"></i> Staff and Role Visibility</h4><p>Use visibility restrictions when a shortcut contains accounting, payroll, management, legal, or administrative information. Test restricted links with a non-administrator account to confirm that only authorized employees can see them.</p></div></div>

<div class="col-md-12"><div class="scl-guide-card"><h4><i class="fa fa-sort"></i> Reorder Links</h4><p>Open the Smart Choice Links management page. Drag each row using the move handle and place the most frequently used links first. The new order is saved automatically. Keep each star organized by workflow rather than adding links randomly.</p></div></div>

<div class="col-md-6"><div class="scl-guide-card"><h4><i class="fa fa-search"></i> Main and Setup Menu Search</h4><p>The search field at the top of the main or Setup menu filters visible menu items as you type. Enter a module name or page name such as Projects, Reports, Payroll, Employees, Settings, or Utilities. Clear the field to restore the complete menu. The search does not change permissions and cannot reveal pages the employee is not allowed to access.</p></div></div>
<div class="col-md-6"><div class="scl-guide-card"><h4><i class="fa fa-sliders"></i> Popup Appearance</h4><p>Open Settings to adjust panel width, row height, icon size, font size, padding, rounded corners, and animation speed. Use moderate values so the menu remains easy to read without covering the navigation bar or extending beyond the screen.</p></div></div>

<div class="col-md-12"><div class="scl-guide-card"><h4><i class="fa fa-mouse-pointer"></i> Opening and Closing the Star Menus</h4><p>Click a star once to open its menu. Click the same star again to close it. Clicking the other star closes the first menu and opens the second. Clicking anywhere outside the menu closes it. Pressing Escape also closes an open menu. Hover labels disappear automatically when the pointer leaves the star and do not remain stuck on the screen.</p></div></div>

<div class="col-md-6"><div class="scl-guide-card"><h4><i class="fa fa-heartbeat"></i> Health Check</h4><p>Use the Health Check page after installing or upgrading the module. Verify that the database table exists, both stars are enabled, active links exist, the JavaScript and CSS files are accessible, and menu search is enabled. Correct failed checks before changing unrelated CRM files.</p></div></div>
<div class="col-md-6"><div class="scl-guide-card"><h4><i class="fa fa-refresh"></i> After an Upgrade</h4><p>Run Upgrade Database when Perfex displays the option. Clear the CRM application cache and browser cache. Then reload the dashboard with a hard refresh. Confirm one star appears on each side of the search bar, both menus open, every shortcut works, and the Setup search field appears.</p></div></div>

<div class="col-md-12"><div class="scl-guide-card"><h4><i class="fa fa-wrench"></i> Troubleshooting</h4><p><strong>Stars appear but do not open:</strong> clear the browser cache and confirm only one Smart Choice Links module folder exists. <strong>Both stars appear on one side:</strong> verify version 1.2.1 or newer and reload after clearing cached assets. <strong>A label remains visible:</strong> clear cached JavaScript and confirm version 1.2.2 is loaded. <strong>Links work on the management page but not in a star menu:</strong> verify the link is Active, assigned to the correct placement, and permitted for the logged-in employee. <strong>Setup search is missing:</strong> confirm Menu Search is enabled in Settings and that the Setup menu has fully loaded.</p></div></div>

<div class="col-md-12"><div class="scl-guide-card"><h4><i class="fa fa-shield"></i> Safe Maintenance Rules</h4><p>Do not delete the module database table when upgrading. Do not install duplicate Favorite Links or older Smart Choice Links folders at the same time. Back up the module folder and database before structural changes. Edit links through the module interface rather than directly in phpMyAdmin. Test changes with an administrator and a regular employee account.</p></div></div>
</div>
</div></div></div></div>
<?php init_tail(); ?>
