package com.divesh.perfex.leads.domain.models

data class Task(
    val STATUS: Int = 0,
    val assignees: String? = "",
    val assignees_ids: String? = "",
    val billed: Int = 0,
    val billable: Int = 0,
    val current_user_is_assigned: Int = 0,
    val current_user_is_creator: Int = 0,
    val cycles: Int = 0,
    val duedate: String? = "",
    val hourly_rate: Int = 0,
    val description: String? = "",
    val id: Int = 0,
    val custom_recurring: Int = 0,
    val is_assigned: Int = 0,
    val not_finished_timer_by_current_staff: Int = 0,
    val priority: Int = 0,
    val recurring: Int = 0,
    val recurring_type: String? = "",
    val rel_id: Int = 0,
    val rel_name: String? = "",
    val rel_type: String? = "",
    val repeat_every: Int = 0,
    val startdate: String? = "",
    val tags: String? = "",
    val task_name: String? = "",
    val total_cycles: Int = 0,
    val total_logged_time: String? = "",
    val my_logged_time: String? = "",
):java.io.Serializable