<?php defined('BASEPATH') or exit('No direct script access allowed'); ?>
<!doctype html><html lang="<?php echo html_escape(get_locale_key(get_option('active_language'))); ?>"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title><?php echo html_escape($title); ?></title>
<link rel="stylesheet" href="<?php echo module_dir_url('recruitment','assets/css/smart_choice_job_application.css'); ?>?v=1850">
</head><body><div class="sc-public-language"><a href="<?php echo current_url(); ?>?lang=english">English</a><a href="<?php echo current_url(); ?>?lang=spanish">Español</a></div>
<div class="sc-job-page"><div class="sc-job-shell"><div class="sc-job-card">
<header class="sc-job-header"><div class="sc-job-brand"><div class="sc-job-logo"><?php echo get_dark_company_logo(); ?></div><div><h1><?php echo _l('recruitment_application_title'); ?></h1><p><?php echo _l('recruitment_application_subtitle'); ?></p></div></div><div class="sc-job-badges"><span><?php echo _l('recruitment_application_badge_skilled'); ?></span><span><?php echo _l('recruitment_application_badge_field'); ?></span></div></header>
<main class="sc-job-body">
<div class="sc-job-notice"><b><?php echo _l('recruitment_application_required_notice'); ?></b></div>
<?php if (!empty($errors)): ?><div class="sc-alert sc-alert-error"><strong><?php echo _l('recruitment_application_fix_errors'); ?></strong><ul><?php foreach($errors as $error): ?><li><?php echo html_escape($error); ?></li><?php endforeach; ?></ul></div><?php endif; ?>
<?php if (!empty($success)): ?><div class="sc-success"><div class="sc-success-icon">OK</div><h2><?php echo _l('recruitment_application_success_title'); ?></h2><p><?php echo _l('recruitment_application_success_message'); ?></p></div><?php else: ?>
<?php echo form_open_multipart(current_url(), ['class'=>'sc-job-form']); ?>
<?php
function sc_field($label,$name,$type='text',$required=false,$placeholder=''){ $value=set_value($name); echo '<div class="sc-field"><label>'._l($label).($required?' <em>*</em>':'').'</label><input type="'.$type.'" name="'.$name.'" value="'.html_escape($value).'" placeholder="'.html_escape($placeholder).'"'.($required?' required':'').'></div>'; }
function sc_radio($label,$name,$options,$required=false){ echo '<div class="sc-field sc-span-2"><label>'._l($label).($required?' <em>*</em>':'').'</label><div class="sc-pills">'; foreach($options as $value=>$key){ echo '<label><input type="radio" name="'.$name.'" value="'.html_escape($value).'"'.(set_value($name)===$value?' checked':'').($required?' required':'').'><span>'._l($key).'</span></label>'; } echo '</div></div>'; }
function sc_section($icon,$title,$subtitle){ echo '<section class="sc-section"><div class="sc-section-heading"><div><h2>'._l($title).'</h2><p>'._l($subtitle).'</p></div></div><div class="sc-grid">'; }
function sc_end(){ echo '</div></section>'; }
sc_section('01','recruitment_application_personal','recruitment_application_personal_help');
sc_field('recruitment_application_full_name','full_name','text',true); sc_field('recruitment_application_email','email','email',true); sc_field('recruitment_application_phone','phone','tel',true); sc_field('recruitment_application_dob','dob','date'); sc_field('recruitment_application_address','address'); sc_field('recruitment_application_city','city'); sc_field('recruitment_application_state','state'); sc_field('recruitment_application_zip','zip'); sc_end();
sc_section('02','recruitment_application_position_section','recruitment_application_position_help'); ?>
<div class="sc-field"><label><?php echo _l('recruitment_application_position'); ?> <em>*</em></label><select name="position" required><option value=""><?php echo _l('recruitment_application_select'); ?></option><?php foreach(['General Construction Worker','Roofer','Framer / Carpenter','Concrete / Foundation Worker','Electrician','Plumber','HVAC Installer','Site Supervisor / Foreman','Project Helper / Laborer','Other'] as $p): ?><option value="<?php echo html_escape($p); ?>" <?php echo set_select('position',$p); ?>><?php echo html_escape($p); ?></option><?php endforeach; ?></select></div>
<?php sc_field('recruitment_application_experience_years','experience_years','number',true); sc_field('recruitment_application_available_date','available_date','date',true); sc_radio('recruitment_application_employment_type','employment_type',['Full-Time'=>'recruitment_full_time','Part-Time'=>'recruitment_part_time','Temporary / Project-Based'=>'recruitment_temporary','Weekends Only'=>'recruitment_weekends'],true); sc_end();
sc_section('03','recruitment_application_license_section','recruitment_application_license_help'); ?>
<div class="sc-field"><label><?php echo _l('recruitment_application_resume'); ?></label><input type="file" name="resume" accept=".pdf,.doc,.docx,.rtf,.txt"><small><?php echo _l('recruitment_application_resume_help'); ?></small></div>
<div class="sc-field"><label><?php echo _l('recruitment_application_driver_license_upload'); ?></label><input type="file" name="driver_license" accept=".pdf,.jpg,.jpeg,.png"></div>
<?php sc_radio('recruitment_application_vehicle','vehicle_type',['Car'=>'recruitment_vehicle_car','Truck'=>'recruitment_vehicle_truck','Car and Truck'=>'recruitment_vehicle_both','No Personal Vehicle'=>'recruitment_vehicle_none']); ?>
<div class="sc-field"><label><?php echo _l('recruitment_application_education_level'); ?> <em>*</em></label><select name="education_level" required><option value=""><?php echo _l('recruitment_application_select'); ?></option><?php foreach(['Less than High School','High School / GED','Some College / Trade School','Associate Degree','Bachelor Degree','Master Degree or Higher'] as $e): ?><option value="<?php echo html_escape($e); ?>" <?php echo set_select('education_level',$e); ?>><?php echo html_escape($e); ?></option><?php endforeach; ?></select></div>
<?php sc_radio('recruitment_application_osha','has_construction_certificate',['Yes'=>'recruitment_yes','No'=>'recruitment_no']); sc_end();
sc_section('04','recruitment_application_skills_section','recruitment_application_skills_help'); ?>
<div class="sc-field sc-span-2"><label><?php echo _l('recruitment_application_skills'); ?></label><div class="sc-chips"><?php foreach(['Framing / Carpentry','Roofing','Drywall & Finishing','Painting','Concrete / Masonry','Flooring Installation','Electrical','Plumbing','Demolition','Scaffolding & Ladders','Power Tools','Heavy Equipment'] as $skill): ?><label><input type="checkbox" name="skills[]" value="<?php echo html_escape($skill); ?>"><span><?php echo html_escape($skill); ?></span></label><?php endforeach; ?></div></div>
<?php sc_end();
sc_section('05','recruitment_application_history_section','recruitment_application_history_help'); sc_field('recruitment_application_previous_company','prev_company'); sc_field('recruitment_application_previous_position','prev_position'); sc_field('recruitment_application_previous_duration','prev_duration'); sc_field('recruitment_application_reference_name','ref_name'); sc_field('recruitment_application_reference_phone','ref_phone','tel'); sc_end();
sc_section('06','recruitment_application_emergency_section','recruitment_application_emergency_help'); sc_field('recruitment_application_emergency_name','emergency_name'); sc_field('recruitment_application_emergency_phone','emergency_phone','tel'); sc_field('recruitment_application_emergency_relation','emergency_relation'); sc_end();
sc_section('07','recruitment_application_legal_section','recruitment_application_legal_help'); sc_radio('recruitment_application_authorized','legal_authorized',['Yes'=>'recruitment_yes','No'=>'recruitment_no'],true); sc_radio('recruitment_application_has_license','has_driver_license',['Yes'=>'recruitment_yes','No'=>'recruitment_no']); sc_radio('recruitment_application_criminal_record','criminal_record',['No'=>'recruitment_no','Yes'=>'recruitment_yes'],true); sc_radio('recruitment_application_heights','q_heights',['Yes'=>'recruitment_yes','No'=>'recruitment_no'],true); sc_radio('recruitment_application_lift','q_lift_weight',['Yes'=>'recruitment_yes','No'=>'recruitment_no'],true); sc_radio('recruitment_application_overtime','q_overtime',['Yes'=>'recruitment_yes','No'=>'recruitment_no'],true); ?>
<div class="sc-field sc-span-2"><label><?php echo _l('recruitment_application_safety'); ?> <em>*</em></label><select name="q_safety_first" required><option value=""><?php echo _l('recruitment_application_select'); ?></option><option value="Finishing the job fast"><?php echo _l('recruitment_safety_fast'); ?></option><option value="Keeping everyone safe with proper PPE and procedures"><?php echo _l('recruitment_safety_correct'); ?></option><option value="Taking frequent phone breaks"><?php echo _l('recruitment_safety_phone'); ?></option></select></div>
<?php sc_radio('recruitment_application_attention','q_attention',['Yes, I reviewed everything'=>'recruitment_reviewed_yes','No, I did not review'=>'recruitment_reviewed_no'],true); ?>
<div class="sc-field sc-span-2"><label><?php echo _l('recruitment_application_additional'); ?></label><textarea name="additional_info" rows="5"><?php echo html_escape(set_value('additional_info')); ?></textarea></div>
<div class="sc-field sc-span-2"><label><?php echo _l('recruitment_application_signature'); ?> <em>*</em></label><div class="sc-signature-wrap"><canvas id="signature-pad" height="180" data-required-message="<?php echo html_escape(_l('recruitment_signature_required')); ?>" aria-label="<?php echo html_escape(_l('recruitment_application_signature')); ?>"></canvas></div><input type="hidden" name="signature" id="signature-data"><div class="sc-signature-actions"><button type="button" id="clear-signature" class="sc-btn sc-btn-light"><?php echo _l('recruitment_clear_signature'); ?></button><small><?php echo _l('recruitment_signature_help'); ?></small></div></div><?php sc_field('recruitment_application_signature_date','signature_date','date',true); sc_end(); ?>
<section class="sc-section sc-w4"><div class="sc-section-heading"><div><h2><?php echo _l('recruitment_w4_title'); ?></h2><p><?php echo _l('recruitment_w4_help'); ?></p></div></div><a target="_blank" rel="noopener" href="<?php echo html_escape(get_option('smart_choice_recruitment_w4_url') ?: 'https://justsmartchoice.com/dev-tools/uploads/fw4.pdf'); ?>" class="sc-btn sc-btn-blue"><?php echo _l('recruitment_w4_button'); ?></a></section>
<p class="sc-consent"><?php echo _l('recruitment_application_consent'); ?></p><div class="sc-actions"><button type="reset" class="sc-btn sc-btn-light"><?php echo _l('recruitment_clear_form'); ?></button><button type="submit" class="sc-btn sc-btn-orange"><?php echo _l('recruitment_submit_application'); ?></button></div>
<?php echo form_close(); endif; ?>
</main></div></div></div>
<script src="<?php echo module_dir_url('recruitment','assets/js/smart_choice_signature_pad.js'); ?>?v=1900"></script></body></html>
