<?php defined('BASEPATH') or exit('No direct script access allowed'); ?>
<div id="top"></div><?php hooks()->do_action('app_customers_portal_head'); ?>
<?php $clean=static function($t){$t=strip_tags((string)$t);$t=preg_replace('/[\x{1F000}-\x{1FAFF}\x{2600}-\x{27BF}]/u','',$t);return trim(preg_replace('/\s+/',' ',$t));}; ?>
<div class="sc-rec-page">
<section class="sc-rec-hero"><div class="sc-rec-shell"><span class="sc-rec-eyebrow"><?php echo _l('recruitment_portal'); ?></span><h1><?php echo _l('recruitment_portal_hero_title'); ?></h1><p><?php echo _l('recruitment_portal_hero_text'); ?></p><a class="sc-rec-primary" href="#jobs"><?php echo _l('recruitment_view_positions'); ?></a></div></section>
<section class="sc-rec-search"><div class="sc-rec-shell"><h2><?php echo _l('recruitment_careers_title'); ?></h2><p><?php echo _l('recruitment_careers_text'); ?></p><?php echo form_open_multipart(site_url('recruitment/recruitment_portal/search_job'),['id'=>'search_job','class'=>'sc-search-form']); ?><input type="search" name="search" value="<?php echo isset($search)?html_escape($search):''; ?>" placeholder="<?php echo _l('rp_key_search'); ?>"><button type="submit"><?php echo _l('search'); ?></button><?php echo form_close(); ?></div></section>
<section id="jobs" class="sc-rec-jobs"><div class="sc-rec-shell">
<?php if(!empty($rec_campaingn)){ ?><div class="sc-job-grid">
<?php foreach($rec_campaingn as $job){ $desc=$clean($job['cp_job_description']??''); ?>
<article class="sc-job-card"><div class="sc-job-card-top"><span class="sc-job-type"><?php echo html_escape($job['cp_form_work']?:_l('not_specified')); ?></span><?php if(strtotime(date('Y-m-d'))>strtotime($job['cp_to_date'])){ ?><span class="sc-job-status"><?php echo _l('overdue'); ?></span><?php } ?></div><h3><a href="<?php echo site_url('recruitment/recruitment_portal/job_detail/'.(int)$job['cp_id']); ?>"><?php echo html_escape($job['campaign_name']); ?></a></h3><div class="sc-job-company"><?php echo html_escape($job['company_name']?:'Smart Choice Contractors USA'); ?></div><div class="sc-job-meta"><span><i class="fa fa-map-marker"></i><?php echo html_escape($job['cp_workplace']?:_l('not_specified')); ?></span><span><i class="fa fa-briefcase"></i><?php echo html_escape($job['position_name']?:_l('not_specified')); ?></span></div><p><?php echo html_escape(mb_strimwidth($desc,0,280,'...')); ?></p><div class="sc-job-footer"><span><?php echo html_escape($job['cp_from_date'].' – '.$job['cp_to_date']); ?></span><a class="sc-job-detail-btn" href="<?php echo site_url('recruitment/recruitment_portal/job_detail/'.(int)$job['cp_id']); ?>"><?php echo _l('view_detail'); ?></a></div></article>
<?php } ?></div><?php }else{ ?><div class="sc-empty"><?php echo _l('recruitment_portal_not_found'); ?></div><?php } ?>
</div></section></div><?php hooks()->do_action('app_customers_portal_footer'); ?>
