<?php defined('BASEPATH') or exit('No direct script access allowed'); ?>
<?php init_head(); ?>
<div id="wrapper"><div class="content snm-wrap">
  <div class="snm-hero"><div><h1><i class="fa fa-heartbeat"></i> Health Checker</h1><p>Check module tables, columns, settings, and recent CRM errors.</p></div><div class="snm-actions"><a class="btn snm-btn-light" href="<?php echo admin_url('smart_network_manager'); ?>">Back</a></div></div>
  <div class="panel_s snm-panel"><div class="panel-heading snm-panel-heading">Module Health</div><div class="panel-body"><div class="row"><?php foreach($health as $item){ ?><div class="col-md-4"><div class="snm-health"><strong><?php echo html_escape($item['name']); ?></strong><span><?php echo html_escape($item['status']); ?></span></div></div><?php } ?></div></div></div>
  <div class="panel_s snm-panel"><div class="panel-heading snm-panel-heading">Database Checker</div><div class="panel-body table-responsive"><table class="table table-striped"><thead><tr><th>Item</th><th>Status</th></tr></thead><tbody><?php foreach($database as $row){ ?><tr><td><?php echo html_escape($row['item']); ?></td><td><?php echo html_escape($row['status']); ?></td></tr><?php } ?></tbody></table><hr><?php foreach(['check','analyze','optimize','repair'] as $tool){ echo form_open(admin_url('smart_network_manager/db_tool/'.$tool), ['class'=>'snm-inline-form']); ?><button class="btn snm-btn-blue _delete" type="submit"><?php echo ucfirst($tool); ?> Module Tables</button><?php echo form_close(); } ?></div></div>
  <div class="panel_s snm-panel"><div class="panel-heading snm-panel-heading">Recent CRM Error Report</div><div class="panel-body table-responsive"><table class="table table-condensed"><thead><tr><th>Log File</th><th>Line</th></tr></thead><tbody><?php if(empty($errors)){ ?><tr><td colspan="2">No recent errors found in the latest log files.</td></tr><?php } foreach($errors as $err){ ?><tr><td><?php echo html_escape($err['file']); ?></td><td><code><?php echo html_escape($err['line']); ?></code></td></tr><?php } ?></tbody></table></div></div>
</div></div>
<?php init_tail(); ?>
