<?php defined('BASEPATH') or exit('No direct script access allowed'); $this->load->view('usi_smartchoice_seo/partials/top'); $h=$handoff ?? []; echo form_open(current_url()); ?>
<div class="panel_s"><div class="panel-body"><h4><?php echo html_escape($title); ?></h4><hr>
<div class="row"><div class="col-md-6"><label>Handoff Title</label><input name="handoff_title" class="form-control" value="<?php echo html_escape($h['handoff_title'] ?? ''); ?>"></div><div class="col-md-6"><label>Project Name</label><input name="project_name" class="form-control" value="<?php echo html_escape($h['project_name'] ?? ''); ?>"></div></div>
<div class="row mtop15"><div class="col-md-3"><label>AI Estimate ID</label><input name="ai_estimate_id" class="form-control" value="<?php echo (int)($h['ai_estimate_id'] ?? 0); ?>"></div><div class="col-md-3"><label>Customer ID</label><input name="customer_id" class="form-control" value="<?php echo (int)($h['customer_id'] ?? 0); ?>"></div><div class="col-md-3"><label>Project ID</label><input name="project_id" class="form-control" value="<?php echo (int)($h['project_id'] ?? 0); ?>"></div><div class="col-md-3"><label>Status</label><select name="handoff_status" class="form-control"><?php foreach(['draft','ready_for_project','tasks_created','on_hold','completed'] as $st){ ?><option value="<?php echo $st; ?>" <?php echo (($h['handoff_status'] ?? 'draft')===$st?'selected':''); ?>><?php echo ucwords(str_replace('_',' ',$st)); ?></option><?php } ?></select></div></div>
<div class="row mtop15"><div class="col-md-4"><label>Assigned Staff ID</label><input name="assigned_staff_id" class="form-control" value="<?php echo (int)($h['assigned_staff_id'] ?? get_staff_user_id()); ?>"></div><div class="col-md-4"><label>Start Date</label><input type="date" name="start_date" class="form-control" value="<?php echo html_escape($h['start_date'] ?? ''); ?>"></div><div class="col-md-4"><label>Due Date</label><input type="date" name="due_date" class="form-control" value="<?php echo html_escape($h['due_date'] ?? ''); ?>"></div></div>
<div class="row mtop15"><div class="col-md-12"><label>Production Notes</label><textarea name="production_notes" rows="5" class="form-control"><?php echo html_escape($h['production_notes'] ?? ''); ?></textarea></div></div>
<div class="row mtop15"><div class="col-md-6"><label>Material Notes</label><textarea name="material_notes" rows="5" class="form-control"><?php echo html_escape($h['material_notes'] ?? ''); ?></textarea></div><div class="col-md-6"><label>Permit Notes</label><textarea name="permit_notes" rows="5" class="form-control"><?php echo html_escape($h['permit_notes'] ?? ''); ?></textarea></div></div>
<div class="row mtop15"><div class="col-md-12"><label>Task Plan - one task per line</label><textarea name="task_plan" rows="7" class="form-control"><?php echo html_escape($h['task_plan'] ?? ''); ?></textarea></div></div>
<div class="mtop20"><button class="btn btn-primary btn-sm" type="submit">Save</button> <a class="btn btn-default btn-sm" href="<?php echo admin_url('usi_smartchoice_seo/project_handoffs'); ?>">Back</a></div>
</div></div><?php echo form_close(); ?>
