<?php defined('BASEPATH') or exit('No direct script access allowed'); init_head(); ?>
<div id="wrapper"><div class="content"><div class="panel_s"><div class="panel-body">
<?php $this->load->view('usi_smartchoice_seo/partials/top'); ?>
<h4><i class="fa fa-video-camera"></i> <?php echo html_escape($title); ?></h4>
<?php echo form_open(admin_url('usi_smartchoice_seo/video_project/' . (int)($video['id'] ?? 0))); ?>
<div class="row"><div class="col-md-6"><?php echo render_input('title', 'Video Title', $video['title'] ?? ''); ?></div><div class="col-md-3"><?php echo render_select('language', [['id'=>'en-US','name'=>'English'],['id'=>'es-US','name'=>'Spanish']], ['id','name'], 'Language', $video['language'] ?? 'en-US'); ?></div><div class="col-md-3"><?php echo render_select('video_purpose', [['id'=>'training','name'=>'Training'],['id'=>'marketing','name'=>'Marketing'],['id'=>'customer','name'=>'Customer'],['id'=>'project','name'=>'Project']], ['id','name'], 'Purpose', $video['video_purpose'] ?? 'training'); ?></div></div>
<div class="row"><div class="col-md-6"><label>Voice</label><select name="voice_id" class="form-control"><option value="0">Select Voice</option><?php foreach ($voices as $voice) { ?><option value="<?php echo (int)$voice['id']; ?>" <?php echo ((int)($video['voice_id'] ?? 0)===(int)$voice['id']?'selected':''); ?>><?php echo html_escape($voice['voice_name'].' - '.$voice['language']); ?></option><?php } ?></select></div><div class="col-md-6"><label>Avatar</label><select name="avatar_id" class="form-control"><option value="0">Select Avatar</option><?php foreach ($avatars as $avatar) { ?><option value="<?php echo (int)$avatar['id']; ?>" <?php echo ((int)($video['avatar_id'] ?? 0)===(int)$avatar['id']?'selected':''); ?>><?php echo html_escape($avatar['avatar_name'].' - '.$avatar['position_name']); ?></option><?php } ?></select></div></div>
<?php echo render_textarea('script_text', 'Script Text', $video['script_text'] ?? '', ['rows'=>8]); ?>
<div class="row"><div class="col-md-3"><?php echo render_select('logo_enabled', [['id'=>'1','name'=>'Yes'],['id'=>'0','name'=>'No']], ['id','name'], 'Add Logo Watermark', $video['logo_enabled'] ?? '1'); ?></div><div class="col-md-3"><?php echo render_select('logo_position', [['id'=>'top_right','name'=>'Top Right'],['id'=>'top_left','name'=>'Top Left'],['id'=>'bottom_right','name'=>'Bottom Right'],['id'=>'bottom_left','name'=>'Bottom Left']], ['id','name'], 'Logo Position', $video['logo_position'] ?? 'top_right'); ?></div><div class="col-md-3"><?php echo render_input('intro_thumbnail', 'Intro Thumbnail URL', $video['intro_thumbnail'] ?? ''); ?></div><div class="col-md-3"><?php echo render_input('outro_thumbnail', 'Outro Thumbnail URL', $video['outro_thumbnail'] ?? ''); ?></div></div>
<h4>Text Layers</h4>
<?php for ($i=1; $i<=4; $i++) { ?><div class="row"><div class="col-md-5"><?php echo render_input('text_layer_'.$i, 'Text '.$i, ''); ?></div><div class="col-md-2"><?php echo render_input('text_start_'.$i, 'Start Second', '0', 'number'); ?></div><div class="col-md-2"><?php echo render_input('text_duration_'.$i, 'Duration', '5', 'number'); ?></div><div class="col-md-3"><?php echo render_select('text_animation_'.$i, [['id'=>'fade','name'=>'Fade'],['id'=>'vanish','name'=>'Vanish'],['id'=>'rollover','name'=>'Rollover'],['id'=>'slide','name'=>'Slide']], ['id','name'], 'Animation', 'fade'); ?></div></div><?php } ?>
<?php echo render_textarea('ai_notes', 'AI Notes / Generation Instructions', $video['ai_notes'] ?? '', ['rows'=>4]); ?>
<div class="text-right"><a class="btn btn-default" href="<?php echo admin_url('usi_smartchoice_seo/video_studio'); ?>">Back</a><button type="submit" class="btn btn-primary">Save Video Project</button></div>
<?php echo form_close(); ?></div></div></div></div><?php init_tail(); ?>
