<?php defined('BASEPATH') or exit('No direct script access allowed'); ?>
<?php init_head(); ?>
<div id="wrapper"><div class="content"><div class="google-meet-wrap smart-choice-normalized-module gm-help">
  <div class="google-meet-header"><div><span class="gm-provider-label">Powered by Jitsi</span><h1><i class="fa fa-question-circle" aria-hidden="true"></i> Video Meeting Help</h1><p>Create a shared room, invite participants and join your meeting with confidence.</p></div></div>
  <?php $this->load->view('google_meet/_nav'); ?>
  <div class="gm-instruction-banner"><h3><i class="fa fa-video-camera" aria-hidden="true"></i> One meeting, one shared room</h3><p>Video Meeting connects staff and customer contacts through Jitsi. The CRM saves a single room link for all attendees. Customers sign in to the portal and see only meetings assigned to their contact.</p></div>
  <div class="gm-help-grid">
    <div class="gm-help-card"><h3><span>1</span> Create and assign</h3><p>Open <strong>Video Meeting &gt; New Meeting</strong>. Set the topic, schedule and participants. Leave <strong>Shared Video Meeting Link</strong> blank to generate a Jitsi room automatically. Select the exact customer in <strong>Customer Contacts</strong> so the meeting appears in that customer's portal.</p></div>
    <div class="gm-help-card"><h3><span>2</span> Start as host</h3><p>Open the saved meeting and choose <strong>Join Meeting</strong>. On the public <strong>meet.jit.si</strong> service, the host must sign in to start the room. Guests join after the host starts it. CRM permissions and Jitsi moderator permissions are separate.</p></div>
    <div class="gm-help-card"><h3><span>3</span> Staff permissions</h3><p>Use CRM roles to grant <strong>View Own</strong> or global <strong>View</strong>, followed by <strong>Create</strong>, <strong>Edit</strong> and <strong>Delete</strong> only as needed. Settings and notification tests require the existing Settings permission. Changing the meeting name does not change who can access it.</p></div>
    <div class="gm-help-card"><h3><span>4</span> Customer access</h3><p>Enable the customer portal in <strong>Settings</strong>. Assigned contacts find their meetings under <strong>Meetings &gt; Video Meeting</strong>. An empty list means no meeting has been assigned to that contact. Logged-out customers use the normal CRM login.</p></div>
    <div class="gm-help-card"><h3><span>5</span> Share and invite</h3><p>Save the meeting before sharing its room link. Invitations use the existing CRM email, notifications and configured SMS service. Share controls prepare a message for you to send; they do not send it automatically. Previously saved external meeting links remain available.</p></div>
    <div class="gm-help-card"><h3><span>6</span> Privacy and room security</h3><p>Staff meeting notes stay private from customers. If a room PIN is enabled, the Jitsi moderator applies it after joining. On the public service the PIN does not persist after everyone leaves. Lobby and moderation controls depend on the configured video service.</p></div>
    <div class="gm-help-card"><h3><span>7</span> Recording and notes</h3><p>Recording availability depends on the Jitsi service and moderator permissions. CRM recording preferences do not enable a provider feature. Add an available recording link or summary to the meeting notes after the call.</p></div>
    <div class="gm-help-card"><h3><span>8</span> Troubleshoot joining</h3><p>Check <strong>Health</strong>, the configured Jitsi hostname and the customer's assignment. If the room says it is waiting for a moderator, ask the host to join and sign in. Allow microphone and camera access in your browser. Notification tests send real messages; use a test recipient.</p></div>
  </div>
</div></div></div>
<?php init_tail(); ?>
