<?php
defined('BASEPATH') or exit('No direct script access allowed');
class Smart_choice_call_center extends AdminController {
 public function __construct(){parent::__construct();$this->load->model('smart_choice_call_center/Call_center_model','cc');$this->load->helper('smart_choice_call_center/smart_choice_call_center');}
 private function page($view,$data=[]){$data['title']=_l('sccc_menu');$data['stats']=$this->cc->stats();$data['calls']=$this->cc->calls(100,!sccc_can('view'));$this->load->view('smart_choice_call_center/'.$view,$data);}
 public function index(){redirect(admin_url('smart_choice_call_center/dashboard'));}
 public function dashboard(){sccc_require(sccc_can('view')?'view':'view_own');$this->page('dashboard');}
 public function dialer(){sccc_require(sccc_can('view')?'view':'view_own');$this->page('dialer');}
 public function calls(){sccc_require(sccc_can('view')?'view':'view_own');$this->page('calls');}
 public function campaigns(){sccc_require('manage_campaigns');$this->page('campaigns',['campaigns'=>$this->cc->get_campaigns(),'lists'=>$this->cc->get_lists(),'agents'=>$this->cc->get_ai_agents()]);}
 public function lists(){sccc_require('view');$this->page('lists',['lists'=>$this->cc->get_lists()]);}
 public function ivr(){sccc_require('manage_ivr');$this->page('ivr',['extensions'=>$this->cc->get_extensions()]);}
 public function greetings(){sccc_require('manage_ivr');$this->page('greetings',['greetings'=>$this->cc->get_greetings()]);}
 public function callbacks(){sccc_require('view');$this->page('callbacks');}
 public function recordings(){sccc_require('manage_recordings');$this->page('recordings');}
 public function ai(){sccc_require('manage_ai');$this->page('ai',['agents'=>$this->cc->get_ai_agents()]);}
 public function reports(){sccc_require('view_reports');$this->page('reports');}
 public function token(){sccc_require(sccc_can('view')?'view':'view_own');$t=sccc_twilio_access_token('staff_'.get_staff_user_id());$this->output->set_content_type('application/json')->set_output(json_encode(['success'=>(bool)$t,'token'=>$t]));}
 public function place_call(){sccc_require('create');$r=$this->cc->place_call($this->input->post('phone'),get_staff_user_id());$this->output->set_content_type('application/json')->set_output(json_encode($r));}
 public function save_list(){sccc_require('create');$this->db->insert(db_prefix().'sccc_lists',['name'=>$this->input->post('name',true),'description'=>$this->input->post('description',true),'created_by'=>get_staff_user_id(),'created_at'=>date('Y-m-d H:i:s')]);set_alert('success',_l('sccc_saved'));redirect(admin_url('smart_choice_call_center/lists'));}
 public function sample_csv(){sccc_require('import');header('Content-Type:text/csv');header('Content-Disposition:attachment; filename="call-center-import-sample.csv"');echo "first_name,last_name,company,phone,email,lead_source,assigned_staff,notes\nJohn,Doe,Example Company,+1 (555) 123-4567,john@example.com,Website,,Sample note\n";exit;}
 public function import_csv($list_id){sccc_require('import');if(empty($_FILES['csv']['tmp_name'])){set_alert('danger',_l('sccc_import_file_required'));redirect(admin_url('smart_choice_call_center/lists'));} $fh=fopen($_FILES['csv']['tmp_name'],'r');$h=fgetcsv($fh);$h=array_map('trim',$h);$required=['first_name','last_name','company','phone','email','lead_source','assigned_staff','notes'];foreach($required as $x){if(!in_array($x,$h,true)){set_alert('danger',_l('sccc_import_bad_header'));redirect(admin_url('smart_choice_call_center/lists'));}}$n=0;while(($r=fgetcsv($fh))!==false){$d=array_combine($h,array_pad($r,count($h),''));$phone=sccc_phone($d['phone']);if(!$phone)continue;$this->db->insert(db_prefix().'sccc_list_contacts',['list_id'=>(int)$list_id,'first_name'=>$d['first_name'],'last_name'=>$d['last_name'],'company'=>$d['company'],'phone'=>$phone,'email'=>$d['email'],'lead_source'=>$d['lead_source'],'assigned_staff'=>(int)$d['assigned_staff']?:null,'notes'=>$d['notes'],'created_at'=>date('Y-m-d H:i:s')]);$n++;}fclose($fh);set_alert('success',_l('sccc_imported_count',$n));redirect(admin_url('smart_choice_call_center/lists'));}
 public function export_list($list_id){sccc_require('export');$rows=$this->db->where('list_id',(int)$list_id)->get(db_prefix().'sccc_list_contacts')->result_array();header('Content-Type:text/csv');header('Content-Disposition:attachment; filename="call-list-'.$list_id.'.csv"');$o=fopen('php://output','w');fputcsv($o,['first_name','last_name','company','phone','email','lead_source','assigned_staff','notes','status','disposition']);foreach($rows as $r)fputcsv($o,[$r['first_name'],$r['last_name'],$r['company'],sccc_phone_display($r['phone']),$r['email'],$r['lead_source'],$r['assigned_staff'],$r['notes'],$r['status'],$r['disposition']]);fclose($o);exit;}
 public function save_extension(){sccc_require('manage_extensions');$id=(int)$this->input->post('id');$d=['staff_id'=>(int)$this->input->post('staff_id')?:null,'extension'=>$this->input->post('extension',true),'display_name'=>$this->input->post('display_name',true),'destination_type'=>$this->input->post('destination_type',true),'destination'=>$this->input->post('destination',true),'fallback_number'=>sccc_phone($this->input->post('fallback_number')),'ring_seconds'=>(int)$this->input->post('ring_seconds'),'active'=>$this->input->post('active')?1:0,'updated_at'=>date('Y-m-d H:i:s')];if($id)$this->db->where('id',$id)->update(db_prefix().'sccc_extensions',$d);else{$d['created_at']=date('Y-m-d H:i:s');$this->db->insert(db_prefix().'sccc_extensions',$d);}set_alert('success',_l('sccc_saved'));redirect(admin_url('smart_choice_call_center/ivr'));}
 public function upload_greeting(){sccc_require('manage_ivr');$name=$this->input->post('name',true);$tts=$this->input->post('text_to_speech',true);$file=null;$path=null;if(!empty($_FILES['audio']['tmp_name'])){$ext=strtolower(pathinfo($_FILES['audio']['name'],PATHINFO_EXTENSION));if(!in_array($ext,['mp3','wav','m4a'],true)){set_alert('danger',_l('sccc_audio_type_error'));redirect(admin_url('smart_choice_call_center/greetings'));}$file=time().'_'.preg_replace('/[^a-zA-Z0-9._-]/','_',$_FILES['audio']['name']);$dir=FCPATH.'uploads/smart_choice_call_center/greetings/';if(!is_dir($dir))mkdir($dir,0755,true);move_uploaded_file($_FILES['audio']['tmp_name'],$dir.$file);$path='uploads/smart_choice_call_center/greetings/'.$file;}$this->db->insert(db_prefix().'sccc_greetings',['name'=>$name,'type'=>$this->input->post('type',true),'file_name'=>$file,'file_path'=>$path,'text_to_speech'=>$tts,'voice'=>$this->input->post('voice',true),'language'=>$this->input->post('language',true),'created_by'=>get_staff_user_id(),'created_at'=>date('Y-m-d H:i:s')]);set_alert('success',_l('sccc_saved'));redirect(admin_url('smart_choice_call_center/greetings'));}
 public function save_campaign(){sccc_require('manage_campaigns');$d=['name'=>$this->input->post('name',true),'list_id'=>(int)$this->input->post('list_id'),'staff_id'=>(int)$this->input->post('staff_id')?:null,'caller_id'=>sccc_phone($this->input->post('caller_id')),'status'=>'draft','mode'=>$this->input->post('mode',true),'ai_agent_id'=>(int)$this->input->post('ai_agent_id')?:null,'max_attempts'=>(int)$this->input->post('max_attempts')?:2,'retry_minutes'=>(int)$this->input->post('retry_minutes')?:60,'daily_limit'=>(int)$this->input->post('daily_limit')?:500,'timezone'=>get_option('sccc_default_timezone'),'created_by'=>get_staff_user_id(),'created_at'=>date('Y-m-d H:i:s')];$this->db->insert(db_prefix().'sccc_campaigns',$d);set_alert('success',_l('sccc_saved'));redirect(admin_url('smart_choice_call_center/campaigns'));}
 public function campaign_status($id,$status){sccc_require('manage_campaigns');if(in_array($status,['running','paused','stopped'],true)){$this->db->where('id',(int)$id)->update(db_prefix().'sccc_campaigns',['status'=>$status,'updated_at'=>date('Y-m-d H:i:s')]);if($status==='running')$this->cc->process_campaign((int)$id,1);}redirect(admin_url('smart_choice_call_center/campaigns'));}
 public function save_ai_agent(){sccc_require('manage_ai');$this->db->insert(db_prefix().'sccc_ai_agents',['name'=>$this->input->post('name',true),'provider'=>$this->input->post('provider',true),'websocket_url'=>$this->input->post('websocket_url',true),'webhook_url'=>$this->input->post('webhook_url',true),'system_prompt'=>$this->input->post('system_prompt'),'voice_name'=>$this->input->post('voice_name',true),'active'=>1,'created_by'=>get_staff_user_id(),'created_at'=>date('Y-m-d H:i:s')]);set_alert('success',_l('sccc_saved'));redirect(admin_url('smart_choice_call_center/ai'));}
 public function recording_download($id){sccc_require('manage_recordings');$r=$this->db->where('id',(int)$id)->get(db_prefix().'sccc_recordings')->row_array();if(!$r)show_404();$url=$r['recording_url'];if(substr($url,-4)!=='.mp3')$url.='.mp3';$sid=get_option('sccc_twilio_account_sid');$token=get_option('sccc_twilio_auth_token');$ch=curl_init($url);curl_setopt($ch,CURLOPT_RETURNTRANSFER,true);curl_setopt($ch,CURLOPT_USERPWD,$sid.':'.$token);$body=curl_exec($ch);$code=curl_getinfo($ch,CURLINFO_HTTP_CODE);curl_close($ch);if($code>=300)show_error(_l('sccc_recording_download_failed'));header('Content-Type:audio/mpeg');header('Content-Disposition:attachment; filename="call-recording-'.$id.'.mp3"');echo $body;exit;}
}
