<?php
defined('BASEPATH') or exit('No direct script access allowed');
class Webhook extends App_Controller {
 public function __construct(){parent::__construct();$this->load->model('smart_choice_call_center/Call_center_model','cc');$this->load->helper('smart_choice_call_center/smart_choice_call_center');}
 private function xml($x){$this->output->set_content_type('text/xml')->set_output($x);}
 private function greeting($id){$g=$id?$this->db->where('id',(int)$id)->get(db_prefix().'sccc_greetings')->row_array():null;if($g&&$g['file_path'])return '<Play>'.sccc_xml(base_url($g['file_path'])).'</Play>';if($g&&$g['text_to_speech'])return '<Say voice="'.sccc_xml($g['voice']?:'Polly.Joanna').'" language="'.sccc_xml($g['language']?:'en-US').'">'.sccc_xml($g['text_to_speech']).'</Say>';return '<Say>'.sccc_xml(_l('sccc_default_greeting')).'</Say>';}
 public function incoming(){
  $from=$this->input->post('From');$to=$this->input->post('To');$sid=$this->input->post('CallSid');$id=$this->cc->create_call(['twilio_sid'=>$sid,'direction'=>'inbound','from_number'=>$from,'to_number'=>$to,'status'=>'ringing']);$g=$this->greeting((int)get_option('sccc_main_greeting_id'));$action=site_url('smart_choice_call_center/webhook/ivr_route?call_id='.$id);$prompt=_l('sccc_ivr_prompt');$xml='<?xml version="1.0" encoding="UTF-8"?><Response>'.$g.'<Gather input="dtmf speech" numDigits="3" timeout="5" speechTimeout="auto" action="'.sccc_xml($action).'" method="POST"><Say>'.sccc_xml($prompt).'</Say></Gather><Redirect method="POST">'.sccc_xml($action).'</Redirect></Response>';$this->xml($xml);
 }
 public function ivr_route(){
  $call=(int)$this->input->get('call_id');$digits=trim((string)$this->input->post('Digits'));$speech=trim((string)$this->input->post('SpeechResult'));$ext=null;if($digits!=='')$ext=$this->db->where('extension',$digits)->where('active',1)->get(db_prefix().'sccc_extensions')->row_array();if(!$ext&&$speech!==''){$rows=$this->db->where('active',1)->get(db_prefix().'sccc_extensions')->result_array();foreach($rows as $r){if(stripos($speech,$r['display_name'])!==false){$ext=$r;break;}}}
  if(!$ext && $digits===get_option('sccc_operator_key') && get_option('sccc_operator_extension'))$ext=$this->db->where('extension',get_option('sccc_operator_extension'))->get(db_prefix().'sccc_extensions')->row_array();
  if($digits===get_option('sccc_callback_key') && get_option('sccc_enable_callbacks')==='1'){$this->db->insert(db_prefix().'sccc_callbacks',['call_id'=>$call,'phone'=>$this->input->post('From'),'status'=>'pending','created_at'=>date('Y-m-d H:i:s')]);$this->xml('<?xml version="1.0"?><Response><Say>'.sccc_xml(_l('sccc_callback_confirmed')).'</Say><Hangup/></Response>');return;}
  if(!$ext){$this->xml('<?xml version="1.0"?><Response><Say>'.sccc_xml(_l('sccc_extension_not_found')).'</Say><Redirect>'.sccc_xml(site_url('smart_choice_call_center/webhook/incoming')).'</Redirect></Response>');return;}
  $dest=$ext['destination_type']==='browser'?'client:staff_'.$ext['staff_id']:sccc_phone($ext['destination']);$record=get_option('sccc_record_calls')==='1'?' record="record-from-answer-dual" recordingStatusCallback="'.sccc_xml(site_url('smart_choice_call_center/webhook/recording?call_id='.$call)).'"':'';$dial='<Dial timeout="'.(int)$ext['ring_seconds'].'"'.$record.'><Number>'.sccc_xml($dest).'</Number></Dial>';if($ext['destination_type']==='browser')$dial='<Dial timeout="'.(int)$ext['ring_seconds'].'"'.$record.'><Client>staff_'.(int)$ext['staff_id'].'</Client></Dial>';$this->xml('<?xml version="1.0"?><Response><Say>'.sccc_xml(_l('sccc_connecting_to',$ext['display_name'])).'</Say>'.$dial.'</Response>');
 }
 public function outgoing_twiml(){
  $call=(int)$this->input->get('call_id');$ai=(int)$this->input->get('ai_agent_id');$r=$this->db->where('id',$call)->get(db_prefix().'sccc_calls')->row_array();if(!$r)show_404();if($ai){$a=$this->db->where('id',$ai)->where('active',1)->get(db_prefix().'sccc_ai_agents')->row_array();if($a&&$a['websocket_url']){$xml='<?xml version="1.0"?><Response><Connect><Stream url="'.sccc_xml($a['websocket_url']).'"><Parameter name="call_id" value="'.$call.'"/><Parameter name="agent_id" value="'.$ai.'"/></Stream></Connect></Response>';$this->xml($xml);return;}}
  $record=get_option('sccc_record_calls')==='1'?' record="record-from-answer-dual" recordingStatusCallback="'.sccc_xml(site_url('smart_choice_call_center/webhook/recording?call_id='.$call)).'"':'';$this->xml('<?xml version="1.0"?><Response><Dial'.$record.' callerId="'.sccc_xml($r['from_number']).'"><Number>'.sccc_xml($r['to_number']).'</Number></Dial></Response>');
 }
 public function browser_outgoing(){
  $to=$this->input->post('To')?:$this->input->get('To');$from=get_option('sccc_outbound_caller_id')?:get_option('sccc_main_number');$identity=(string)$this->input->post('From');$staff_id=0;if(preg_match('/staff_(\d+)/',$identity,$m))$staff_id=(int)$m[1];$id=$this->cc->create_call(['twilio_sid'=>$this->input->post('CallSid'),'staff_id'=>$staff_id?:null,'direction'=>'outbound','from_number'=>$from,'to_number'=>sccc_phone($to),'status'=>'in-progress','answered_at'=>date('Y-m-d H:i:s')]);$record=get_option('sccc_record_calls')==='1'?' record="record-from-answer-dual" recordingStatusCallback="'.sccc_xml(site_url('smart_choice_call_center/webhook/recording?call_id='.$id)).'"':'';$action=site_url('smart_choice_call_center/webhook/browser_complete?call_id='.$id);$this->xml('<?xml version="1.0"?><Response><Dial'.$record.' callerId="'.sccc_xml($from).'" action="'.sccc_xml($action).'"><Number>'.sccc_xml(sccc_phone($to)).'</Number></Dial></Response>'); }
 public function browser_complete(){ $id=(int)$this->input->get('call_id');$status=$this->input->post('DialCallStatus')?:'completed';$dur=(int)$this->input->post('DialCallDuration');$this->db->where('id',$id)->update(db_prefix().'sccc_calls',['status'=>$status,'duration'=>$dur,'ended_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')]);$this->xml('<?xml version="1.0"?><Response><Hangup/></Response>'); }
 public function status(){
  $id=(int)$this->input->get('call_id');$status=$this->input->post('CallStatus');$dur=(int)$this->input->post('CallDuration');$sid=$this->input->post('CallSid');$d=['status'=>$status?:'unknown','duration'=>$dur,'updated_at'=>date('Y-m-d H:i:s')];if($sid)$d['twilio_sid']=$sid;if($status==='in-progress')$d['answered_at']=date('Y-m-d H:i:s');if(in_array($status,['completed','busy','failed','no-answer','canceled'],true))$d['ended_at']=date('Y-m-d H:i:s');$this->db->where('id',$id)->update(db_prefix().'sccc_calls',$d);$c=$this->db->where('id',$id)->get(db_prefix().'sccc_calls')->row_array();if($c&&$c['list_contact_id']&&in_array($status,['completed','busy','failed','no-answer','canceled'],true)){$next=in_array($status,['busy','no-answer'],true)?date('Y-m-d H:i:s',time()+3600):null;$this->db->where('id',$c['list_contact_id'])->update(db_prefix().'sccc_list_contacts',['status'=>$status==='completed'?'called':'ready','next_attempt_at'=>$next]);if($c['campaign_id'])$this->cc->process_campaign((int)$c['campaign_id'],1);}echo 'OK';
 }
 public function recording(){ $call=(int)$this->input->get('call_id');$sid=$this->input->post('RecordingSid');$url=$this->input->post('RecordingUrl');if($url){$this->db->insert(db_prefix().'sccc_recordings',['call_id'=>$call,'twilio_recording_sid'=>$sid,'recording_url'=>$url,'duration'=>(int)$this->input->post('RecordingDuration'),'channels'=>(int)$this->input->post('RecordingChannels')?:1,'created_at'=>date('Y-m-d H:i:s')]);}echo 'OK'; }
}
