<?php defined('BASEPATH') or exit('No direct script access allowed'); init_head(); ?>
<div id="wrapper"><div class="content"><div class="panel_s"><div class="panel-body">
<?php $this->load->view('usi_smartchoice_seo/partials/top'); ?>
<div class="sc-toolbar"><h4><i class="fa fa-folder-open-o"></i> <?php echo html_escape($title); ?></h4><div class="sc-toolbar-actions"><a class="btn btn-info btn-sm" href="<?php echo admin_url('usi_smartchoice_seo/estimate_review_queue'); ?>">Estimate Review</a><a class="btn btn-default btn-sm" href="<?php echo admin_url('usi_smartchoice_seo/customer_packages'); ?>">Reload</a></div></div>
<form method="get" class="sc-filter row"><div class="col-md-8"><input type="text" name="search" class="form-control" placeholder="Filter title, scope, handoff, or status" value="<?php echo html_escape($filters['search'] ?? ''); ?>"></div><div class="col-md-3"><select name="package_status" class="form-control"><option value="">All Statuses</option><?php foreach (['draft','ready_for_review','ready_to_send','sent','archived'] as $status) { ?><option value="<?php echo html_escape($status); ?>" <?php echo (($filters['package_status'] ?? '') === $status) ? 'selected' : ''; ?>><?php echo ucwords(str_replace('_',' ',$status)); ?></option><?php } ?></select></div><div class="col-md-1"><button class="btn btn-default btn-block" type="submit">Filter</button></div></form>
<div class="table-responsive"><table class="table table-striped table-condensed sc-table"><thead><tr><th>ID</th><th>Package</th><th>AI Estimate</th><th>Customer</th><th>CRM Estimate</th><th>Status</th><th>Updated</th><th class="text-center">Actions</th></tr></thead><tbody>
<?php foreach (($packages ?? []) as $row) { ?><tr><td><?php echo (int)$row['id']; ?></td><td><?php echo html_escape($row['package_title']); ?></td><td><?php echo (int)$row['ai_estimate_id']; ?></td><td><?php echo (int)$row['customer_id']; ?></td><td><?php echo (int)$row['crm_estimate_id']; ?></td><td><?php echo html_escape($row['package_status']); ?></td><td><?php echo html_escape($row['updated_at']); ?></td><td class="text-center"><a class="btn btn-info btn-xs" href="<?php echo admin_url('usi_smartchoice_seo/customer_package/' . (int)$row['id']); ?>">View</a></td></tr><?php } ?>
<?php if (empty($packages)) { ?><tr><td colspan="8" class="text-center text-muted">No customer packages yet. Build one from an approved AI estimate.</td></tr><?php } ?>
</tbody></table></div>
</div></div></div></div><?php init_tail(); ?>
