<?php defined('BASEPATH') or exit('No direct script access allowed'); init_head(); ?>
<div id="wrapper"><?php $this->load->view('admin/_nav'); ?><div class="content"><div class="panel_s"><div class="panel-body">
<div class="tw-flex tw-items-center tw-justify-between"><h4><i class="fa fa-clone"></i> <?= _l('cabinet_maker_materials'); ?></h4>
<div class="cm-toolbar"><button type="button" class="btn btn-default" data-toggle="modal" data-target="#cmImportMaterials"><i class="fa fa-upload"></i> <?= _l('cabinet_maker_import'); ?></button><a class="btn btn-default" href="<?= admin_url('cabinet_maker/sample_materials'); ?>"><i class="fa fa-download"></i> <?= _l('cabinet_maker_sample_header'); ?></a><button type="button" class="btn btn-default" onclick="location.reload()"><i class="fa fa-refresh"></i> <?= _l('cabinet_maker_reload'); ?></button><button type="button" class="btn btn-default" onclick="cmExportMaterials('csv')"><i class="fa fa-file-excel-o"></i> CSV</button><button type="button" class="btn btn-default" onclick="window.print()"><i class="fa fa-print"></i> Print</button></div></div><hr>
<div class="row"><div class="col-md-8">
<table id="cmMaterialsTable" class="table table-striped dt-table"><thead><tr><th>Name</th><th>SKU</th><th>Category</th><th>Size</th><th>Unit</th><th>Cost</th></tr></thead><tbody>
<?php foreach($materials as $m){ ?><tr><td><?= html_escape($m->name); ?></td><td><?= html_escape($m->sku); ?></td><td><?= html_escape(ucfirst($m->category)); ?></td><td><?= ($m->width !== null ? html_escape(rtrim(rtrim((string)$m->width,'0'),'.').' × '.rtrim(rtrim((string)$m->length,'0'),'.').' × '.rtrim(rtrim((string)$m->thickness,'0'),'.')) : '-'); ?></td><td><?= html_escape($m->unit); ?></td><td><?= app_format_money($m->unit_cost,get_base_currency()); ?></td></tr><?php } ?>
</tbody></table><?php if(empty($materials)){ ?><div class="alert alert-warning">No materials are available. Refresh this page to run the default material seed.</div><?php } ?></div>
<div class="col-md-4"><div class="panel_s"><div class="panel-body"><h5><i class="fa fa-plus-circle"></i> Add Material</h5><?= form_open(admin_url('cabinet_maker/materials')); ?><?= render_input('name','name','','text',['required'=>true]); ?><?= render_input('sku','SKU'); ?><?= render_input('category','Category','sheet'); ?><?= render_input('width','Width',48,'number',['step'=>'.001']); ?><?= render_input('length','Length',96,'number',['step'=>'.001']); ?><?= render_input('thickness','Thickness','.75','number',['step'=>'.001']); ?><?= render_input('unit_cost','Unit Cost',0,'number',['step'=>'.01']); ?><input type="hidden" name="unit" value="sheet"><button class="btn btn-primary btn-block"><i class="fa fa-plus"></i> Add Material</button><?= form_close(); ?></div></div></div></div>
</div></div></div></div>
<script>function cmExportMaterials(type){if(type!=='csv')return;var rows=[['Name','SKU','Category','Size','Unit','Cost']];document.querySelectorAll('#cmMaterialsTable tbody tr').forEach(function(tr){rows.push(Array.from(tr.cells).map(function(td){return td.innerText.trim();}));});var csv=rows.map(function(r){return r.map(function(v){return '"'+String(v).replace(/"/g,'""')+'"';}).join(',');}).join('\r\n');var a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='cabinet-maker-materials.csv';a.click();URL.revokeObjectURL(a.href);}</script>
<?php init_tail(); ?><div class="modal fade" id="cmImportMaterials"><div class="modal-dialog"><div class="modal-content"><?= form_open_multipart(admin_url('cabinet_maker/import_materials')); ?><div class="modal-header"><h4><?= _l('cabinet_maker_import'); ?></h4></div><div class="modal-body"><input type="file" name="file" accept=".csv" required class="form-control"></div><div class="modal-footer"><button class="btn btn-primary"><?= _l('cabinet_maker_import'); ?></button></div><?= form_close(); ?></div></div></div>