<?php defined('BASEPATH') or exit('No direct script access allowed'); init_head(); $v=$verification ?? []; ?>
<div id="wrapper"><div class="content usi-seo"><div class="panel_s"><div class="panel-body">
<?php $this->load->view('usi_smartchoice_seo/partials/top'); ?>
<div class="sc-toolbar"><h4><i class="fa fa-check-circle"></i> <?php echo html_escape($title); ?></h4><a class="btn btn-default btn-sm" href="<?php echo admin_url('usi_smartchoice_seo/field_verifications'); ?>"><i class="fa fa-arrow-left"></i> Back</a></div>
<?php echo form_open(admin_url('usi_smartchoice_seo/field_verification/'.(int)($v['id'] ?? 0))); ?>
<div class="row"><div class="col-md-6"><div class="form-group"><label>Verification Title</label><input type="text" name="verification_title" class="form-control" value="<?php echo html_escape($v['verification_title'] ?? ''); ?>" required></div></div><div class="col-md-2"><div class="form-group"><label>AI Estimate ID</label><input type="number" name="ai_estimate_id" class="form-control" value="<?php echo (int)($v['ai_estimate_id'] ?? 0); ?>"></div></div><div class="col-md-2"><div class="form-group"><label>Customer ID</label><input type="number" name="customer_id" class="form-control" value="<?php echo (int)($v['customer_id'] ?? 0); ?>"></div></div><div class="col-md-2"><div class="form-group"><label>Project ID</label><input type="number" name="project_id" class="form-control" value="<?php echo (int)($v['project_id'] ?? 0); ?>"></div></div></div>
<div class="row"><div class="col-md-6"><div class="form-group"><label>Jobsite Address</label><input type="text" name="jobsite_address" class="form-control" value="<?php echo html_escape($v['jobsite_address'] ?? ''); ?>"></div></div><div class="col-md-3"><div class="form-group"><label>Status</label><select name="field_status" class="form-control"><?php foreach(['pending'=>'Pending','in_progress'=>'In Progress','verified'=>'Verified','needs_revision'=>'Needs Revision','blocked'=>'Blocked'] as $k=>$label){ ?><option value="<?php echo $k; ?>" <?php echo (($v['field_status'] ?? 'pending')===$k?'selected':''); ?>><?php echo $label; ?></option><?php } ?></select></div></div><div class="col-md-3"><label>&nbsp;</label><div class="checkbox checkbox-primary"><input type="checkbox" id="ready_for_estimate" name="ready_for_estimate" value="1" <?php echo ((int)($v['ready_for_estimate'] ?? 0)===1?'checked':''); ?>><label for="ready_for_estimate">Ready For Estimate</label></div></div></div>
<div class="form-group"><label>Measurement Summary</label><textarea name="measurement_summary" class="form-control" rows="5"><?php echo html_escape($v['measurement_summary'] ?? ''); ?></textarea></div>
<div class="form-group"><label>Inspection Checklist</label><textarea name="inspection_checklist" class="form-control" rows="7"><?php echo html_escape($v['inspection_checklist'] ?? 'Verify customer name and jobsite address.\nVerify measurements.\nVerify photos are clear.\nVerify service scope.\nVerify exclusions.\nVerify access, parking, power, water, and material staging.'); ?></textarea></div>
<div class="form-group"><label>Photo Notes</label><textarea name="photo_notes" class="form-control" rows="5"><?php echo html_escape($v['photo_notes'] ?? ''); ?></textarea></div>
<button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Save Verification</button>
<?php echo form_close(); ?>
</div></div></div></div><?php init_tail(); ?>