<?php defined('BASEPATH') or exit('No direct script access allowed'); init_head(); ?>
<div id="wrapper"><div class="content"><div class="row"><div class="col-md-12"><div class="panel_s"><div class="panel-body">
<h4 class="tw-mt-0"><?php echo _l('notes_edit_note'); ?></h4><hr>
<?php echo form_open_multipart(admin_url('notes/notes/update_note/'.(int)$note->id)); ?><div class="row">
<div class="col-md-6"><?php echo render_input('title','notes_title',$note->title ?? '',['required'=>true]); ?></div>
<div class="col-md-3"><label><?php echo _l('lead_add_edit_source'); ?></label><select class="selectpicker" name="rel_type" data-width="100%"><?php foreach($rel_type as $key=>$source){ ?><option value="<?php echo html_escape($key); ?>" <?php echo $key===$note->rel_type?'selected':''; ?>><?php echo html_escape($source['name']); ?></option><?php } ?></select></div>
<div class="col-md-3"><?php echo render_input('rel_id','tasks_dt_name',(int)$note->rel_id,'number'); ?></div>
<div class="col-md-3"><label><?php echo _l('notes_type'); ?></label><select class="selectpicker" name="note_type" data-width="100%"><?php foreach($note_types as $key=>$type){ ?><option value="<?php echo html_escape($key); ?>" <?php echo $key===($note->note_type??'general')?'selected':''; ?>><?php echo html_escape($type['name']); ?></option><?php } ?></select></div>
<div class="col-md-3"><label><?php echo _l('notes_priority'); ?></label><select class="selectpicker" name="priority" data-width="100%"><?php foreach(['low','medium','high','urgent'] as $p){ ?><option value="<?php echo $p; ?>" <?php echo $p===($note->priority??'medium')?'selected':''; ?>><?php echo _l('notes_priority_'.$p); ?></option><?php } ?></select></div>
<div class="col-md-3"><label><?php echo _l('notes_brand_color'); ?></label><select class="selectpicker" name="note_color" data-width="100%"><?php foreach($brand_colors as $hex=>$name){ ?><option value="<?php echo $hex; ?>" <?php echo strtoupper($hex)===strtoupper($note->note_color??'')?'selected':''; ?>><?php echo html_escape($name.' '.$hex); ?></option><?php } ?></select></div>
<div class="col-md-3"><label><?php echo _l('notes_assign_to_staff'); ?></label><select class="selectpicker" name="assigned_staff_id" data-width="100%"><option value=""></option><?php foreach($staffs as $staff){ ?><option value="<?php echo (int)$staff->staffid; ?>" <?php echo (int)$staff->staffid===(int)($note->assigned_staff_id??0)?'selected':''; ?>><?php echo html_escape($staff->fullname); ?></option><?php } ?></select></div>
<div class="col-md-12 mtop15"><?php echo render_textarea('description','note_description',$note->description,['class'=>'tinymce','rows'=>12]); ?></div><div class="col-md-6"><?php echo render_input('attachment','notes_attachment','','file'); ?></div>
</div><div class="text-right"><a href="<?php echo admin_url('notes/notes/view/'.(int)$note->id); ?>" class="btn btn-default"><?php echo _l('cancel'); ?></a> <button class="btn btn-primary"><i class="fa fa-save"></i> <?php echo _l('update_note'); ?></button></div><?php echo form_close(); ?>
</div></div></div></div></div></div><?php init_tail(); ?><script>$(function(){init_editor('.tinymce');});</script></body></html>
