<?php defined('BASEPATH') or exit('No direct script access allowed'); ?>
<?php init_head(); ?>
<div id="wrapper"><div class="content"><?php echo sammy_ai_nav(); ?><div class="row">
<div class="col-md-4"><div class="panel_s"><div class="panel-body"><h4>New Training Course</h4><?php echo form_open(admin_url('usi_smartchoice_seo/save_learning_course')); ?>
<div class="form-group"><label>Course Title</label><input type="text" name="course_title" class="form-control" required></div>
<div class="form-group"><label>Course Type</label><select name="course_type" class="form-control"><option value="crm_training">CRM Training</option><option value="estimating">Estimating</option><option value="field">Field Operations</option><option value="safety">Safety</option><option value="admin">Administration</option></select></div>
<div class="form-group"><label>Target Role</label><input type="text" name="target_role" class="form-control"></div>
<div class="form-group"><label>Status</label><select name="status" class="form-control"><option value="draft">Draft</option><option value="active">Active</option><option value="archived">Archived</option></select></div>
<div class="form-group"><label>Description</label><textarea name="description" rows="5" class="form-control"></textarea></div><button class="btn btn-primary btn-sm">Save Course</button><?php echo form_close(); ?></div></div></div>
<div class="col-md-8"><div class="panel_s"><div class="panel-body"><div class="clearfix"><h4 class="pull-left">AI Learning & Training Center</h4><div class="pull-right"><a class="btn btn-default btn-sm" href="<?php echo admin_url('usi_smartchoice_seo/learning_center'); ?>">Reload</a></div></div><hr>
<div class="table-responsive"><table class="table table-striped table-condensed sc-compact-table"><thead><tr><th>Course</th><th>Type</th><th>Role</th><th>Status</th><th>Updated</th></tr></thead><tbody><?php if (empty($courses)) { ?><tr><td colspan="5" class="text-center text-muted">No training courses found.</td></tr><?php } foreach ($courses as $course) { ?><tr><td><strong><?php echo html_escape($course['course_title']); ?></strong><br><span class="text-muted"><?php echo html_escape($course['description']); ?></span></td><td><?php echo html_escape(ucwords(str_replace('_',' ', $course['course_type']))); ?></td><td><?php echo html_escape($course['target_role']); ?></td><td><?php echo html_escape(ucwords($course['status'])); ?></td><td><?php echo html_escape($course['updated_at']); ?></td></tr><?php } ?></tbody></table></div>
</div></div></div></div></div></div><?php init_tail(); ?></body></html>