<?php defined('BASEPATH') or exit('No direct script access allowed'); init_head(); ?>
<div id="wrapper"><div class="content"><div class="panel_s"><div class="panel-body">
<?php $this->load->view('usi_smartchoice_seo/partials/top'); ?>
<div class="sc-toolbar"><h4><i class="fa fa-check-square-o"></i> <?php echo html_escape($title); ?></h4><div class="sc-toolbar-actions"><?php if ($estimate) { ?><a class="btn btn-success btn-sm" href="<?php echo admin_url('usi_smartchoice_seo/calculate_ai_estimate/' . (int)$estimate['id']); ?>">Calculate Numbers</a><a class="btn btn-info btn-sm" href="<?php echo admin_url('usi_smartchoice_seo/prepare_customer_scope/' . (int)$estimate['id']); ?>">Prepare Customer Scope</a><a class="btn btn-primary btn-sm" href="<?php echo admin_url('usi_smartchoice_seo/create_crm_estimate_from_ai/' . (int)$estimate['id']); ?>">Create CRM Estimate Draft</a><a class="btn btn-success btn-sm" href="<?php echo admin_url('usi_smartchoice_seo/build_customer_package/' . (int)$estimate['id']); ?>">Build Customer Package</a><?php } ?><a class="btn btn-default btn-sm" href="<?php echo admin_url('usi_smartchoice_seo/estimate_review_queue'); ?>">Back</a></div></div>
<?php if ($estimate) { ?>
<div class="row"><div class="col-md-3"><div class="sc-card"><div class="sc-card-count"><?php echo app_format_money((float)$estimate['total'], get_base_currency()); ?></div><div class="sc-card-label">Total</div></div></div><div class="col-md-3"><div class="sc-card"><div class="sc-card-count"><?php echo html_escape((string)($estimate['pricing_confidence'] ?? '0')); ?>%</div><div class="sc-card-label">Confidence</div></div></div><div class="col-md-3"><div class="sc-card"><div class="sc-card-count"><?php echo html_escape((string)($estimate['review_status'] ?? 'draft')); ?></div><div class="sc-card-label">Review Status</div></div></div><div class="col-md-3"><div class="sc-card"><div class="sc-card-count"><?php echo !empty($estimate['field_verified']) ? 'Yes' : 'No'; ?></div><div class="sc-card-label">Field Verified</div></div></div></div>
<?php echo form_open(admin_url('usi_smartchoice_seo/save_estimate_review/' . (int)$estimate['id'])); ?>
<div class="row"><div class="col-md-4"><label>Review Status</label><select name="review_status" class="form-control"><?php foreach (['draft','in_review','needs_revision','approved'] as $status) { ?><option value="<?php echo html_escape($status); ?>" <?php echo (($estimate['review_status'] ?? 'draft') === $status) ? 'selected' : ''; ?>><?php echo ucwords(str_replace('_',' ',$status)); ?></option><?php } ?></select></div><div class="col-md-4"><label>Field Verified</label><select name="field_verified" class="form-control"><option value="0" <?php echo empty($estimate['field_verified']) ? 'selected' : ''; ?>>No</option><option value="1" <?php echo !empty($estimate['field_verified']) ? 'selected' : ''; ?>>Yes</option></select></div><div class="col-md-4"><label>CRM Estimate ID</label><input type="text" class="form-control" readonly value="<?php echo (int)($estimate['converted_estimate_id'] ?? 0); ?>"></div></div>
<div class="row mtop15"><div class="col-md-12"><label>Customer Scope</label><textarea name="customer_scope" rows="7" class="form-control"><?php echo html_escape((string)($estimate['customer_scope'] ?? '')); ?></textarea></div></div>
<div class="row mtop15"><div class="col-md-6"><label>Exclusions</label><textarea name="exclusions" rows="5" class="form-control"><?php echo html_escape((string)($estimate['exclusions'] ?? '')); ?></textarea></div><div class="col-md-6"><label>Payment Schedule</label><textarea name="payment_schedule" rows="5" class="form-control"><?php echo html_escape((string)($estimate['payment_schedule'] ?? '')); ?></textarea></div></div>
<div class="row mtop15"><div class="col-md-12"><label>Estimator Review Notes</label><textarea name="estimator_review_notes" rows="4" class="form-control"><?php echo html_escape((string)($estimate['estimator_review_notes'] ?? '')); ?></textarea></div></div>
<div class="sc-toolbar-actions mtop15"><button type="submit" class="btn btn-primary btn-sm">Save Review</button></div><?php echo form_close(); ?>
<div class="row mtop15"><div class="col-md-6"><?php echo form_open(admin_url('usi_smartchoice_seo/approve_ai_estimate/' . (int)$estimate['id'])); ?><label>Approval Notes</label><textarea name="approval_notes" rows="3" class="form-control"></textarea><button type="submit" class="btn btn-success btn-sm mtop10">Approve Estimate</button><?php echo form_close(); ?></div><div class="col-md-6"><?php echo form_open(admin_url('usi_smartchoice_seo/mark_ai_estimate_needs_revision/' . (int)$estimate['id'])); ?><label>Revision Notes</label><textarea name="revision_notes" rows="3" class="form-control"></textarea><button type="submit" class="btn btn-warning btn-sm mtop10">Needs Revision</button><?php echo form_close(); ?></div></div>
<h5 class="mtop20">Calculated Line Items</h5><div class="table-responsive"><table class="table table-striped table-condensed sc-table"><thead><tr><th>#</th><th>Description</th><th>Scope Detail</th><th>Qty</th><th>Unit</th><th>Rate</th><th>Total</th><th>Confidence</th></tr></thead><tbody><?php foreach (($lines ?? []) as $line) { ?><tr><td><?php echo (int)$line['line_order']; ?></td><td><?php echo html_escape($line['description']); ?></td><td><?php echo html_escape($line['long_description']); ?></td><td><?php echo html_escape($line['quantity']); ?></td><td><?php echo html_escape($line['unit']); ?></td><td><?php echo app_format_money((float)$line['unit_rate'], get_base_currency()); ?></td><td><?php echo app_format_money((float)$line['line_total'], get_base_currency()); ?></td><td><?php echo html_escape($line['confidence']); ?>%</td></tr><?php } ?><?php if (empty($lines)) { ?><tr><td colspan="8" class="text-center text-muted">No calculated line items yet.</td></tr><?php } ?></tbody></table></div>
<h5>Review Log</h5><div class="table-responsive"><table class="table table-striped table-condensed sc-table"><thead><tr><th>Action</th><th>Notes</th><th>Staff</th><th>Date</th></tr></thead><tbody><?php foreach (($approval_log ?? []) as $log) { ?><tr><td><?php echo html_escape($log['action']); ?></td><td><?php echo nl2br(html_escape((string)$log['notes'])); ?></td><td><?php echo (int)$log['created_by']; ?></td><td><?php echo html_escape($log['created_at']); ?></td></tr><?php } ?><?php if (empty($approval_log)) { ?><tr><td colspan="4" class="text-center text-muted">No review log yet.</td></tr><?php } ?></tbody></table></div>
<?php } ?>
</div></div></div></div><?php init_tail(); ?>
