<?php
defined('BASEPATH') or exit('No direct script access allowed');
$template=$proposal['template']??[];
$contract=!empty($proposal['include_contract'])?($analysis['contract']??null):null;
$img=function($name){return solar_pro_pdf_image_src($name);};
$yearsToShow=[1,2,3,4,5,10,20,25];
$panelWarranty=(int)($analysis['panel_equipment']['warranty_years']??0);
?>
<style>
body{font-family:helvetica;color:#24343b}.hero{background:#0E6F5B;color:#fff;padding:24px}.hero h1,.hero h2{color:#fff}.hero h1{font-size:27px}.hero h2{font-size:20px}.section-title{font-size:19px;color:#0E6F5B;margin-top:18px}.lead{font-size:10px;color:#5b6870;line-height:1.55}.grid{width:100%;border-collapse:collapse}.grid td,.grid th{padding:7px;border:1px solid #d9e2e7}.kpi td{background:#f4f8f8;text-align:center}.impact td{text-align:center;vertical-align:top;background:#fbfcfc}.year-table th{background:#0E6F5B;color:#fff}.year-table tr:nth-child(even) td{background:#f3f8f8}.product{width:100%;border:1px solid #d9e2e7}.product td{padding:10px;vertical-align:top}.warranty{background:#eef7f4;border:1px solid #cfe2dc;padding:12px}.visual{width:100%;max-height:250px}.small{font-size:8.5px;color:#66747a}.pagebreak{page-break-before:always;height:1px}.brand1{background:#0E6F5B;color:#fff}.brand2{background:#3598DB;color:#fff}.brand3{background:#169179;color:#fff}.brand4{background:#F28C28;color:#fff}
</style>
<div class="hero"><h1><?php echo html_escape(get_option('companyname')); ?></h1><h2><?php echo html_escape($template['hero_title']??_l('solar_pro_power_your_future')); ?></h2><p><?php echo html_escape(trim($analysis['first_name'].' '.$analysis['last_name'])); ?> — <?php echo html_escape($analysis['address']); ?></p><p><?php echo number_format($analysis['system_kw'],2); ?> kW · <?php echo (int)$analysis['panel_count']; ?> <?php echo _l('solar_pro_panels'); ?> · <?php echo number_format($analysis['solar_offset_pct'],0); ?>% <?php echo _l('solar_pro_offset'); ?></p></div>
<?php echo $template['intro_html']??''; ?>

<h2 class="section-title">01 · <?php echo _l('solar_pro_financial_future'); ?></h2>
<p class="lead"><?php echo _l('solar_pro_financial_story'); ?></p>
<table class="grid kpi"><tr><td><?php echo _l('solar_pro_est_monthly_payment'); ?><br><b><?php echo app_format_money($finance['monthly_payment'],get_base_currency()); ?></b></td><td><?php echo _l('solar_pro_monthly_savings'); ?><br><b><?php echo app_format_money($finance['monthly_savings'],get_base_currency()); ?></b></td><td><?php echo _l('solar_pro_annual_savings'); ?><br><b><?php echo app_format_money($finance['annual_savings'],get_base_currency()); ?></b></td><td>25 <?php echo _l('solar_pro_years'); ?><br><b><?php echo app_format_money($finance['projections'][25],get_base_currency()); ?></b></td></tr></table>
<br>
<table class="grid year-table"><thead><tr><th width="12%"><?php echo _l('solar_pro_year'); ?></th><th width="30%"><?php echo _l('solar_pro_projected_annual_savings'); ?></th><th width="30%"><?php echo _l('solar_pro_projected_cumulative_savings'); ?></th><th width="28%"><?php echo _l('solar_pro_projection_value'); ?></th></tr></thead><tbody><?php foreach($yearsToShow as $i=>$y):$r=$finance['yearly'][$y]??null;if(!$r)continue;?><tr><td><?php echo $y; ?></td><td><?php echo app_format_money($r['annual_savings'],get_base_currency()); ?></td><td><?php echo app_format_money($r['cumulative_savings'],get_base_currency()); ?></td><td class="brand<?php echo ($i%4)+1; ?>"><?php echo app_format_money($r['cumulative_net'],get_base_currency()); ?></td></tr><?php endforeach;?></tbody></table>
<p class="small"><?php echo sprintf(_l('solar_pro_projection_assumption'),number_format($finance['utility_escalation_pct'],1),number_format((float)solar_pro_setting('solar_pro_solar_degradation_pct',.5),1)); ?></p>

<h2 class="section-title">02 · <?php echo _l('solar_pro_planet_impact'); ?></h2><p class="lead"><?php echo _l('solar_pro_planet_story'); ?></p>
<table class="grid impact"><tr><td><?php if($img('co2-impact.png')):?><img src="<?php echo $img('co2-impact.png'); ?>" height="105"><br><?php endif; ?><b><?php echo number_format($environment['co2_tons'],1); ?></b><br><?php echo _l('solar_pro_metric_tons_co2'); ?></td><td><?php if($img('trees-impact.png')):?><img src="<?php echo $img('trees-impact.png'); ?>" height="105"><br><?php endif; ?><b><?php echo number_format($environment['trees'],0); ?></b><br><?php echo _l('solar_pro_tree_equivalent'); ?></td><td><?php if($img('clean-energy.png')):?><img src="<?php echo $img('clean-energy.png'); ?>" height="105"><br><?php endif; ?><b><?php echo number_format($analysis['annual_production_kwh']); ?></b><br>kWh <?php echo _l('solar_pro_clean_energy_year'); ?></td><td><?php if($img('cars-impact.png')):?><img src="<?php echo $img('cars-impact.png'); ?>" height="105"><br><?php endif; ?><b><?php echo number_format($environment['cars']??0,1); ?></b><br><?php echo _l('solar_pro_car_equivalent'); ?></td></tr></table>
<p class="small"><?php echo _l('solar_pro_environment_disclaimer'); ?></p>

<h2 class="section-title">03 · <?php echo _l('solar_pro_your_system'); ?></h2><p class="lead"><?php echo _l('solar_pro_system_story'); ?></p>
<?php if($img('solar-energy-flow.png')):?><img class="visual" src="<?php echo $img('solar-energy-flow.png'); ?>"><?php endif; ?>
<table class="grid"><tr><td><?php echo _l('solar_pro_system_size'); ?><br><b><?php echo number_format($analysis['system_kw'],2); ?> kW</b></td><td><?php echo _l('solar_pro_panels'); ?><br><b><?php echo (int)$analysis['panel_count']; ?></b></td><td><?php echo _l('solar_pro_annual_generation'); ?><br><b><?php echo number_format($analysis['annual_production_kwh']); ?> kWh</b></td><td><?php echo _l('solar_pro_system_price'); ?><br><b><?php echo app_format_money($analysis['system_price'],get_base_currency()); ?></b></td></tr></table>
<br>
<table class="product"><tr><td width="35%"><?php if($img('enphase-iq8.png')):?><img src="<?php echo $img('enphase-iq8.png'); ?>" width="220"><?php endif; ?></td><td><h3><?php echo _l('solar_pro_iq8_title'); ?></h3><p><?php echo _l('solar_pro_iq8_description'); ?></p></td></tr></table><br>
<table class="product"><tr><td width="35%"><?php if($img('enphase-gateway.png')):?><img src="<?php echo $img('enphase-gateway.png'); ?>" width="220"><?php endif; ?></td><td><h3><?php echo _l('solar_pro_gateway_title'); ?></h3><p><?php echo _l('solar_pro_gateway_description'); ?></p></td></tr></table>
<div class="warranty"><h3><?php echo _l('solar_pro_warranty_title'); ?></h3><p>• <?php echo _l('solar_pro_iq8_warranty'); ?><br>• <?php echo _l('solar_pro_gateway_warranty'); ?><?php if($panelWarranty>0): ?><br>• <?php echo sprintf(_l('solar_pro_panel_warranty_dynamic'),$panelWarranty); ?><?php endif; ?></p><p class="small"><?php echo _l('solar_pro_enphase_product_note'); ?></p></div>

<h2 class="section-title">04 · <?php echo _l('solar_pro_installation_flow'); ?></h2><p class="lead"><?php echo _l('solar_pro_installation_story'); ?></p><?php if($img('installation-flow.png')):?><img class="visual" src="<?php echo $img('installation-flow.png'); ?>"><?php endif; ?>
<table class="grid"><tr>
<?php foreach(['solar_pro_flow_sunlight','solar_pro_flow_panels','solar_pro_flow_microinverters','solar_pro_flow_disconnect','solar_pro_flow_gateway','solar_pro_flow_main_panel','solar_pro_flow_home'] as $flowKey): ?><td style="text-align:center;font-size:8px"><b><?php echo _l($flowKey); ?></b></td><?php endforeach; ?>
</tr></table>

<h2 class="section-title">05 · <?php echo _l('solar_pro_discussion'); ?></h2><?php if(empty($proposal['comments'])):?><p><?php echo _l('solar_pro_no_discussion'); ?></p><?php else:foreach($proposal['comments'] as $c):?><p><b><?php echo html_escape($c['staff_id']?get_staff_full_name($c['staff_id']):$c['contact_name']); ?>:</b> <?php echo nl2br(html_escape($c['message'])); ?></p><?php endforeach;endif;?><?php echo $template['closing_html']??''; ?>

<?php foreach(['panel_equipment','inverter_equipment'] as $ek):$eq=$analysis[$ek]??null;if(!$eq)continue;?><div class="pagebreak"></div><h1><?php echo html_escape(trim($eq['manufacturer'].' '.$eq['model'])); ?> — <?php echo _l('solar_pro_equipment_specs'); ?></h1><table class="grid"><tr><th><?php echo _l('solar_pro_type'); ?></th><td><?php echo html_escape(solar_pro_humanize($eq['type'])); ?></td><th><?php echo _l('solar_pro_warranty_years'); ?></th><td><?php echo html_escape($eq['warranty_years']); ?></td></tr><tr><th><?php echo _l('solar_pro_dc_watts'); ?></th><td><?php echo html_escape($eq['watts']); ?></td><th><?php echo _l('solar_pro_ac_watts'); ?></th><td><?php echo html_escape($eq['ac_watts']); ?></td></tr></table><?php $pre=json_decode($eq['spec_preview_json']??'[]',true);if(is_array($pre)):foreach($pre as $pn):$pp=FCPATH.'uploads/solar_pro/equipment/'.(int)$eq['id'].'/'.$pn;if(is_file($pp)):?><p><img src="<?php echo $pp; ?>" style="max-width:100%;max-height:700px"></p><?php endif;endforeach;endif;?><?php endforeach;?>
<?php if($contract):?><div class="pagebreak"></div><h1><?php echo html_escape($contract['title']); ?></h1><?php echo solar_pro_render_contract_content($contract,$analysis,false); ?><?php endif;?>
