<?php

defined('BASEPATH') or exit('No direct script access allowed');

class Enterprise_schema
{
    public static function install()
    {
        $CI = &get_instance();
        $prefix = db_prefix();
        $charset = preg_replace('/[^a-zA-Z0-9_]/', '', (string) ($CI->db->char_set ?: 'utf8'));
        $collation = preg_replace('/[^a-zA-Z0-9_]/', '', (string) ($CI->db->dbcollat ?: 'utf8_general_ci'));
        $oldDebug = $CI->db->db_debug;
        $CI->db->db_debug = false;

        $tables = self::definitions();
        foreach ($tables as $suffix => $definition) {
            $table = $prefix . $suffix;
            if ($CI->db->table_exists($table)) {
                continue;
            }
            $sql = "CREATE TABLE IF NOT EXISTS `{$table}` ({$definition}) ENGINE=InnoDB DEFAULT CHARSET={$charset} COLLATE={$collation}";
            if ($CI->db->query($sql) === false) {
                $error = $CI->db->error();
                log_message('error', 'Smart Choice Enterprise schema failed for ' . $table . ': ' . ($error['message'] ?? 'Unknown database error'));
            }
        }
        $CI->db->db_debug = $oldDebug;
        self::seedFeatureFlags();
        self::setOptions();
        return true;
    }

    private static function definitions()
    {
        return [
            'sce_events' => "`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`event_key` VARCHAR(191) NOT NULL,`aggregate_type` VARCHAR(100) DEFAULT NULL,`aggregate_id` VARCHAR(100) DEFAULT NULL,`payload` LONGTEXT NULL,`context` LONGTEXT NULL,`staff_id` INT DEFAULT NULL,`correlation_id` VARCHAR(64) DEFAULT NULL,`created_at` DATETIME NOT NULL,PRIMARY KEY (`id`),KEY `event_key_created` (`event_key`,`created_at`),KEY `aggregate_lookup` (`aggregate_type`,`aggregate_id`)",
            'sce_queue_jobs' => "`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`queue_name` VARCHAR(100) NOT NULL DEFAULT 'default',`job_key` VARCHAR(191) NOT NULL,`handler` VARCHAR(191) NOT NULL,`payload` LONGTEXT NULL,`status` VARCHAR(30) NOT NULL DEFAULT 'pending',`priority` INT NOT NULL DEFAULT 100,`attempts` INT NOT NULL DEFAULT 0,`max_attempts` INT NOT NULL DEFAULT 3,`available_at` DATETIME NOT NULL,`reserved_at` DATETIME DEFAULT NULL,`completed_at` DATETIME DEFAULT NULL,`failed_at` DATETIME DEFAULT NULL,`last_error` TEXT NULL,`created_by` INT DEFAULT NULL,`created_at` DATETIME NOT NULL,`updated_at` DATETIME DEFAULT NULL,PRIMARY KEY (`id`),UNIQUE KEY `job_key` (`job_key`),KEY `queue_status_available` (`queue_name`,`status`,`available_at`,`priority`)",
            'sce_feature_flags' => "`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,`feature_key` VARCHAR(191) NOT NULL,`name` VARCHAR(191) NOT NULL,`description` TEXT NULL,`is_enabled` TINYINT(1) NOT NULL DEFAULT 0,`scope_type` VARCHAR(30) NOT NULL DEFAULT 'global',`scope_id` VARCHAR(100) DEFAULT NULL,`configuration` LONGTEXT NULL,`created_by` INT DEFAULT NULL,`updated_by` INT DEFAULT NULL,`created_at` DATETIME NOT NULL,`updated_at` DATETIME DEFAULT NULL,PRIMARY KEY (`id`),KEY `feature_scope_lookup` (`feature_key`,`scope_type`,`scope_id`)",
            'sce_audit_log' => "`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`action` VARCHAR(100) NOT NULL,`entity_type` VARCHAR(100) DEFAULT NULL,`entity_id` VARCHAR(100) DEFAULT NULL,`staff_id` INT DEFAULT NULL,`ip_address` VARCHAR(45) DEFAULT NULL,`user_agent` VARCHAR(500) DEFAULT NULL,`before_data` LONGTEXT NULL,`after_data` LONGTEXT NULL,`metadata` LONGTEXT NULL,`created_at` DATETIME NOT NULL,PRIMARY KEY (`id`),KEY `entity_lookup` (`entity_type`,`entity_id`),KEY `staff_created` (`staff_id`,`created_at`)",
            'sce_field_permissions' => "`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,`resource_type` VARCHAR(100) NOT NULL,`field_key` VARCHAR(191) NOT NULL,`role_id` INT NOT NULL DEFAULT 0,`staff_id` INT NOT NULL DEFAULT 0,`can_view` TINYINT(1) NOT NULL DEFAULT 1,`can_edit` TINYINT(1) NOT NULL DEFAULT 0,`can_export` TINYINT(1) NOT NULL DEFAULT 0,`created_by` INT DEFAULT NULL,`updated_by` INT DEFAULT NULL,`created_at` DATETIME NOT NULL,`updated_at` DATETIME DEFAULT NULL,PRIMARY KEY (`id`),UNIQUE KEY `field_subject` (`resource_type`,`field_key`,`role_id`,`staff_id`)",
            'sce_api_clients' => "`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,`name` VARCHAR(191) NOT NULL,`public_key` VARCHAR(64) NOT NULL,`secret_hash` VARCHAR(255) NOT NULL,`scopes` TEXT NULL,`allowed_ips` TEXT NULL,`is_active` TINYINT(1) NOT NULL DEFAULT 1,`last_used_at` DATETIME DEFAULT NULL,`expires_at` DATETIME DEFAULT NULL,`created_by` INT DEFAULT NULL,`created_at` DATETIME NOT NULL,`updated_at` DATETIME DEFAULT NULL,PRIMARY KEY (`id`),UNIQUE KEY `public_key` (`public_key`)",
            'sce_customer_properties' => "`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`client_id` INT NOT NULL,`property_name` VARCHAR(191) NOT NULL,`property_type` VARCHAR(100) DEFAULT NULL,`address` VARCHAR(255) DEFAULT NULL,`city` VARCHAR(100) DEFAULT NULL,`state` VARCHAR(100) DEFAULT NULL,`zip` VARCHAR(30) DEFAULT NULL,`country` INT DEFAULT NULL,`is_primary` TINYINT(1) NOT NULL DEFAULT 0,`year_built` INT DEFAULT NULL,`square_feet` DECIMAL(15,2) DEFAULT NULL,`notes` TEXT NULL,`created_by` INT DEFAULT NULL,`created_at` DATETIME NOT NULL,`updated_at` DATETIME DEFAULT NULL,PRIMARY KEY (`id`),KEY `client_primary` (`client_id`,`is_primary`)",
            'sce_customer_household' => "`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`client_id` INT NOT NULL,`contact_id` INT DEFAULT NULL,`full_name` VARCHAR(191) NOT NULL,`relationship` VARCHAR(100) DEFAULT NULL,`email` VARCHAR(191) DEFAULT NULL,`phone` VARCHAR(50) DEFAULT NULL,`is_emergency_contact` TINYINT(1) NOT NULL DEFAULT 0,`is_authorized` TINYINT(1) NOT NULL DEFAULT 0,`notes` TEXT NULL,`created_by` INT DEFAULT NULL,`created_at` DATETIME NOT NULL,`updated_at` DATETIME DEFAULT NULL,PRIMARY KEY (`id`),KEY `client_household` (`client_id`)",
            'sce_customer_preferences' => "`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`client_id` INT NOT NULL,`preference_key` VARCHAR(191) NOT NULL,`preference_value` TEXT NULL,`created_by` INT DEFAULT NULL,`created_at` DATETIME NOT NULL,`updated_at` DATETIME DEFAULT NULL,PRIMARY KEY (`id`),UNIQUE KEY `client_preference` (`client_id`,`preference_key`)",
            'sce_customer_scores' => "`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`client_id` INT NOT NULL,`customer_score` DECIMAL(8,2) DEFAULT NULL,`health_score` DECIMAL(8,2) DEFAULT NULL,`lifetime_value` DECIMAL(15,2) NOT NULL DEFAULT 0,`calculation_data` LONGTEXT NULL,`calculated_at` DATETIME NOT NULL,PRIMARY KEY (`id`),KEY `client_calculated` (`client_id`,`calculated_at`)",
            'sce_customer_timeline' => "`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`client_id` INT NOT NULL,`event_type` VARCHAR(100) NOT NULL,`title` VARCHAR(191) NOT NULL,`description` TEXT NULL,`related_type` VARCHAR(100) DEFAULT NULL,`related_id` VARCHAR(100) DEFAULT NULL,`event_at` DATETIME NOT NULL,`created_by` INT DEFAULT NULL,`created_at` DATETIME NOT NULL,PRIMARY KEY (`id`),KEY `client_event` (`client_id`,`event_at`)",
            'sce_customer_categories' => "`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,`name` VARCHAR(191) NOT NULL,`description` TEXT NULL,`color` VARCHAR(20) DEFAULT NULL,`created_at` DATETIME NOT NULL,PRIMARY KEY (`id`),UNIQUE KEY `name` (`name`)",
            'sce_customer_category_links' => "`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`client_id` INT NOT NULL,`category_id` INT NOT NULL,`created_at` DATETIME NOT NULL,PRIMARY KEY (`id`),UNIQUE KEY `client_category` (`client_id`,`category_id`)",
            'sce_relationship_assignments' => "`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`client_id` INT NOT NULL,`staff_id` INT NOT NULL,`relationship_type` VARCHAR(100) NOT NULL DEFAULT 'manager',`is_primary` TINYINT(1) NOT NULL DEFAULT 0,`created_at` DATETIME NOT NULL,PRIMARY KEY (`id`),KEY `client_staff` (`client_id`,`staff_id`)",
            'sce_pinned_records' => "`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`staff_id` INT NOT NULL,`record_type` VARCHAR(100) NOT NULL,`record_id` VARCHAR(100) NOT NULL,`label` VARCHAR(191) NOT NULL,`url` VARCHAR(500) DEFAULT NULL,`created_at` DATETIME NOT NULL,PRIMARY KEY (`id`),UNIQUE KEY `staff_record` (`staff_id`,`record_type`,`record_id`)",
            'sce_opportunities' => "`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`client_id` INT DEFAULT NULL,`lead_id` INT DEFAULT NULL,`project_id` INT DEFAULT NULL,`name` VARCHAR(191) NOT NULL,`stage` VARCHAR(80) NOT NULL DEFAULT 'new',`amount` DECIMAL(15,2) NOT NULL DEFAULT 0,`probability` DECIMAL(5,2) NOT NULL DEFAULT 0,`expected_close_date` DATE DEFAULT NULL,`owner_staff_id` INT DEFAULT NULL,`source` VARCHAR(100) DEFAULT NULL,`status` VARCHAR(30) NOT NULL DEFAULT 'open',`notes` TEXT NULL,`created_by` INT DEFAULT NULL,`created_at` DATETIME NOT NULL,`updated_at` DATETIME DEFAULT NULL,PRIMARY KEY (`id`),KEY `stage_status` (`stage`,`status`),KEY `owner_close` (`owner_staff_id`,`expected_close_date`)",
            'sce_sales_goals' => "`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`staff_id` INT DEFAULT NULL,`goal_type` VARCHAR(80) NOT NULL,`period_start` DATE NOT NULL,`period_end` DATE NOT NULL,`target_value` DECIMAL(15,2) NOT NULL DEFAULT 0,`actual_value` DECIMAL(15,2) NOT NULL DEFAULT 0,`created_at` DATETIME NOT NULL,`updated_at` DATETIME DEFAULT NULL,PRIMARY KEY (`id`),KEY `staff_period` (`staff_id`,`period_start`,`period_end`)",
            'sce_sales_commissions' => "`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`staff_id` INT NOT NULL,`opportunity_id` BIGINT DEFAULT NULL,`invoice_id` INT DEFAULT NULL,`commission_type` VARCHAR(50) NOT NULL DEFAULT 'percentage',`rate` DECIMAL(8,4) NOT NULL DEFAULT 0,`base_amount` DECIMAL(15,2) NOT NULL DEFAULT 0,`commission_amount` DECIMAL(15,2) NOT NULL DEFAULT 0,`status` VARCHAR(30) NOT NULL DEFAULT 'pending',`earned_at` DATETIME DEFAULT NULL,`paid_at` DATETIME DEFAULT NULL,`created_at` DATETIME NOT NULL,PRIMARY KEY (`id`),KEY `staff_status` (`staff_id`,`status`)",
            'sce_field_visits' => "`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`project_id` INT DEFAULT NULL,`task_id` INT DEFAULT NULL,`client_id` INT DEFAULT NULL,`property_id` BIGINT DEFAULT NULL,`technician_id` INT NOT NULL,`crew_id` BIGINT DEFAULT NULL,`scheduled_start` DATETIME DEFAULT NULL,`scheduled_end` DATETIME DEFAULT NULL,`check_in_at` DATETIME DEFAULT NULL,`check_out_at` DATETIME DEFAULT NULL,`latitude` DECIMAL(10,7) DEFAULT NULL,`longitude` DECIMAL(10,7) DEFAULT NULL,`status` VARCHAR(40) NOT NULL DEFAULT 'scheduled',`notes` TEXT NULL,`created_at` DATETIME NOT NULL,`updated_at` DATETIME DEFAULT NULL,PRIMARY KEY (`id`),KEY `technician_schedule` (`technician_id`,`scheduled_start`),KEY `project_status` (`project_id`,`status`)",
            'sce_time_clock' => "`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`staff_id` INT NOT NULL,`field_visit_id` BIGINT DEFAULT NULL,`entry_type` VARCHAR(30) NOT NULL,`entry_at` DATETIME NOT NULL,`latitude` DECIMAL(10,7) DEFAULT NULL,`longitude` DECIMAL(10,7) DEFAULT NULL,`notes` VARCHAR(500) DEFAULT NULL,`created_at` DATETIME NOT NULL,PRIMARY KEY (`id`),KEY `staff_entry` (`staff_id`,`entry_at`)",
            'sce_crews' => "`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`name` VARCHAR(191) NOT NULL,`leader_staff_id` INT DEFAULT NULL,`status` VARCHAR(30) NOT NULL DEFAULT 'active',`notes` TEXT NULL,`created_at` DATETIME NOT NULL,`updated_at` DATETIME DEFAULT NULL,PRIMARY KEY (`id`),UNIQUE KEY `name` (`name`)",
            'sce_crew_members' => "`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`crew_id` BIGINT NOT NULL,`staff_id` INT NOT NULL,`role_name` VARCHAR(100) DEFAULT NULL,`active_from` DATE DEFAULT NULL,`active_to` DATE DEFAULT NULL,PRIMARY KEY (`id`),UNIQUE KEY `crew_staff` (`crew_id`,`staff_id`)",
            'sce_daily_logs' => "`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`project_id` INT NOT NULL,`field_visit_id` BIGINT DEFAULT NULL,`log_date` DATE NOT NULL,`weather` VARCHAR(100) DEFAULT NULL,`labor_summary` TEXT NULL,`work_completed` TEXT NULL,`materials_used` TEXT NULL,`delays` TEXT NULL,`safety_notes` TEXT NULL,`created_by` INT DEFAULT NULL,`created_at` DATETIME NOT NULL,PRIMARY KEY (`id`),KEY `project_date` (`project_id`,`log_date`)",
            'sce_dispatch_assignments' => "`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`field_visit_id` BIGINT NOT NULL,`technician_id` INT NOT NULL,`vehicle_id` BIGINT DEFAULT NULL,`route_order` INT NOT NULL DEFAULT 0,`dispatch_status` VARCHAR(40) NOT NULL DEFAULT 'assigned',`assigned_at` DATETIME NOT NULL,`acknowledged_at` DATETIME DEFAULT NULL,`created_by` INT DEFAULT NULL,PRIMARY KEY (`id`),KEY `technician_status` (`technician_id`,`dispatch_status`)",
            'sce_technician_skills' => "`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`staff_id` INT NOT NULL,`skill_name` VARCHAR(191) NOT NULL,`skill_level` VARCHAR(50) DEFAULT NULL,`certification_expires` DATE DEFAULT NULL,`notes` TEXT NULL,PRIMARY KEY (`id`),UNIQUE KEY `staff_skill` (`staff_id`,`skill_name`)",
            'sce_equipment' => "`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`client_id` INT DEFAULT NULL,`property_id` BIGINT DEFAULT NULL,`project_id` INT DEFAULT NULL,`equipment_name` VARCHAR(191) NOT NULL,`equipment_type` VARCHAR(100) DEFAULT NULL,`manufacturer` VARCHAR(100) DEFAULT NULL,`model_number` VARCHAR(100) DEFAULT NULL,`serial_number` VARCHAR(191) DEFAULT NULL,`asset_tag` VARCHAR(100) DEFAULT NULL,`installed_at` DATE DEFAULT NULL,`warranty_expires` DATE DEFAULT NULL,`status` VARCHAR(40) NOT NULL DEFAULT 'active',`notes` TEXT NULL,`created_at` DATETIME NOT NULL,`updated_at` DATETIME DEFAULT NULL,PRIMARY KEY (`id`),UNIQUE KEY `serial_number` (`serial_number`),KEY `client_property` (`client_id`,`property_id`)",
            'sce_equipment_service' => "`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`equipment_id` BIGINT NOT NULL,`project_id` INT DEFAULT NULL,`service_type` VARCHAR(100) NOT NULL,`service_date` DATE NOT NULL,`technician_id` INT DEFAULT NULL,`description` TEXT NULL,`cost` DECIMAL(15,2) NOT NULL DEFAULT 0,`next_service_date` DATE DEFAULT NULL,`created_at` DATETIME NOT NULL,PRIMARY KEY (`id`),KEY `equipment_date` (`equipment_id`,`service_date`)",
            'sce_inventory_locations' => "`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`name` VARCHAR(191) NOT NULL,`location_type` VARCHAR(50) NOT NULL DEFAULT 'warehouse',`vehicle_id` BIGINT DEFAULT NULL,`address` VARCHAR(255) DEFAULT NULL,`status` VARCHAR(30) NOT NULL DEFAULT 'active',`created_at` DATETIME NOT NULL,PRIMARY KEY (`id`),UNIQUE KEY `name` (`name`)",
            'sce_inventory_items' => "`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`item_code` VARCHAR(100) NOT NULL,`name` VARCHAR(191) NOT NULL,`description` TEXT NULL,`unit` VARCHAR(50) DEFAULT NULL,`barcode` VARCHAR(191) DEFAULT NULL,`qr_value` VARCHAR(500) DEFAULT NULL,`minimum_stock` DECIMAL(15,3) NOT NULL DEFAULT 0,`average_cost` DECIMAL(15,4) NOT NULL DEFAULT 0,`vendor_id` INT DEFAULT NULL,`status` VARCHAR(30) NOT NULL DEFAULT 'active',`created_at` DATETIME NOT NULL,`updated_at` DATETIME DEFAULT NULL,PRIMARY KEY (`id`),UNIQUE KEY `item_code` (`item_code`),KEY `barcode` (`barcode`)",
            'sce_inventory_stock' => "`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`item_id` BIGINT NOT NULL,`location_id` BIGINT NOT NULL,`quantity` DECIMAL(15,3) NOT NULL DEFAULT 0,`reserved_quantity` DECIMAL(15,3) NOT NULL DEFAULT 0,`updated_at` DATETIME NOT NULL,PRIMARY KEY (`id`),UNIQUE KEY `item_location` (`item_id`,`location_id`)",
            'sce_inventory_movements' => "`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`item_id` BIGINT NOT NULL,`from_location_id` BIGINT DEFAULT NULL,`to_location_id` BIGINT DEFAULT NULL,`movement_type` VARCHAR(40) NOT NULL,`quantity` DECIMAL(15,3) NOT NULL,`unit_cost` DECIMAL(15,4) NOT NULL DEFAULT 0,`project_id` INT DEFAULT NULL,`reference_type` VARCHAR(100) DEFAULT NULL,`reference_id` VARCHAR(100) DEFAULT NULL,`created_by` INT DEFAULT NULL,`created_at` DATETIME NOT NULL,PRIMARY KEY (`id`),KEY `item_created` (`item_id`,`created_at`)",
            'sce_project_phases' => "`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`project_id` INT NOT NULL,`name` VARCHAR(191) NOT NULL,`sequence_no` INT NOT NULL DEFAULT 0,`start_date` DATE DEFAULT NULL,`due_date` DATE DEFAULT NULL,`completed_at` DATETIME DEFAULT NULL,`status` VARCHAR(40) NOT NULL DEFAULT 'not_started',`budget_amount` DECIMAL(15,2) NOT NULL DEFAULT 0,`actual_cost` DECIMAL(15,2) NOT NULL DEFAULT 0,`created_at` DATETIME NOT NULL,`updated_at` DATETIME DEFAULT NULL,PRIMARY KEY (`id`),KEY `project_sequence` (`project_id`,`sequence_no`)",
            'sce_rfis' => "`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`project_id` INT NOT NULL,`rfi_number` VARCHAR(100) NOT NULL,`subject` VARCHAR(191) NOT NULL,`question` TEXT NOT NULL,`response` TEXT NULL,`status` VARCHAR(40) NOT NULL DEFAULT 'open',`due_date` DATE DEFAULT NULL,`assigned_to` INT DEFAULT NULL,`created_by` INT DEFAULT NULL,`created_at` DATETIME NOT NULL,`answered_at` DATETIME DEFAULT NULL,PRIMARY KEY (`id`),UNIQUE KEY `project_rfi` (`project_id`,`rfi_number`)",
            'sce_submittals' => "`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`project_id` INT NOT NULL,`submittal_number` VARCHAR(100) NOT NULL,`title` VARCHAR(191) NOT NULL,`specification_section` VARCHAR(100) DEFAULT NULL,`status` VARCHAR(40) NOT NULL DEFAULT 'pending',`submitted_at` DATETIME DEFAULT NULL,`reviewed_at` DATETIME DEFAULT NULL,`reviewed_by` INT DEFAULT NULL,`notes` TEXT NULL,`created_at` DATETIME NOT NULL,PRIMARY KEY (`id`),UNIQUE KEY `project_submittal` (`project_id`,`submittal_number`)",
            'sce_permits' => "`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`project_id` INT NOT NULL,`permit_type` VARCHAR(100) NOT NULL,`permit_number` VARCHAR(100) DEFAULT NULL,`jurisdiction` VARCHAR(191) DEFAULT NULL,`status` VARCHAR(40) NOT NULL DEFAULT 'planned',`applied_date` DATE DEFAULT NULL,`issued_date` DATE DEFAULT NULL,`expiration_date` DATE DEFAULT NULL,`inspection_status` VARCHAR(80) DEFAULT NULL,`notes` TEXT NULL,`created_at` DATETIME NOT NULL,PRIMARY KEY (`id`),KEY `project_status` (`project_id`,`status`)",
            'sce_change_orders' => "`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`project_id` INT NOT NULL,`change_number` VARCHAR(100) NOT NULL,`title` VARCHAR(191) NOT NULL,`description` TEXT NULL,`amount` DECIMAL(15,2) NOT NULL DEFAULT 0,`cost_impact` DECIMAL(15,2) NOT NULL DEFAULT 0,`days_impact` INT NOT NULL DEFAULT 0,`status` VARCHAR(40) NOT NULL DEFAULT 'draft',`approved_at` DATETIME DEFAULT NULL,`created_by` INT DEFAULT NULL,`created_at` DATETIME NOT NULL,PRIMARY KEY (`id`),UNIQUE KEY `project_change` (`project_id`,`change_number`)",
            'sce_document_versions' => "`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`entity_type` VARCHAR(100) NOT NULL,`entity_id` VARCHAR(100) NOT NULL,`document_name` VARCHAR(191) NOT NULL,`file_name` VARCHAR(255) NOT NULL,`file_path` VARCHAR(500) NOT NULL,`mime_type` VARCHAR(100) DEFAULT NULL,`version_no` INT NOT NULL DEFAULT 1,`status` VARCHAR(40) NOT NULL DEFAULT 'current',`checksum` VARCHAR(64) DEFAULT NULL,`uploaded_by` INT DEFAULT NULL,`uploaded_at` DATETIME NOT NULL,PRIMARY KEY (`id`),KEY `entity_document` (`entity_type`,`entity_id`,`document_name`)",
            'sce_document_approvals' => "`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`document_version_id` BIGINT NOT NULL,`approver_staff_id` INT DEFAULT NULL,`approver_contact_id` INT DEFAULT NULL,`status` VARCHAR(40) NOT NULL DEFAULT 'pending',`comments` TEXT NULL,`requested_at` DATETIME NOT NULL,`responded_at` DATETIME DEFAULT NULL,PRIMARY KEY (`id`),KEY `document_status` (`document_version_id`,`status`)",
            'sce_communications' => "`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`channel` VARCHAR(30) NOT NULL,`direction` VARCHAR(20) NOT NULL,`entity_type` VARCHAR(50) DEFAULT NULL,`entity_id` VARCHAR(100) DEFAULT NULL,`from_address` VARCHAR(191) DEFAULT NULL,`to_address` VARCHAR(191) DEFAULT NULL,`subject` VARCHAR(255) DEFAULT NULL,`body` LONGTEXT NULL,`status` VARCHAR(40) NOT NULL DEFAULT 'queued',`external_id` VARCHAR(191) DEFAULT NULL,`staff_id` INT DEFAULT NULL,`created_at` DATETIME NOT NULL,PRIMARY KEY (`id`),KEY `entity_created` (`entity_type`,`entity_id`,`created_at`)",
            'sce_call_logs' => "`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`call_sid` VARCHAR(191) DEFAULT NULL,`direction` VARCHAR(20) NOT NULL,`from_number` VARCHAR(50) DEFAULT NULL,`to_number` VARCHAR(50) DEFAULT NULL,`status` VARCHAR(40) NOT NULL DEFAULT 'queued',`duration_seconds` INT NOT NULL DEFAULT 0,`staff_id` INT DEFAULT NULL,`client_id` INT DEFAULT NULL,`lead_id` INT DEFAULT NULL,`started_at` DATETIME DEFAULT NULL,`answered_at` DATETIME DEFAULT NULL,`ended_at` DATETIME DEFAULT NULL,`recording_url` VARCHAR(500) DEFAULT NULL,`has_recording` TINYINT(1) NOT NULL DEFAULT 0,`notes` TEXT NULL,`created_at` DATETIME NOT NULL,PRIMARY KEY (`id`),UNIQUE KEY `call_sid` (`call_sid`),KEY `phone_created` (`to_number`,`created_at`)",
            'sce_call_recordings' => "`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`call_log_id` BIGINT NOT NULL,`recording_sid` VARCHAR(191) DEFAULT NULL,`recording_url` VARCHAR(500) NOT NULL,`duration_seconds` INT NOT NULL DEFAULT 0,`status` VARCHAR(40) DEFAULT NULL,`created_at` DATETIME NOT NULL,PRIMARY KEY (`id`),KEY `call_log_id` (`call_log_id`)",
            'sce_campaigns' => "`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`name` VARCHAR(191) NOT NULL,`campaign_type` VARCHAR(50) NOT NULL,`status` VARCHAR(40) NOT NULL DEFAULT 'draft',`budget` DECIMAL(15,2) NOT NULL DEFAULT 0,`spend` DECIMAL(15,2) NOT NULL DEFAULT 0,`start_date` DATE DEFAULT NULL,`end_date` DATE DEFAULT NULL,`created_by` INT DEFAULT NULL,`created_at` DATETIME NOT NULL,PRIMARY KEY (`id`)",
            'sce_campaign_attribution' => "`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`campaign_id` BIGINT NOT NULL,`lead_id` INT DEFAULT NULL,`client_id` INT DEFAULT NULL,`opportunity_id` BIGINT DEFAULT NULL,`revenue` DECIMAL(15,2) NOT NULL DEFAULT 0,`attributed_at` DATETIME NOT NULL,PRIMARY KEY (`id`),KEY `campaign_id` (`campaign_id`)",
            'sce_review_requests' => "`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`client_id` INT NOT NULL,`project_id` INT DEFAULT NULL,`channel` VARCHAR(30) NOT NULL DEFAULT 'email',`status` VARCHAR(40) NOT NULL DEFAULT 'pending',`review_url` VARCHAR(500) DEFAULT NULL,`sent_at` DATETIME DEFAULT NULL,`completed_at` DATETIME DEFAULT NULL,`created_at` DATETIME NOT NULL,PRIMARY KEY (`id`)",
            'sce_workflows' => "`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`name` VARCHAR(191) NOT NULL,`trigger_type` VARCHAR(100) NOT NULL,`entity_type` VARCHAR(50) DEFAULT NULL,`is_active` TINYINT(1) NOT NULL DEFAULT 0,`conditions_json` LONGTEXT NULL,`created_by` INT DEFAULT NULL,`created_at` DATETIME NOT NULL,`updated_at` DATETIME DEFAULT NULL,PRIMARY KEY (`id`)",
            'sce_workflow_steps' => "`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`workflow_id` BIGINT NOT NULL,`step_order` INT NOT NULL DEFAULT 0,`action_type` VARCHAR(100) NOT NULL,`configuration_json` LONGTEXT NULL,`delay_minutes` INT NOT NULL DEFAULT 0,PRIMARY KEY (`id`),KEY `workflow_order` (`workflow_id`,`step_order`)",
            'sce_workflow_runs' => "`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`workflow_id` BIGINT NOT NULL,`entity_type` VARCHAR(50) DEFAULT NULL,`entity_id` VARCHAR(100) DEFAULT NULL,`status` VARCHAR(40) NOT NULL DEFAULT 'queued',`started_at` DATETIME DEFAULT NULL,`completed_at` DATETIME DEFAULT NULL,`error_message` TEXT NULL,`created_at` DATETIME NOT NULL,PRIMARY KEY (`id`)",
            'sce_report_definitions' => "`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`name` VARCHAR(191) NOT NULL,`report_type` VARCHAR(100) NOT NULL,`configuration_json` LONGTEXT NULL,`created_by` INT DEFAULT NULL,`created_at` DATETIME NOT NULL,`updated_at` DATETIME DEFAULT NULL,PRIMARY KEY (`id`)",
            'sce_scheduled_reports' => "`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`report_id` BIGINT NOT NULL,`frequency` VARCHAR(40) NOT NULL,`recipients` TEXT NOT NULL,`format` VARCHAR(10) NOT NULL DEFAULT 'pdf',`next_run_at` DATETIME DEFAULT NULL,`last_run_at` DATETIME DEFAULT NULL,`is_active` TINYINT(1) NOT NULL DEFAULT 1,PRIMARY KEY (`id`)",
            'sce_qr_codes' => "`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`name` VARCHAR(191) NOT NULL,`qr_type` VARCHAR(50) NOT NULL,`payload` LONGTEXT NOT NULL,`is_dynamic` TINYINT(1) NOT NULL DEFAULT 0,`status` VARCHAR(40) NOT NULL DEFAULT 'active',`expires_at` DATETIME DEFAULT NULL,`scan_count` INT UNSIGNED NOT NULL DEFAULT 0,`logo_path` VARCHAR(500) DEFAULT NULL,`foreground_color` VARCHAR(20) DEFAULT NULL,`background_color` VARCHAR(20) DEFAULT NULL,`created_by` INT DEFAULT NULL,`created_at` DATETIME NOT NULL,PRIMARY KEY (`id`)",
            'sce_qr_scans' => "`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`qr_code_id` BIGINT NOT NULL,`ip_address` VARCHAR(45) DEFAULT NULL,`user_agent` VARCHAR(500) DEFAULT NULL,`referrer` VARCHAR(500) DEFAULT NULL,`country` VARCHAR(100) DEFAULT NULL,`city` VARCHAR(100) DEFAULT NULL,`scanned_at` DATETIME NOT NULL,PRIMARY KEY (`id`),KEY `qr_scanned` (`qr_code_id`,`scanned_at`)",
            'sce_security_rules' => "`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`rule_type` VARCHAR(50) NOT NULL,`name` VARCHAR(191) NOT NULL,`value` TEXT NULL,`is_active` TINYINT(1) NOT NULL DEFAULT 1,`created_by` INT DEFAULT NULL,`created_at` DATETIME NOT NULL,PRIMARY KEY (`id`)",
            'sce_login_audit' => "`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`staff_id` INT DEFAULT NULL,`email` VARCHAR(191) DEFAULT NULL,`ip_address` VARCHAR(45) DEFAULT NULL,`user_agent` VARCHAR(500) DEFAULT NULL,`status` VARCHAR(30) NOT NULL,`occurred_at` DATETIME NOT NULL,PRIMARY KEY (`id`),KEY `staff_occurred` (`staff_id`,`occurred_at`)",
            'sce_performance_metrics' => "`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`metric_key` VARCHAR(100) NOT NULL,`metric_value` DECIMAL(20,6) NOT NULL DEFAULT 0,`metric_unit` VARCHAR(30) DEFAULT NULL,`context_json` LONGTEXT NULL,`recorded_at` DATETIME NOT NULL,PRIMARY KEY (`id`),KEY `metric_recorded` (`metric_key`,`recorded_at`)",
            'sce_favorites' => "`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`staff_id` INT NOT NULL,`label` VARCHAR(191) NOT NULL,`url` VARCHAR(500) NOT NULL,`icon` VARCHAR(100) DEFAULT NULL,`position` INT NOT NULL DEFAULT 0,`created_at` DATETIME NOT NULL,PRIMARY KEY (`id`),KEY `staff_position` (`staff_id`,`position`)",
            'sce_quick_actions' => "`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`action_key` VARCHAR(100) NOT NULL,`name` VARCHAR(191) NOT NULL,`url` VARCHAR(500) NOT NULL,`icon` VARCHAR(100) DEFAULT NULL,`permission_key` VARCHAR(100) DEFAULT NULL,`is_active` TINYINT(1) NOT NULL DEFAULT 1,PRIMARY KEY (`id`),UNIQUE KEY `action_key` (`action_key`)",
        ];
    }

    private static function seedFeatureFlags()
    {
        $CI = &get_instance();
        $table = db_prefix() . 'sce_feature_flags';
        if (!$CI->db->table_exists($table)) return;
        $flags = [
            ['enterprise_foundation','Enterprise Foundation','Shared services, queue, audit, API and permissions.',1],
            ['customer_360','Customer 360','Customer timeline, properties, household and scoring.',1],
            ['sales_operations','Sales Operations','Opportunities, forecasting, goals and commissions.',1],
            ['field_operations','Field Operations','Visits, crews, time clock and daily logs.',1],
            ['dispatch','Dispatch','Assignments, routes and technician skills.',1],
            ['equipment_inventory','Equipment and Inventory','Equipment history, locations, stock and movements.',1],
            ['project_controls','Project Controls','Phases, RFIs, submittals, permits and change orders.',1],
            ['document_center','Document Center','Document version and approval foundation.',1],
            ['enterprise_api','Enterprise API Foundation','Disabled until an API client is explicitly created.',0],
            ['communications','Communications','Unified communication timeline and channel records.',1],
            ['call_center','Call Center','Twilio calling, call logs and recording metadata.',1],
            ['marketing','Marketing','Campaigns, attribution and review requests.',1],
            ['workflows','Workflow Automation','Triggers, steps, runs and scheduled execution.',1],
            ['reporting','Reporting','Report definitions and scheduled delivery.',1],
            ['qr_center','QR Code Center','Static and dynamic QR generation and tracking.',1],
            ['security_center','Security Center','Security rules, login history and field policies.',1],
            ['performance_center','Performance Center','Runtime, queue and database health metrics.',1],
        ];
        foreach ($flags as $flag) {
            $exists = $CI->db->where('feature_key',$flag[0])->where('scope_type','global')->get($table)->row();
            if (!$exists) $CI->db->insert($table,['feature_key'=>$flag[0],'name'=>$flag[1],'description'=>$flag[2],'is_enabled'=>$flag[3],'scope_type'=>'global','scope_id'=>null,'created_by'=>function_exists('get_staff_user_id')?(get_staff_user_id()?:null):null,'created_at'=>date('Y-m-d H:i:s')]);
        }
    }

    private static function setOptions()
    {
        $options = ['smart_choice_enterprise_core_enabled'=>'1','smart_choice_enterprise_core_version'=>'1.5.0','smart_choice_enterprise_queue_batch_size'=>'10','smart_choice_enterprise_queue_max_attempts'=>'3'];
        foreach ($options as $name=>$value) {
            if (get_option($name)==='') add_option($name,$value); else update_option($name,$value);
        }
    }
}
