<?php defined('BASEPATH') or exit('No direct script access allowed'); $portal_lang = solar_pro_public_language_code($portal_lang ?? 'en'); $sp_l = static function($key) use ($portal_lang){ return solar_pro_public_l($key, $portal_lang); }; $other_lang = $portal_lang === 'en' ? 'es' : 'en'; ?>
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?php echo html_escape($title); ?></title><link rel="stylesheet" href="<?php echo module_dir_url('solar_pro','assets/css/solar-pro-public.css?v='.SOLAR_PRO_VERSION); ?>"></head><body>
<div class="sp-public"><div class="sp-public-hero"><div class="sp-crm-logo"><?php get_dark_company_logo(); ?></div><span><?php echo $sp_l('solar_pro_smart_choice_solar'); ?></span><h1><?php echo $sp_l('solar_pro_free_solar_report'); ?></h1><p><?php echo $sp_l('solar_pro_public_intro'); ?></p><div class="sp-language-toggle"><a href="<?php echo site_url('solar_pro/estimate?lang='.$other_lang); ?>" class="sp-language-button"><i class="fa fa-language"></i> <?php echo $sp_l($portal_lang === 'en' ? 'solar_pro_translate_spanish' : 'solar_pro_translate_english'); ?></a></div><?php if(solar_pro_appointment_url()): ?><div class="sp-appointment-cta"><a href="<?php echo html_escape(solar_pro_appointment_url()); ?>" target="_blank" rel="noopener" class="sp-secondary sp-appointment-button"><?php echo $sp_l('solar_pro_schedule_consultation'); ?></a></div><?php endif; ?></div>
<div class="sp-form-card"><?php if(!empty($error)): ?><div class="sp-alert error"><?php echo html_escape($error); ?></div><?php endif; ?><?php echo form_open(site_url('solar_pro/estimate?lang='.$portal_lang), ['enctype'=>'multipart/form-data']); ?><input type="hidden" name="portal_lang" value="<?php echo html_escape($portal_lang); ?>"><div class="sp-required-notice"><?php echo $sp_l('solar_pro_required_fields_notice'); ?></div>
<div class="sp-grid">
<label class="<?php echo !empty($field_errors['first_name'])?'sp-field-error':''; ?>"><?php echo $sp_l('solar_pro_first_name'); ?> <strong class="sp-required">*</strong><input name="first_name" value="<?php echo html_escape($old['first_name'] ?? ''); ?>" required aria-required="true"><?php if(!empty($field_errors['first_name'])): ?><small><?php echo html_escape($field_errors['first_name']); ?></small><?php endif; ?></label>
<label class="<?php echo !empty($field_errors['last_name'])?'sp-field-error':''; ?>"><?php echo $sp_l('solar_pro_last_name'); ?> <strong class="sp-required">*</strong><input name="last_name" value="<?php echo html_escape($old['last_name'] ?? ''); ?>" required aria-required="true"><?php if(!empty($field_errors['last_name'])): ?><small><?php echo html_escape($field_errors['last_name']); ?></small><?php endif; ?></label>
<label class="<?php echo !empty($field_errors['email'])?'sp-field-error':''; ?>"><?php echo $sp_l('solar_pro_email'); ?> <strong class="sp-required">*</strong><input type="email" name="email" value="<?php echo html_escape($old['email'] ?? ''); ?>" required aria-required="true"><?php if(!empty($field_errors['email'])): ?><small><?php echo html_escape($field_errors['email']); ?></small><?php endif; ?></label>
<label class="<?php echo !empty($field_errors['phone'])?'sp-field-error':''; ?>"><?php echo $sp_l('solar_pro_phone'); ?> <strong class="sp-required">*</strong><input name="phone" type="tel" value="<?php echo html_escape($old['phone'] ?? ''); ?>" required aria-required="true"><?php if(!empty($field_errors['phone'])): ?><small><?php echo html_escape($field_errors['phone']); ?></small><?php endif; ?></label>
</div>
<label class="<?php echo !empty($field_errors['address'])?'sp-field-error':''; ?>"><?php echo $sp_l('solar_pro_address'); ?> <strong class="sp-required">*</strong><input name="address" value="<?php echo html_escape($old['address'] ?? ''); ?>" required aria-required="true"><?php if(!empty($field_errors['address'])): ?><small><?php echo html_escape($field_errors['address']); ?></small><?php endif; ?></label><div class="sp-grid three"><label><?php echo $sp_l('solar_pro_city'); ?><input name="city"></label><label><?php echo $sp_l('solar_pro_state'); ?><input name="state" value="<?php echo html_escape(solar_pro_setting('solar_pro_default_state','FL')); ?>"></label><label><?php echo $sp_l('solar_pro_zip'); ?><input name="zip"></label></div>
<div class="sp-grid"><label><?php echo $sp_l('solar_pro_annual_consumption_kwh'); ?><input type="number" min="1" step="0.01" name="annual_consumption_kwh" required></label><label><?php echo $sp_l('solar_pro_average_monthly_bill'); ?><input type="number" min="0" step="0.01" name="average_monthly_bill"></label></div>
<div class="sp-grid"><label><?php echo $sp_l('solar_pro_utility'); ?><select name="utility_id"><option value=""><?php echo $sp_l('solar_pro_select_utility'); ?></option><?php foreach($utilities as $u): ?><option value="<?php echo $u['id']; ?>"><?php echo html_escape($u['name']); ?></option><?php endforeach; ?></select></label><label><?php echo $sp_l('solar_pro_panel_size'); ?><select name="panel_watts"><option value="400">400 W</option><option value="440" selected>440 W</option></select></label></div>
<div class="sp-card-lite"><h3><?php echo $sp_l('solar_pro_analysis_method'); ?></h3><label class="sp-choice"><input type="radio" name="analysis_method" value="google_solar" checked> <strong><?php echo $sp_l('solar_pro_google_solar'); ?></strong> — <?php echo $sp_l('solar_pro_google_method_desc'); ?></label><label class="sp-choice"><input type="radio" name="analysis_method" value="quick_estimate"> <strong><?php echo $sp_l('solar_pro_quick_estimate'); ?></strong> — <?php echo $sp_l('solar_pro_fallback_method_desc'); ?></label></div><div class="sp-upload-card"><h3><?php echo $sp_l('solar_pro_upload_documents'); ?></h3><p class="sp-small"><?php echo $sp_l('solar_pro_upload_documents_help'); ?></p><label><?php echo $sp_l('solar_pro_government_id'); ?><input type="file" name="id_document[]" accept="image/*,.pdf" multiple></label><label><?php echo $sp_l('solar_pro_electric_bill'); ?><input type="file" name="electric_bill[]" accept="image/*,.pdf" multiple></label><label><?php echo $sp_l('solar_pro_noc'); ?><input type="file" name="noc[]" accept="image/*,.pdf" multiple></label><label><?php echo $sp_l('solar_pro_property_photos'); ?><input type="file" name="property_photos[]" accept="image/*" multiple></label></div><button class="sp-button" type="submit"><?php echo $sp_l('solar_pro_analyze_my_home'); ?></button><p class="sp-small"><?php echo $sp_l('solar_pro_estimate_disclaimer'); ?></p><?php echo form_close(); ?></div></div></body></html>
