<?php defined('BASEPATH') or exit('No direct script access allowed'); init_head(); $p=$post_data??null; ?>
<div id="wrapper"><div class="content publishx-scope"><div class="row"><div class="col-md-12"><?php echo form_open_multipart(admin_url('publishx/post/'.($p->id??'')),['id'=>'publishx-form']); ?><div class="panel_s"><div class="panel-body"><h3 class="tw-mt-0"><i class="fa-regular fa-newspaper"></i> <?php echo _l('publishx_create_post'); ?></h3><hr>
<div class="row"><div class="col-md-8">
<?php echo render_input('post_title','publishx_tbl_post_title',$p->post_title??''); ?>
<div class="row"><div class="col-md-8"><?php echo render_input('post_slug','publishx_post_slug',$p->post_slug??''); ?></div><div class="col-md-4"><button type="button" class="btn btn-default publishx-ai" data-field="post_title"><i class="fa fa-robot"></i> AI Title</button></div></div>
<?php echo render_textarea('short_content','publishx_tbl_post_short_content',$p->short_content??'', ['rows'=>4],[], '', 'tinymce'); ?><button type="button" class="btn btn-default publishx-ai" data-field="short_content"><i class="fa fa-robot"></i> AI Summary</button>
<?php echo render_textarea('full_content','publishx_post_full_content',$p->full_content??'', ['rows'=>14],[], '', 'tinymce'); ?><button type="button" class="btn btn-primary publishx-ai" data-field="full_content"><i class="fa fa-robot"></i> AI Write / Improve Article</button>
<hr><h4>SEO</h4><div class="form-group"><label>SEO AI Instructions</label><div class="input-group"><input class="form-control" id="ai_prompt" placeholder="Example: Target homeowners in Spring Hill searching for kitchen remodeling"><span class="input-group-btn"><button type="button" class="btn btn-info publishx-ai" data-field="seo_instructions"><i class="fa fa-wand-magic-sparkles"></i> Generate SEO Instructions</button></span></div></div>
<?php echo render_input('meta_title','publishx_meta_title',$p->meta_title??''); ?><button type="button" class="btn btn-info btn-xs publishx-ai" data-field="meta_title"><i class="fa fa-magic"></i> Generate Meta Title</button>
<?php echo render_textarea('meta_description','publishx_meta_description',$p->meta_description??'', ['rows'=>3]); ?><button type="button" class="btn btn-default btn-xs publishx-ai" data-field="meta_description">Generate with AI</button>
<?php echo render_input('meta_keywords','publishx_meta_keywords',$p->meta_keywords??''); ?><button type="button" class="btn btn-default btn-xs publishx-ai" data-field="meta_keywords">Generate with AI</button>
</div><div class="col-md-4">
<div class="publishx-side-card"><h4>Website Publishing</h4><?php echo render_select('website_id',$websites,['id','name'],'publishx_website',$p->website_id??''); ?><?php echo render_input('target_folder','publishx_target_folder',$p->target_folder??(get_option('publishx_default_target_folder')?:'services/engineering')); ?><p class="text-muted">Example: <code>services/engineering</code>. The website profile controls the shared header and footer includes.</p></div>
<div class="publishx-side-card"><h4>Classification</h4><?php echo render_select('category_id',$post_categories,['id','category_name'],'publishx_post_category',$p->category_id??''); ?><?php echo render_select('language_id',$post_languages,['id','name'],'publishx_post_language',$p->language_id??''); ?><?php echo render_select('template_key',$templates,['id','title'],'publishx_template',$p->template_key??'smart_choice_pro'); ?><?php echo render_select('status',publishx_post_statuses(),['value','name'],'publishx_post_status',$p->status??1); ?><?php echo render_datetime_input('scheduled','publishx_scheduled',$p->scheduled??''); ?></div>
<div class="publishx-side-card"><h4>Media</h4><?php echo render_input('hero_video_url','Video (YouTube ID, YouTube/Vimeo URL, or uploaded video URL)',$p->hero_video_url??''); ?><p class="text-muted">YouTube: paste the video ID after <code>watch?v=</code>, or paste the full YouTube/Vimeo link. Uploaded formats: MP4, WebM, OGG.</p><label>Upload your own video</label><input type="file" name="hero_video_file" class="form-control" accept="video/mp4,video/webm,video/ogg"><input type="hidden" name="featured_image_url" id="featured_image_url" value="<?php echo html_escape($p->featured_image_url??''); ?>"><div class="publishx-media-choice"><button type="button" class="btn btn-default" data-toggle="collapse" data-target="#publishx-upload-box"><i class="fa fa-upload"></i> Upload Image</button><button type="button" class="btn btn-info" data-toggle="modal" data-target="#publishx-media-modal"><i class="fa fa-images"></i> Choose from Blogging Library</button></div><div id="publishx-upload-box" class="collapse tw-mt-2"><label><?php echo _l('publishx_upload_feature_image'); ?></label><input type="file" name="featured_image" class="form-control"></div><div id="publishx-selected-preview" class="tw-mt-2"><?php if(!empty($p)){?><img src="<?php echo html_escape(publishx_feature_image_url($p)); ?>" class="img-responsive publishx-selected-image"><?php }?></div><a class="btn btn-default btn-block tw-mt-2" href="<?php echo admin_url('publishx/media'); ?>"><i class="fa fa-folder-open"></i> Manage Blogging Media Folder</a></div>
<?php if(!empty($p->published_url)){?><div class="alert alert-success"><a target="_blank" href="<?php echo html_escape($p->published_url); ?>"><?php echo html_escape($p->published_url); ?></a></div><?php }?>
</div></div></div><div class="panel-footer text-right"><?php if(!empty($p->id) && has_permission('publishx_posts','','delete')){ ?><a href="<?php echo admin_url('publishx/delete_post/'.(int)$p->id); ?>" class="btn btn-danger pull-left _delete"><i class="fa fa-trash"></i> Delete Post</a><?php } ?><a href="<?php echo admin_url('publishx/posts'); ?>" class="btn btn-default">Back</a><button class="btn btn-primary" type="submit">Save</button><button class="btn btn-success" type="submit" name="publish_now" value="1"><i class="fa fa-upload"></i> Save & Publish to Website</button></div></div><?php echo form_close(); ?></div></div></div></div>
<div class="modal fade" id="publishx-media-modal" tabindex="-1"><div class="modal-dialog modal-lg"><div class="modal-content"><div class="modal-header"><button type="button" class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Choose from Blogging Media Library</h4></div><div class="modal-body"><div class="publishx-media-grid"><?php foreach($media as $m){ if($m['type']!=='image') continue; ?><button type="button" class="publishx-media-picker" data-url="<?php echo html_escape($m['url']); ?>"><img src="<?php echo html_escape($m['url']); ?>"><span><?php echo html_escape($m['name']); ?></span></button><?php } ?></div><?php if(empty($media)){?><div class="alert alert-info">No Blogging media has been uploaded yet. Use Blogging → Media to upload images.</div><?php }?></div></div></div></div><?php init_tail(); ?><script>$(function(){$('.publishx-media-picker').on('click',function(){var u=$(this).data('url');$('#featured_image_url').val(u);$('#publishx-selected-preview').html('<img src="'+u+'" class="img-responsive publishx-selected-image">');$('#publishx-media-modal').modal('hide');});$('.publishx-ai').on('click',function(){var b=$(this),f=b.data('field');b.prop('disabled',true);$.post('<?php echo admin_url('publishx/ai'); ?>',{field:f,title:$('#post_title').val(),prompt:$('#ai_prompt').val()},function(r){if(r.status!=='ok'){alert_float('danger',r.message);return;}var ed=tinymce.get(f);if(ed){ed.setContent(r.content);}else{$('#'+f).val(r.content);}alert_float('success','AI content created.');},'json').always(function(){b.prop('disabled',false);});});});</script></body></html>