<?php defined('BASEPATH') or exit('No direct script access allowed'); ?>
<?php init_head(); ?>
<div id="wrapper"><div class="content usi-seo"><div class="row"><div class="col-md-12">
<?php $this->load->view('usi_smartchoice_seo/partials/top'); ?>
<div class="panel_s"><div class="panel-body"><div class="usi-toolbar"><h4><?php echo _l('usi_smartchoice_seo_reports'); ?></h4><div class="usi-actions">
<a href="<?php echo admin_url('usi_smartchoice_seo/pages'); ?>" class="btn btn-sm btn-default"><i class="fa fa-file-text-o"></i> <?php echo _l('usi_smartchoice_seo_pages'); ?></a>
<a href="<?php echo admin_url('usi_smartchoice_seo/keywords'); ?>" class="btn btn-sm btn-default"><i class="fa fa-search"></i> <?php echo _l('usi_smartchoice_seo_keywords'); ?></a>
<a href="<?php echo admin_url('usi_smartchoice_seo/reports'); ?>" class="btn btn-sm btn-default"><i class="fa fa-refresh"></i> <?php echo _l('usi_smartchoice_seo_reload'); ?></a>
<a href="<?php echo admin_url('usi_smartchoice_seo/export/reports?' . http_build_query($filters ?? [])); ?>" class="btn btn-sm btn-default"><i class="fa fa-download"></i> <?php echo _l('export'); ?></a>
<a href="<?php echo admin_url('usi_smartchoice_seo/sample_header/reports'); ?>" class="btn btn-sm btn-default"><i class="fa fa-table"></i> <?php echo _l('usi_smartchoice_seo_sample_header'); ?></a></div></div>
<p class="text-muted"><?php echo _l('usi_smartchoice_seo_reports_note'); ?></p>
<form method="get" class="usi-filter"><div class="row"><div class="col-md-3"><?php echo render_input('search','usi_smartchoice_seo_filter_header',$filters['search'] ?? ''); ?></div><div class="col-md-3"><?php echo render_date_input('date_from','usi_smartchoice_seo_date_from',$filters['date_from'] ?? ''); ?></div><div class="col-md-3"><?php echo render_date_input('date_to','usi_smartchoice_seo_date_to',$filters['date_to'] ?? ''); ?></div><div class="col-md-3 usi-filter-buttons"><button class="btn btn-sm btn-primary" type="submit"><?php echo _l('filter'); ?></button><a class="btn btn-sm btn-default" href="<?php echo admin_url('usi_smartchoice_seo/reports'); ?>"><?php echo _l('clear'); ?></a></div></div></form>
<?php echo form_open_multipart(admin_url('usi_smartchoice_seo/import/reports'), ['class'=>'usi-import']); ?><input type="file" name="import_file" accept=".csv"> <button class="btn btn-sm btn-default" type="submit"><i class="fa fa-upload"></i> <?php echo _l('import'); ?></button><?php echo form_close(); ?>
<?php echo form_open(admin_url('usi_smartchoice_seo/mass_delete_reports'), ['class'=>'usi-mass-form']); ?>
<div class="table-responsive"><table class="table table-striped table-condensed usi-compact-table"><thead><tr><th class="usi-check"><input type="checkbox" class="usi-check-all"></th><th><?php echo _l('date'); ?></th><th><?php echo _l('summary'); ?></th><th><?php echo _l('usi_smartchoice_seo_pages_created'); ?></th><th><?php echo _l('usi_smartchoice_seo_keywords_targeted'); ?></th><th><?php echo _l('usi_smartchoice_seo_issues_found'); ?></th><th><?php echo _l('options'); ?></th></tr></thead><tbody><?php foreach ($reports as $row) { ?><tr><td><input type="checkbox" name="ids[]" value="<?php echo (int)$row['id']; ?>"></td><td><?php echo html_escape($row['report_date']); ?></td><td class="text-left"><?php echo html_escape($row['summary']); ?></td><td><?php echo (int)$row['pages_created']; ?></td><td><?php echo (int)$row['keywords_targeted']; ?></td><td><?php echo (int)$row['issues_found']; ?></td><td><button type="button" class="btn btn-xs btn-default usi-view-report" data-summary="<?php echo html_escape($row['summary']); ?>"><?php echo _l('view'); ?></button></td></tr><?php } ?><?php if (empty($reports)) { ?><tr><td colspan="7" class="text-center text-muted"><?php echo _l('no_results_found'); ?></td></tr><?php } ?></tbody></table></div><?php if (has_permission('usi_smartchoice_seo','','delete')) { ?><div class="usi-table-footer"><button class="btn btn-sm btn-danger" type="submit"><i class="fa fa-trash"></i> <?php echo _l('usi_smartchoice_seo_mass_delete'); ?></button></div><?php } ?><?php echo form_close(); ?>
</div></div></div></div></div></div>
<?php init_tail(); ?></body></html>
