<?php defined('BASEPATH') or exit('No direct script access allowed'); ?>
<?php init_head(); ?>
<div id="wrapper"><div id="sc-enterprise-app"><div class="content">
<div class="sc-enterprise-header"><div><h1><?php echo html_escape($title); ?></h1><p><?php echo _l('enterprise_foundation_description'); ?></p></div><div class="sc-toolbar"><a href="<?php echo current_url(); ?>" class="btn btn-default btn-sm"><i class="fa-solid fa-rotate"></i> <?php echo _l('reload'); ?></a></div></div>

<div class="row sc-metric-grid">
<?php $cards=[[_l('enterprise_events'),$summary['events'],'fa-bolt'],[_l('enterprise_queue_jobs'),$summary['queue_total'],'fa-list-check'],[_l('enterprise_feature_flags'),$summary['feature_flags'],'fa-toggle-on'],[_l('enterprise_audit_records'),$summary['audit_records'],'fa-clipboard-list'],[_l('enterprise_field_rules'),$summary['field_rules'],'fa-user-lock'],[_l('enterprise_api_clients'),$summary['api_clients'],'fa-key']];foreach($cards as$c){ ?><div class="col-lg-4 col-md-6"><div class="panel_s sc-metric-card"><div class="panel-body"><i class="fa-solid <?php echo html_escape($c[2]); ?>"></i><div><span><?php echo html_escape($c[0]); ?></span><strong><?php echo html_escape($c[1]); ?></strong><div class="panel_s mtop20"><div class="panel-body"><h4><?php echo _l('enterprise_api_settings'); ?></h4><form method="post" action="<?php echo admin_url('smart_choice_enterprise_core/foundation_settings'); ?>"><?php echo form_hidden($this->security->get_csrf_token_name(),$this->security->get_csrf_hash()); ?><div class="row"><div class="col-md-5"><input class="form-control" name="enterprise_api_base_url" value="<?php echo html_escape(get_option('enterprise_api_base_url')); ?>" placeholder="API Base URL"></div><div class="col-md-5"><input class="form-control" name="enterprise_api_key" value="<?php echo html_escape(get_option('enterprise_api_key')); ?>" placeholder="API Key"></div><div class="col-md-2"><button class="btn btn-primary btn-block"><?php echo _l('save'); ?></button></div></div></form><hr><a class="btn btn-info btn-sm" href="<?php echo admin_url('smart_choice_enterprise_core/cron_guide'); ?>"><i class="fa fa-clock-o"></i> <?php echo _l('enterprise_cron_guide'); ?></a></div></div></div></div></div></div><?php } ?>
</div>
<div class="panel_s"><div class="panel-body"><h4><?php echo _l('enterprise_runtime_status'); ?></h4><table class="table table-bordered"><tr><th><?php echo _l('enterprise_module_version'); ?></th><td><?php echo html_escape($summary['module_version']); ?></td></tr><tr><th><?php echo _l('enterprise_last_cron_run'); ?></th><td><?php echo html_escape($summary['cron_last_run'] ?: _l('enterprise_not_available')); ?></td></tr><tr><th><?php echo _l('enterprise_api_status'); ?></th><td><?php echo _l('enterprise_api_disabled_by_default'); ?></td></tr></table></div></div>
</div></div></div><?php init_tail(); ?>