<?php defined('BASEPATH') or exit('No direct script access allowed'); init_head(); ?>
<div id="wrapper"><div class="content"><div class="row"><div class="col-md-12"><div class="panel_s sc-appointly-panel"><div class="panel-body">
<div class="tw-flex tw-items-center tw-justify-between tw-gap-2 tw-flex-wrap"><div><h4 class="tw-mt-0"><i class="fa fa-route text-success"></i> <?php echo _l('appointly_dispatch_board'); ?></h4><p class="text-muted tw-mb-0"><?php echo _l('appointly_dispatch_board_help'); ?></p></div><div class="btn-group"><a href="<?php echo admin_url('appointly/appointments'); ?>" class="btn btn-default btn-sm"><i class="fa fa-calendar-check-o"></i> <?php echo _l('appointment_appointments'); ?></a><a href="<?php echo admin_url('appointly/smartchoice/notification_log'); ?>" class="btn btn-warning btn-sm"><i class="fa fa-list"></i> Notification Log</a><button type="button" class="btn btn-success btn-sm" data-toggle="modal" data-target="#appointlyTestNotificationModal"><i class="fa fa-bell"></i> <?php echo _l('appointly_test_notification'); ?></button><button class="btn btn-info btn-sm" onclick="location.reload();"><i class="fa fa-refresh"></i> <?php echo _l('reload'); ?></button></div></div><hr>
<div class="alert alert-info">Use the status control to notify the customer when the appointment is confirmed, the installer is on the way, 15 minutes away, arrived, in progress, completed, or ready for follow-up. Every action is recorded in Notification Log.</div>
<div class="table-responsive"><table class="table table-striped table-hover dt-table"><thead><tr><th><?php echo _l('appointment'); ?></th><th><?php echo _l('date'); ?></th><th><?php echo _l('time'); ?></th><th><?php echo _l('status'); ?></th><th><?php echo _l('staff'); ?></th><th>Dispatch Action</th><th><?php echo _l('options'); ?></th></tr></thead><tbody>
<?php foreach ($appointments as $appointment) { ?><tr><td><?php echo html_escape($appointment['subject'] ?? 'Appointment'); ?></td><td><?php echo _d($appointment['date']); ?></td><td><?php echo html_escape(($appointment['start_hour'] ?? '').' - '.($appointment['end_hour'] ?? '')); ?></td><td><span class="label label-default"><?php echo html_escape(ucwords(str_replace('-', ' ', $appointment['status'] ?? ''))); ?></span></td><td><?php echo !empty($appointment['provider_id']) ? get_staff_full_name($appointment['provider_id']) : '-'; ?></td><td>
<?php echo form_open(admin_url('appointly/smartchoice/update_dispatch_status'), ['class'=>'form-inline']); ?><input type="hidden" name="appointment_id" value="<?php echo (int)$appointment['id']; ?>"><select name="status" class="form-control input-sm" required><option value="">Select status</option><option value="confirmed">Confirmed</option><option value="on-the-way">Installer On The Way</option><option value="15-minutes-away">15 Minutes Away</option><option value="arrived">Arrived</option><option value="in-progress">In Progress</option><option value="completed">Completed</option><option value="follow-up">Follow Up</option><option value="cancelled">Cancelled</option><option value="no-show">No Show</option></select> <button type="submit" class="btn btn-primary btn-xs"><i class="fa fa-paper-plane"></i> Update & Notify</button><?php echo form_close(); ?>
</td><td><a href="<?php echo admin_url('appointly/appointments/view?appointment_id='.(int)$appointment['id']); ?>" class="btn btn-default btn-xs"><i class="fa fa-eye"></i> <?php echo _l('view'); ?></a></td></tr><?php } ?>
</tbody></table></div></div></div></div></div></div></div>
<div class="modal fade" id="appointlyTestNotificationModal"><div class="modal-dialog"><div class="modal-content"><?php echo form_open(admin_url('appointly/smartchoice/test_notification')); ?><div class="modal-header"><button type="button" class="close" data-dismiss="modal">&times;</button><h4>Test Appointment Notification</h4></div><div class="modal-body"><div class="alert alert-info">Choose exactly who receives the test, the channel, and the message.</div><?php $CI=&get_instance();$rows=$CI->db->where('active',1)->order_by('firstname','ASC')->get(db_prefix().'staff')->result_array();$opts=[];foreach($rows as $x){$opts[]=['id'=>$x['staffid'],'name'=>trim($x['firstname'].' '.$x['lastname'])];}echo render_select('recipient_staff_id',$opts,['id','name'],'Test recipient',get_staff_user_id());echo render_select('channel',[['id'=>'crm','name'=>'CRM internal notification'],['id'=>'email','name'=>'Employee email'],['id'=>'telegram','name'=>'Telegram default chat']],['id','name'],'Delivery channel','crm');echo render_textarea('message','Test message',get_option('appointly_sc_test_notification_text') ?: 'Smart Choice Appointments test notification.');?></div><div class="modal-footer"><button class="btn btn-default" data-dismiss="modal" type="button">Close</button><button class="btn btn-success" type="submit">Send Test</button></div><?php echo form_close(); ?></div></div></div><?php init_tail(); ?>
