<?php defined('BASEPATH') or exit('No direct script access allowed'); init_head(); ?>
<div id="wrapper"><div class="content"><div class="panel_s"><div class="panel-body sc-appointly-help">
<h3><i class="fa-solid fa-calendar-check text-success"></i> Smart Choice Appointments Training Guide</h3>
<p>This guide is for first-time users. Complete the setup steps before sending live customer notifications.</p>
<h4>1. Initial setup</h4><ol><li>Open <b>Setup → Settings → Appointly</b> and review dashboard, booking form, invoice, tax, notification, calendar, and integration settings.</li><li>Open <b>Appointments → Company Schedule</b> and set normal business hours.</li><li>Open <b>Staff Working Hours</b> and confirm who uses the company schedule.</li><li>Open <b>Services</b>, assign providers, and drag services into the desired booking-form order.</li><li>Open <b>Dispatch Board</b> and test each notification channel.</li></ol>
<h4>2. Recommended status flow and how to change it</h4><pre>Scheduled → Confirmed → Installer On The Way → 10 Minutes Away → Arrived → In Progress → Completed → Follow Up</pre><ol><li>Open the appointment status configuration area.</li><li>Create or rename statuses to match this flow.</li><li>Do not delete statuses already used by appointments without a full database backup.</li><li>Map notifications to Confirmed, On The Way, 10 Minutes Away, Arrived, and Completed.</li><li>Test each transition using a test appointment.</li></ol>
<h4>3. Installer tracking and customer notices</h4><p>Every appointment should include customer name, mobile phone, email, service address, assigned employee, service, date, time, and notes. The employee profile should include a current picture and phone number.</p><ol><li><b>On The Way:</b> send employee name, company phone number, profile picture or secure tracking link, and ETA.</li><li><b>10 Minutes Away:</b> send the saved ten-minute message.</li><li><b>Arrived:</b> record arrival time.</li><li><b>Completed:</b> stop tracking and send follow-up instructions.</li></ol><div class="alert alert-warning">Automatic 10-minute alerts require live GPS/ETA data from the installer tracker. The toggle alone cannot calculate distance.</div>
<h4>4. Notification testing</h4><ol><li>Open Dispatch Board.</li><li>Choose the employee, delivery channel, and exact message.</li><li>The result identifies who received it and where it was sent.</li><li>Verify actual delivery before enabling automation.</li></ol>
<h4>5. Telegram</h4><ol><li>Create a bot in BotFather.</li><li>Start the bot from the receiving chat or group.</li><li>Save the bot token and chat ID.</li><li>Enable Telegram.</li><li>Health Check passes only when the toggle, token, and chat ID are all present.</li></ol>
<h4>6. Facebook / Meta</h4><p>Facebook delivery requires a Meta app, Page token, approved permissions, recipient PSID, webhook, and compliance with Meta messaging windows. The toggle is only a readiness control.</p>
<h4>7. Recommended services</h4><ol><li>Free In-Home Consultation</li><li>Remodeling & Renovation Planning Session</li><li>Project Estimate & Scope Review</li><li>Engineering / Permit Consultation</li><li>Repair & Troubleshooting Visit</li></ol>
</div></div></div></div><?php init_tail(); ?>