<?php defined('BASEPATH') or exit('No direct script access allowed'); init_head(); ?>
<div id="wrapper"><div class="content"><div class="panel_s"><div class="panel-body">
<?php $this->load->view('usi_smartchoice_seo/partials/top'); ?>
<div class="sc-toolbar"><h4><i class="fa fa-graduation-cap"></i> <?php echo html_escape($title); ?></h4><div><a class="btn btn-primary btn-sm" href="<?php echo admin_url('usi_smartchoice_seo/ai_training_item'); ?>">New Training Rule</a><a class="btn btn-default btn-sm" href="<?php echo admin_url('usi_smartchoice_seo/sample_header/ai_training'); ?>">Sample Header</a><a class="btn btn-default btn-sm" href="<?php echo admin_url('usi_smartchoice_seo/export/ai_training'); ?>">Export</a><a class="btn btn-default btn-sm" href="<?php echo admin_url('usi_smartchoice_seo/ai_training'); ?>">Reload</a></div></div>
<form method="get" class="sc-filter"><input type="text" name="search" class="form-control" placeholder="Filter title, category, prompt, or status" value="<?php echo html_escape($filters['search'] ?? ''); ?>"></form>
<?php echo form_open(admin_url('usi_smartchoice_seo/mass_delete_ai_training')); ?><div class="table-responsive"><table class="table table-striped table-condensed sc-table"><thead><tr><th><input type="checkbox" class="sc-check-all"></th><th>Title</th><th>Category</th><th>Status</th><th>Prompt</th><th>Created</th><th class="text-center">Actions</th></tr></thead><tbody>
<?php foreach ($training as $row) { ?><tr><td><input type="checkbox" name="ids[]" value="<?php echo (int)$row['id']; ?>"></td><td><?php echo html_escape($row['title']); ?></td><td><?php echo html_escape($row['category']); ?></td><td><?php echo html_escape($row['status']); ?></td><td><?php echo html_escape(mb_substr((string)$row['prompt_text'], 0, 120)); ?></td><td><?php echo html_escape($row['created_at']); ?></td><td class="text-center"><a class="btn btn-default btn-xs" href="<?php echo admin_url('usi_smartchoice_seo/ai_training_item/' . (int)$row['id']); ?>">Edit</a> <a class="btn btn-danger btn-xs _delete" href="<?php echo admin_url('usi_smartchoice_seo/delete_ai_training/' . (int)$row['id']); ?>">Delete</a></td></tr><?php } ?>
<?php if (empty($training)) { ?><tr><td colspan="7" class="text-center text-muted">No AI training rules found.</td></tr><?php } ?>
</tbody></table></div><button type="submit" class="btn btn-danger btn-sm">Mass Delete</button><?php echo form_close(); ?>
</div></div></div></div><?php init_tail(); ?>
